### ISSUE TITLE
请问作者有讨论群之类的吗？

### ISSUE THREAD

**Issue by David-YJY** [alovajs/alova#102]
### 你在什么情况下，需要这个功能解决什么问题？

请问作者有讨论群之类的吗？

### 你期望的 API 是什么样子的？

请问作者有讨论群之类的吗？

**Comment by David-YJY** [comment]
ok，谢谢回答

**Comment by JOU-amjs** [comment]
建立交流社区后到时候我再来这边告诉你😁

**Comment by JOU-amjs** [comment]
迟来的交流群，我过来通知你啦，到这边加入https://alova.js.org/zh-CN/tutorial/get-started/overview#%E5%8A%A0%E5%85%A5%E4%BA%A4%E6%B5%81%E7%A4%BE%E5%8C%BA
