### ISSUE TITLE
希望能加强TS提示

### ISSUE THREAD

**Issue by ykxbc** [alovajs/alova#103]
### 你在什么情况下，需要这个功能解决什么问题？

`const { data, loading, send } = useRequest((query: { q: number }) => doTest(query), {
  initialData: "",
  immediate: false,
})`

目前send类型是`(...args: any[]) => Promise<unknown>`，期望得到准确的提示：`({q:number})=>Prmise</*...*/>`

### 你期望的 API 是什么样子的？

希望得到更好的ts提示

**Comment by kunkuntang** [comment]
求 补充一下send 类型 type SendHandler<R> = (...args: any[]) => Promise<R>; 的入参提示

**Comment by xywc-s** [comment]
@JOU-amjs  说一点我个人的愚见, 这个类型提示我觉得还是非常有必要实现的, 毕竟发请求就是最基本的功能, 如果发起请求连接口参数类型都不提示, 那相当于无视了TS带来的类型增强能力, 也算是废掉了alova库的一条胳膊. 希望alova团队的各位大佬能收集使用意见, 从实际使用场景和使用频次的角度重新考量一下取舍.
就像推荐alova库的博文里面说的, 类似于axios库的response类型, 只要使用了全局响应拦截改变了默认返回值的类型, 那每个接口声明都要单独传入response类型来修正默认的AxiosResponse类型提示. 
alova库的思想很好, 它的很多特性都是基于实际使用场景来设计开发的, 在各大UI框架都全面拥抱TS的当下, alova作为一个与UI框架高度耦合的请求策略库, 在类型友好方面也一定要跟上才行.
在第一次看到alova库的时候我挺兴奋, 因为在vue3.2发布后, 我们团队将项目开发基础模板从vue2切换到vue3, 也针对axios的问题特别封装过useFetch, useInterceptor等基于composition api的实用函数. 目的正是为了让请求调用变得更加优雅, 并且类型提示更好友好, 而alova在设计方面显然比我们的产物要更加全面和优秀. 但是我目前仍然没有转换到alova上, 原因正是alova的类型提示问题.
除了send的参数类型, 还有Method的config参数类型目前也是any.
![image](https://github.com/alovajs/alova/assets/31307553/11d9b5e2-5014-4eb7-a814-1442280d847b)
最后我很高兴能有这么优秀的库诞生, 希望它越来越好.❤️

**Comment by z91300** [comment]
我现在也是在尝试切换至Alova，同样认为这个很重要，参数的类型提示非常必要啊0.0

**Comment by JOU-amjs** [comment]
> 从实际使用场景和使用频次的角度重新考量一下取舍
@xywc-s 很高兴你能喜欢alova，你的上面这句话让我重新思考了这个问题。
@z91300 也不是没办法加，而是需要在设计考量上决定如何来做，如果大家需要这个功能，那为什么不加上呢

目前来说，从设计方案上需要达到`send`函数自动提示，同时也可以不完全受use hooks的handler限制，因为有些时候会专门需要传参到`onSuccess`等回调函数中

我暂时还没确定方案，可否一起来讨论一下合适的方案

**Comment by JOU-amjs** [comment]
https://github.com/alovajs/alova/issues/158 我开了一个新的讨论帖，共同探讨合适的方案，感兴趣的话可以一同参与进来 @xywc-s @z91300 @ykxbc @kunkuntang
