### ISSUE TITLE
[Bug Report] immediate:false in useRequest doesn't seem to work

### ISSUE THREAD

**Issue by proddy** [alovajs/alova#105]
### Reproduction Link

https://codesandbox.io/p/sandbox/alova-immediate-forked-ocb5tf?file=%2Fsrc%2FApp.tsx

### alova Version

2.5.4

### Describe the Bug

Hi, I'm loving this library and slowly migrating my code from Axios to Alova. I came across one issue, which I'm not sure is a bug or not.

On React, using `useRequest` with the parameter `immediate: false` doesn't seem to work for me. The request call is always fired when the page is loaded. This happens on both using a `requestAdapter` of `xhrRequestAdapter()` and `GlobalFetch()`.

I can create a sandbox and try and reproduce, but before doing that I wondered whether if this is known issue at all?

### Reproduce Steps

When loading the page, all useRequests are fired, even if the immediate flag is set to false.

### Device / Browser / Browser Version

on all browsers I tested (edge/chrome/safari)

**Comment by JOU-amjs** [comment]
Hi proddy! thanks for supporting alova.☺️
If it's the same as what you describe, I think it should be a bug. but this case is already passed unit test, [see here(second test)](https://github.com/alovajs/alova/blob/main/test/browser/hooks/useRequest-react.spec.tsx)
so, you can provide a demo which can reproduce the bug, I will resolve it as soon as possible.

**Comment by proddy** [comment]
Hey, thanks for the quick response. I cooked up a really small sandbox app [here](https://codesandbox.io/p/sandbox/alova-immediate-forked-ocb5tf?file=%2Fsrc%2FApp.tsx) . When you run it, and monitor the traffic using the browser dev tools->Network you'll see it'll always make the Request even if the `immediate` flag is false. Hope it helps!

**Comment by JOU-amjs** [comment]
@proddy I will see it tomorrow. now I have to go to sleep.🥱

**Comment by JOU-amjs** [comment]
@proddy Now the bug is fixed. the reason is react strict mode will emit `useEffect` twice and the second time is going to send a request

**Comment by proddy** [comment]
> @proddy Now the bug is fixed. the reason is react strict mode will emit `useEffect` twice and the second time is going to send a request

Thanks for the quick fix, much appreciated. I was thinking last night too it may be related to the Strict mode so good catch. I'm really loving this library.

**Comment by JOU-amjs** [comment]
😁😁😁
Another small secret is that alova's shared request can prevent sending request twice during initialization in react strict mode
