### ISSUE TITLE
[Feature Request] useRequest data回调三次

### ISSUE THREAD

**Issue by GetWebHB** [alovajs/alova#108]
### Reproduction Link

https://stackblitz.com/edit/vitejs-vite-ce6qjt?file=package.json

### alova Version

2.5.5

### Describe the Bug

我发现它这个data的callback会回调三次，如果请求pending时间较短的时候，数据回调两次，初始化一次

### Reproduce Steps

网络请求

**Comment by JOU-amjs** [comment]
我看了你提供的demo，按目前的设计来看，在react下初始化时发起请求确实会执行三次组件渲染函数，它们分别会在初始化、请求发出时loading设置为true、请求响应后loading设置为false时执行。

这其实是react性能范畴的问题，也确实可以优化成两次渲染，我们在不久的将来会优化它。
现在你可以放心使用，这个目前也不会引起bug。

**Comment by GetWebHB** [comment]
感谢，我也试着解决一下

**Comment by leezb101** [comment]
这个问题在VueHooks中也有，不过目前我观察到到是会回调两次，走两次onSuccess
