### ISSUE TITLE
[Feature Request] alova支持流式接口响应输入吗？ChatGPT流式响应

### ISSUE THREAD

**Issue by yixinhong** [alovajs/alova#110]
### 你在什么情况下，需要这个功能解决什么问题？

ChatGPT流式响应

### 你期望的 API 是什么样子的？

ChatGPT流式响应

**Comment by JOU-amjs** [comment]
@yixinhong 很抱歉，目前还不支持SSE。
不过我已经记下来了，后续将排上日程，实现后将会在这边回复你。
非常感谢你的反馈哦！🤞🤞🤞

**Comment by JOU-amjs** [comment]
已排上日程，[设计文档点此查看](https://alova.js.org/tutorial/strategy/useSSE)

**Comment by MeetinaXD** [comment]
这个功能已经在 [#62](https://github.com/alovajs/scene/pull/62) 中实现。

可以更新 scene 库到最新版本体验。

文档：[Server-sent events发送请求](https://alova.js.org/zh-CN/tutorial/strategy/useSSE/)
