### ISSUE TITLE
localCache只有在设置为0时才能拉取成功吗？

### ISSUE THREAD

**Issue by David-YJY** [alovajs/alova#111]
### Reproduction Link

无

### alova Version

2.5.0

### Describe the Bug

请问在使用 fetch 数据拉取的时候，对应的接口实例，要设置 localCache: 0，才能拉取成功，我实际使用中，发现不设置localCache: 0 是不会去重新拉取的。想问下是这样的吗？

### Reproduce Steps

举例：
```javascript
export const getActivityDetailApi = (activityId) => {
  return alovaInstance.Get(
    `******/${activityId}`,
    {
      localCache: 0
    }
  );
}

// 调用：
fetch(getActivityDetailApi(1));
```

### Device / Browser / Browser Version

uniapp、vue3

**Comment by JOU-amjs** [comment]
没有这个限制，目前是不管有没有设置`localCache`都会去拉取数据，只是对于`localCache: 0`时，拉取的数据不会缓存下来，这是alova可以优化的一个点。

我这边有个[demo](https://codesandbox.io/p/sandbox/github/alovajs/alova-examples/tree/main/packages/prefetch?embed=1)，你可以尝试下，`localCache`有没有设置都会进行拉取。

如果你的问题不是这样的情况，可否提供一个简单的可复现Demo，我会尽快帮你解决这个问题。

**Comment by David-YJY** [comment]
欧克，我试试。我看看你的demo，我目前是如果不设置为0，无法重新拉取。
其他的配置，我使用了unplugin-auto-import 自动导入API，没有在页面中去手动导入，我一会也看下是不是这个原因。感谢

**Comment by JOU-amjs** [comment]
应该和`unplugin-auto-import`关闭不大，如果没有引入的话是会报`not define`错误。

**Comment by David-YJY** [comment]
嗯，可能是我开始没有描述清楚。
我遇到的业务问题，一个报名的活动，列表中item会展示一个报名人数的信息，当我点击进入详情报名，报名成功之后，我需要更新列表的报名人数和详情的报名人数，让它们保持一致，此时不设置 `localCache: 0`，他还是从缓存数据中取数据。所以我去设置 `localCache: 0` 才会调用接口，然后拉取到最新数据。
应该是我的理解有问题，或者说应该用占位缓存模式或者其他方式。

**Comment by JOU-amjs** [comment]
我明白了你的使用场景了，这种情况是因为fetch数据时会命中缓存导致不再发起请求的。有四种解决方案来处理：

1. 设置`useFetcher({ force: true })`来开启强制拉取，即使命中缓存也会穿透它发起请求，但这可能会影响所有拉取数据都穿透缓存。[文档在这](https://alova.js.org/zh-CN/learning/use-fetcher/#%E8%AE%BE%E7%BD%AE%E9%9D%99%E6%80%81%E5%80%BC)
2. 如果你只希望对这个拉取穿透缓存，可以通过传参的形式动态开启是否强制拉取，[文档在这](https://alova.js.org/zh-CN/learning/use-fetcher/#%E5%8A%A8%E6%80%81%E8%AE%BE%E7%BD%AE-force-%E5%80%BC)
3. 先手动调用`invalidateCache`让列表缓存数据失效，再进行拉取数据。[文档在这](https://alova.js.org/zh-CN/learning/invalidate-response-cache)
4. 通过为列表接口设置`hitSource`自动失效缓存，再拉取数据也不会命中缓存。[文档在这](https://alova.js.org/zh-CN/next-step/auto-invalidate-cache)

**Comment by David-YJY** [comment]
ok，我都去看一遍。感谢你！！！

**Comment by JOU-amjs** [comment]
选择适合自己的方案就好。😁

**Comment by David-YJY** [comment]
嗯，是的🤭，我在多研究一下
