### ISSUE TITLE
alova该如何发送多个不同后台地址的请求？baseUrl设置完在哪些地方可以更改？

### ISSUE THREAD

**Issue by djkloop** [alovajs/alova#116]
### 重现链接

https://codesandbox.io/

### alova 版本

2.6.0

### 描述一下你遇到的问题。

```shell
alova该如何发送多个不同后台地址的请求？baseUrl设置完在哪些地方可以更改？
现在后台都是微服务可能对应着不同的url地址，
这个创建实例的时候已经设置了baseUrl但是怎么单独请求的时候修改单独的baseUrl?（这个应该叫请求级？
```

### 重现步骤

无

### 设备/浏览器/浏览器版本

win10/edge chrome/latest

**Comment by JOU-amjs** [comment]
@djkloop  对于不同baseurl，你可以创建多个alova实例来实现，每个alova实例对应一个baseurl。可能有些alova实例配置需要共用的，例如响应处理的回调函数，可以单独写出来赋值给不同alova实例

**Comment by djkloop** [comment]
@JOU-amjs 好的谢谢。感觉创建多个实例有点麻烦要是能动态替换baseUrl就好了

**Comment by JOU-amjs** [comment]
还有这么特殊的需求，你可以这样动态设置请求级baseURL
```javascript
const method = alovaInst.Get('/xxxx');
method.baseURL = 'https:///new_url';

useRequest(method); // 会向新baseURL发请求
method.send(); // 也会向新baseURL发请求
```

**Comment by djkloop** [comment]
@JOU-amjs 好的谢谢。
