### ISSUE TITLE
[Feature Request] 可以支持 solidjs 的的使用吗

### ISSUE THREAD

**Issue by Yanren1225** [alovajs/alova#117]
### 你在什么情况下，需要这个功能解决什么问题？

可以支持 [solidjs](https://www.solidjs.com/) 的的使用吗？

### 你期望的 API 是什么样子的？

solidjs 与 react 有着相似的响应式使用方法，应该可以很方便的支持

**Comment by JOU-amjs** [comment]
solidjs在我们的计划中，但短期内暂时还没计划支持solidjs。
从使用者的角度来说可能写一个statesHook就可以了，但从alova的角度来说，工作量是比较大的，还需要通过单元测试，typescript类型兼容，scene请求策略hooks的兼容和测试。

如果需要，你可以试试[自定义statesHook](https://alova.js.org/zh-CN/advanced/custom-stateshook/)，可以快速满足你的需求。
不着急的话，也可以稍微耐心等待我们提供。

**Comment by tendant** [comment]
请问这个已经实现了吗？

可以提供一个简单的statesHook 吗？这样对于初次接触Alova 的用户会更友好一点。

**Comment by JOU-amjs** [comment]
有人愿意贡献你的一份力量吗？ 请阅读[贡献指南](https://github.com/alovajs/alova/blob/main/CONTRIBUTING.md)

**Comment by wintsa123** [comment]
solid太小众了吧，玩这种新框架的，我不信没能力自己写statesHook

**Comment by dove-xk** [comment]
这有一个简单的实现，没有完整测试，不保证100%可用，也不提供售后
```ts
const solidJsHook = {
  create: (data) => createSignal(data),
  export: (states) => states[0],
  dehydrate: (state: any) => state(),
  update: (newVal, states) => {
    Object.keys(newVal).forEach((key) => {
      states[key][1](newVal[key]);
    });
  },
  effectRequest({ handler, removeStates, immediate, watchingStates }) {
    onCleanup(removeStates);

    immediate && handler();

    let timer: any;
    (watchingStates || []).forEach((state, i) => {
      createEffect(() => {
        state();
        timer && clearTimeout(timer);
        timer = setTimeout(() => {
          handler(i);
          clearTimeout(timer);
          timer = undefined;
        }, 8);
      });
    });
  },
};

```

**Comment by JOU-amjs** [comment]
@thinkeW 非常感谢你的贡献啊！🤞
只是要到达可用状态的话，还需要通过单元测试才可以正常投入使用。
如果有兴趣的话，可以在项目目录下新建`test/browser/hooks/solid`并模仿react的hooks测试用例测试

**Comment by 1075488066** [comment]
> solidjs在我们的计划中，但短期内暂时还没计划支持solidjs。
> 从使用者的角度来说可能写一个statesHook就可以了，但从alova的角度来说，工作量是比较大的，还需要通过单元测试，typescript类型兼容，scene请求策略hooks的兼容和测试。
> 
> 如果需要，你可以试试[自定义statesHook](https://alova.js.org/zh-CN/tutorial/advanced/custom-stateshook/)，可以快速满足你的需求。
> 不着急的话，也可以稍微耐心等待我们提供。

我觉得原生微信小程序可以支持下，其他web框架类似的功能不怎么缺。

**Comment by JOU-amjs** [comment]
@1075488066  原生小程序支持计划中，期待一下哦

**Comment by JOU-amjs** [comment]
在alova@3.2.0中已经支持了solid
