### ISSUE TITLE
[Bug Report] beforeRequest 内调用 abort无效

### ISSUE THREAD

**Issue by Aaminly** [alovajs/alova#120]
### 重现链接

无

### alova 版本

2.6.1

### 描述一下你遇到的问题。

beforeRequest 内调用 abort无效，原因是  
class Method 构造函数执行两次，导致this.abort 为 noop
但在context上挂载可用
```javascript
/**
   * 直接发出请求，返回promise对象
   */
  public send(forceRequest = falseValue): Promise<R> {
    const { response, abort } = sendRequest(this, forceRequest);
    this.abort = abort;
    // 增加到context上可用
    this.context.abort = abort
    return response();
  }
```

### 重现步骤

beforeRequest 内调用 abort无效

**Comment by JOU-amjs** [comment]
触发beforeRequest时，请求还未真正发出，此时的abort自然是无效的。
可否稍微描述一下你的使用场景。

**Comment by Aaminly** [comment]
比如有的接口未登录时不想发起，同时不想在业务组件内部写判断，因为这类接口会大量存在，这时候在拦截器做统一处理，未登录时拦截掉请求，不让继续发出，不知道我这样描述清楚不

**Comment by Aaminly** [comment]
> 触发beforeRequest时，请求还未真正发出，此时的abort自然是无效的。 可否稍微描述一下你的使用场景。

比如有的接口未登录时不想发起，同时不想在业务组件内部写判断，因为这类接口会大量存在，这时候在拦截器做统一处理，未登录时拦截掉请求，不让继续发出，不知道我这样描述清楚不

**Comment by Aaminly** [comment]
> 触发beforeRequest时，请求还未真正发出，此时的abort自然是无效的。 可否稍微描述一下你的使用场景。

正常的做法肯定是设置immediate: true, 解构出send方法，做watch  isLogin的监听是否发送请求，但是这种做法感觉不优雅，是否可以在beforeRequest里直接cancel掉请求，最好是让它压根不出现在network里面

**Comment by Aaminly** [comment]
> 你可以尝试下以下这些方案：
> 
> **1. 在beforeRequest中抛出错误** 你可以在beforeRequest中判断，如果不需要发送请求则抛出一个自定义错误，只是会在请求的地方接收到一个错误，你只需要try catch不处理它就可以了，或者通过自定义的错误内容判断是否需要处理。
> 
> **2. 使用中间件拦截请求** 如果你是使用`useRequest`或`useWatcher`这些use hooks发送请求的，可以设置`middleware`函数，在内部判断是否需要发出请求，不需要则不调用`next`即可，这样相比上面的，不会触发请求也不会抛出错误，你可以单独编写`middleware`函数，在需要使用到的use hook中设置上去。[中间件详解在这](https://alova.js.org/zh-CN/advanced/middleware)

这两个做法其实和在组件业务组件调用地方  设置immediate: true, 解构出send方法，做watch isLogin的监听是否发送请求   没有本质区别的，就是想在拦截器统一处理，比如beforeRequest返回 return false 就不发出当前请求

**Comment by Aaminly** [comment]
> 你可以尝试下以下这些方案：
> 
> **1. 在beforeRequest中抛出错误** 你可以在beforeRequest中判断，如果不需要发送请求则抛出一个自定义错误，只是会在请求的地方接收到一个错误，你只需要try catch不处理它就可以了，或者通过自定义的错误内容判断是否需要处理。
> 
> **2. 使用中间件拦截请求** 如果你是使用`useRequest`或`useWatcher`这些use hooks发送请求的，可以设置`middleware`函数，在内部判断是否需要发出请求，不需要则不调用`next`即可，这样相比上面的，不会触发请求也不会抛出错误，你可以单独编写`middleware`函数，在需要使用到的use hook中设置上去。[中间件详解在这](https://alova.js.org/zh-CN/advanced/middleware)

如果中间件支持全局设置且能在中间件访问当前method实例，或许可以尝试一下，但目前没看到此类文档说明

**Comment by Aaminly** [comment]
> 你可以尝试下以下这些方案：
> 
> **1. 在beforeRequest中抛出错误** 你可以在beforeRequest中判断，如果不需要发送请求则抛出一个自定义错误，只是会在请求的地方接收到一个错误，你只需要try catch不处理它就可以了，或者通过自定义的错误内容判断是否需要处理。
> 
> **2. 使用中间件拦截请求** 如果你是使用`useRequest`或`useWatcher`这些use hooks发送请求的，可以设置`middleware`函数，在内部判断是否需要发出请求，不需要则不调用`next`即可，这样相比上面的，不会触发请求也不会抛出错误，你可以单独编写`middleware`函数，在需要使用到的use hook中设置上去。[中间件详解在这](https://alova.js.org/zh-CN/advanced/middleware)

只是会在请求的地方接收到一个错误，你只需要try catch不处理它就可以了，或者通过自定义的错误内容判断是否需要处理。

就是想无感的去在全局拦截器做处理，不侵入业务逻辑做耦合的如try catch 或者 useRequest 内部的 middleware 中间件书写..

**Comment by JOU-amjs** [comment]
> 比如beforeRequest返回 return false 就不发出当前请求
这是个好建议，这两天考虑更新一个版本解决你的问题

**Comment by JOU-amjs** [comment]
在设计通过beforeRequest阻止发送请求时，遇到了一个难题，就是当还未发出请求时阻止请求，那么在发送请求的位置获得的promise不论转换成什么状态都不太合适。
1、保持pending状态，那么await后的代码永远不会执行
2、改为resolve状态，resolve状态表示请求成功，阻止发送请求显然也不合适
3、reject状态，这个还是比较合适的，但和在beforeRequest抛出错误没有差别，也没有达到你希望的效果。

你可以来聊聊对这个问题，在你所遇到的场景下，你是怎么看的吗

**Comment by JOU-amjs** [comment]
承接上一个回复，具体是这样的，假设有一个这样的请求发送：
```javascript
// vue代码
const res = await someMethodInstance.send();
list.value = res.list;
```
这边将会等待一个promise对象resolve，再将返回数据赋值给`list`的`ref`值，如果这个请求在`beforeRequest`中阻止了这个请求的发送，那么这个promise可能为以下3个状态（promise的状态可以通过代码控制）

1. 保持pending状态，那么`list`的赋值永远不会被触发，而且处于pending状态的promise容易导致[内存溢出问题](https://zhuanlan.zhihu.com/p/385764204)；
2. 改为resolve状态，但此时res的值应该是什么呢？可能为`undefined`，那赋值将报错，也可能自己模拟一个返回值，那么不同请求会有不同的模拟返回值，在`beforeRequest`中也无法做到统一处理；
3. 改为reject状态，此时也需要在单独处理；

因此可能在请求前统一阻止发送请求的方案，需要对特定请求处理较为合适，或者需要自己在项目中调整请求顺序，例如在vue的路由钩子内判断并中断对应的页面跳转，这个是可以做到的。

> beforeRequest 内调用 abort无效，原因是class Method 构造函数执行两次，导致this.abort 为 noop

不过你提到的以上问题，确实是一个bug，为了实现缓存查找的正确性，在请求时内部会克隆一个新的method对象，这个新对象上的abort指向不正确导致了你说的问题，稍后修复一下。

**Comment by Aaminly** [comment]
> 改为resolve状态，但此时res的值应该是什么呢？可能为undefined，那赋值将报错，也可能自己模拟一个返回值，那么不同请求会有不同的模拟返回值，在beforeRequest中也无法做到统一处理；

确实我忽视了该请求已经发出，要对回调做处理。这里我感觉应该是resolve状态，此时如果没给 initialData 初始值，就应该是 undefined   这种表现就和 useRequest 所解构出的 data 表现一致，如果是手动发送请求，解构出的 data 在没给 initialData 的情况下就是 undefined 。所以此时应该把特定接口需要中止后的容错逻辑交由用户自己把控。

**Comment by Aaminly** [comment]
另外res的值，我感觉可以给回到  发送请求前的默认值：data 、loading、error 这些，其中data可能为 undefined。

**Comment by JOU-amjs** [comment]
@Aaminly 因为alova的请求方式有两种。

一种是`useRequest`、`useWatcher`等use hook的形式，也就是你现在所提到的，会返回data 、loading、error 这些，也可以通过`initialData`设置默认值。

另一种是直接通过method实例发送请求，就是我上面写的那种情况。
```javascript
const res = await someMethodInstance.send();
list.value = res.list;
```
在这种情况下是不能设置`initialData`的，它就像`axios`一样直接发送请求并且接收一个promise。

而以上两种情况，都会经过`beforeRequest`拦截，你给的方案可能没有考虑到第二种直接发送请求的情况，就拿这边我给出的示例代码来说，正常请求将返回一个list值，如果阻止请求返回带`undefined`的resolve状态promise，那么没有在这边针对处理，运行到`list.value = res.list;`时也将会报错。

因此，从alova库的使用场景的角度出发，可得出一个结论是，不管获得的resolve状态、还是reject状态的promise都是需要自行处理的，而如果针对use hook单独处理阻止发送请求的情况，将显得这个方案不具有普适性，可能会造成alova越来越复杂，有违alova的设计原则。

这是我在思考设计这个功能的时候所担忧的，在理解了我的想法后，你有什么更好的方案吗？

**Comment by JOU-amjs** [comment]
> beforeRequest 内调用 abort无效，原因是class Method 构造函数执行两次，导致this.abort 为 noop

这个问题已解决，请升级到2.6.2可用。（帖子已被[semantic-release](https://github.com/semantic-release/semantic-release)自动关闭）

**Comment by Aaminly** [comment]
> 在这种情况下是不能设置initialData的，它就像axios一样直接发送请求并且接收一个promise。

```javascript
const res = await someMethodInstance.send();
list.value = res.list;
```

是否可以给   someMethodInstance   增加设置初始值的方法来解决这个问题，如：

```javascript
someMethodInstance.setInitialData([])
const res = await someMethodInstance.send();
list.value = res.list;
```

这个问题的出发点是：需要在某些场景下拦截掉特定请求不发出，那么开发者必然需要去处理这些请求不发出后，请求的位置所作出的响应结果相应的容错。具体场景也是需要在 beforeRequest 做特定请求的拦截判断处理的，如拿到登录状态判断等等。

**Comment by kenixFog** [comment]
我也想要这样的效果，就是不管直接请求，还是延迟请求，只要beforeRequest中抛出异常，alova内部会自动终止本次请求，并将请求的结果，设置为initialData，感觉这个需求应该有应用场景，比如判断token，判断参数是否有效等等。好多try catch，总感觉膈应人~~哈哈

**Comment by JOU-amjs** [comment]
@kenixFog 目前就是这样的，在beforerequest中抛出错误将会终止请求，并在请求处接收到错误，如果有initialdata也将保持这个数据

**Comment by Aaminly** [comment]
我最近又思考了下，感觉以上讨论的时机点不对，beforerequest是请求已经发出了，此时必须做出响应，而实际的需求是请求还未发出时就做判断处理，此时是可以不对发起请求的地方做任何的处理，也无需关注响应结果。这里的需求和单个请求内部做 middleware 中间件处理是一样的场景，在特定情况逻辑下，中间件不执行next请求，也就代表本次请求未发出。

所以是否可以增加全局中间件功能，优先级低于单次请求中间件，或者当接口和全局都存在中间件时，可以设置为：
1、全局不执行
2、全局优先执行
3、全局滞后执行

**Comment by Aaminly** [comment]
> @kenixFog 😁目前就是这样的，在beforerequest中抛出错误将会终止请求，并在请求处接收到错误，如果有initialdata也将保持这个数据
