### ISSUE TITLE
[post] 有时候上传文件，能否提供一个api是speed上传网速

### ISSUE THREAD

**Issue by wintsa123** [alovajs/alova#122]
### 你在什么情况下，需要这个功能解决什么问题？

有时候上传文件，能否提供一个api是speed上传网速

### 你期望的 API 是什么样子的？

`      const speed = event.loaded / (event.timeStamp / 1000); // 计算上传速度`

**Comment by JOU-amjs** [comment]
你可以看下这边的文档
https://alova.js.org/zh-CN/next-step/download-upload-progress

**Comment by wintsa123** [comment]
@JOU-amjs 牛的，之前没看到，另外想再说一个问题。，在api文档里面定义了post/get接口，正常axios直接调用await就好了，用alove需要用hook userequest(包裹着接口)。总感觉用起来没那么方便。。。

**Comment by wintsa123** [comment]
@JOU-amjs 另外想问一下`
  storageAdapter: sessionStorageAdapter ,

const sessionStorageAdapter = {
  set(key, value) {
    sessionStorage.setItem(key, JSON.stringify(value));
  },
  这个sessionStorage的set是什么时候如何触发的？
  get(key) {
    return sessionStorage.getItem(key);
  },
  remove(key) {
    sessionStorage.removeItem(key);
  }
};`

**Comment by wintsa123** [comment]
@JOU-amjs 还有个问题，为什么const {data} 的结果
![image](https://github.com/alovajs/alova/assets/47288630/70e5f26b-d05c-4c8e-bb08-42500761749f)
是这样的，而不是直接的一个json对象？我在拦截器那边设置了，好像只能设置onSuccess的

**Comment by wintsa123** [comment]
是因为data是个ref对象吗，那我想拿到json结果是要通过data._rawdata吗？有更加方便的方法吗。。。
我现在都是通过await send（）

**Comment by JOU-amjs** [comment]
> @JOU-amjs 另外想问一下` storageAdapter: sessionStorageAdapter ,
> 
> const sessionStorageAdapter = { set(key, value) { sessionStorage.setItem(key, JSON.stringify(value)); }, 这个sessionStorage的set是什么时候如何触发的？ get(key) { return sessionStorage.getItem(key); }, remove(key) { sessionStorage.removeItem(key); } };`

在持久化响应数据的时候就会调用它们保存，比如将响应数据设置为placeholder或restore模式的时候

**Comment by JOU-amjs** [comment]
> @JOU-amjs 牛的，之前没看到，另外想再说一个问题。，在api文档里面定义了post/get接口，正常axios直接调用await就好了，用alove需要用hook userequest(包裹着接口)。总感觉用起来没那么方便。。。

应该说更方便才对，你从userequest获得的值是响应式的，比如loadibg、data、error这些，也就是它们可以直接绑定到视图上使用，而且内部会自动帮你管理它们，而axios得到的是普通响应数据，你需要自行维护loading、data这些响应数据

**Comment by wintsa123** [comment]
data.value拿不到值

**Comment by wintsa123** [comment]
> restore

谢谢！我一开始以为这是个类似监听请求类似登录，自动设置长时间seesion的选项。这么看来，这似乎是一个为了等新数据/撤回时才自动化保存的设置

**Comment by JOU-amjs** [comment]
> ![image](https://user-images.githubusercontent.com/47288630/247978600-294f3386-0756-4e39-b96b-a8f35f215483.png) ![image](https://user-images.githubusercontent.com/47288630/247978780-42173b35-740f-4b84-b631-40556a5798e7.png) 无论data.data还是data.value都是 未定义数据。

看你的截图，data.value应该是有值的，正常情况下，data.value就是响应数据，你可以再检查下你的响应数据结构

**Comment by wintsa123** [comment]
![image](https://github.com/alovajs/alova/assets/47288630/8a68fbb9-b17e-4fb3-a24c-3b8c1bfe4c84)
![image](https://github.com/alovajs/alova/assets/47288630/148ba3b8-e87c-4b85-9e35-9cfa2907d960)
就是今天拿不到值。我才觉得奇怪哈哈，老哥你看这应该也没问题啊

**Comment by JOU-amjs** [comment]
你再截图看下打印data部分的代码片段

**Comment by JOU-amjs** [comment]
是需要看下你打印这部分的代码，我看下是不是代码错误导致的

**Comment by wintsa123** [comment]
但我仍然不知道怎么解决

**Comment by JOU-amjs** [comment]
代码问题在于，你在userequest下面紧跟着打印data.value，而请求数据是需要一定时间的，因此这个时候打印肯定是undefined，但在onsuccess中获取是可以正常的。
因为data就是一个ref值 此时可以直接绑定到界面上，如果需要转换数据，可以考虑中onsuccess中操作，或在method的不[transformdata函数中转换](https://alova.js.org/zh-CN/learning/transform-response-data)

**Comment by wintsa123** [comment]
但是我直接绑定在temple的元素上面，第一时间没有获取到值就直接报错了。。我应该用个三元表达式吗？这样的话一开始如果没值绑定的是普通字符串，还会有响应式的效果吗

**Comment by JOU-amjs** [comment]
userequest设置initialData就可以了，这些我们的官方文档里都有教程的哦

**Comment by wintsa123** [comment]
可以了，谢谢大佬。！
