### ISSUE TITLE
[Bug Report] 使用了 methods.abort();方法，但并没有中断执行

### ISSUE THREAD

**Issue by wintsa123** [alovajs/alova#123]
### Reproduction Link

now

### alova Version

new

### Describe the Bug

![image](https://github.com/alovajs/alova/assets/47288630/94b488c0-4877-45e2-b147-a0d802ee13b4)
![image](https://github.com/alovajs/alova/assets/47288630/b7c75ea3-f2b8-47f1-9ed1-42eb13d22422)
![image](https://github.com/alovajs/alova/assets/47288630/b789c358-c680-4315-a2b9-8a7263e2877e)
条件是true的，但是最后并没有中断执行

### Reproduce Steps

1

**Comment by JOU-amjs** [comment]
在beforerequest中中断功能需要在最新的2.6.2才支持，可能要按以下步骤检查一下
1. node_modules里的alova版本是否为最新的2.6.2
2. 在beforerequest中是否进入了if语句块内成功执行了abort

**Comment by wintsa123** [comment]
> 在beforerequest中中断功能需要在最新的2.6.2才支持，可能要按以下步骤检查一下
> 
> 1. node_modules里的alova版本是否为最新的2.6.2
> 2. 在beforerequest中是否进入了if语句块内成功执行了abort

突然发现我是2.6.1

**Comment by wintsa123** [comment]
> 在beforerequest中中断功能需要在最新的2.6.2才支持，可能要按以下步骤检查一下
> 
> 1. node_modules里的alova版本是否为最新的2.6.2
> 2. 在beforerequest中是否进入了if语句块内成功执行了abort
更新后可以了，谢谢大佬。如果有别的前端问题可以问大佬吗。
