### ISSUE TITLE
[question] 关于updateState应该如何使用？

### ISSUE THREAD

**Issue by wintsa123** [alovajs/alova#124]
### 你在什么情况下，需要这个功能解决什么问题？

这是getlist的函数![](https://github.com/alovajs/alova/assets/47288630/6446a6f5-8b1c-4bd3-bf96-7fa6fc6a8317)，最后的结果需要筛选后再渲染出来
我的用法是隔壁的组件upload上传的时候，调用updateState 再触发getlist重新更新渲染

我的想法是如果再第一次的userequest请求时是否也有类似updateState 的方式能修改缓存数据。我看文档看到了transformData，但是这个似乎只能写在实例里面，我有很多场景用到同一个实例，transformData响应数据的筛选并不一致。能否再userequest里面方便修改？
![image](https://github.com/alovajs/alova/assets/47288630/bb3ffabd-b047-4c4b-8bbf-b84843b1846f)

### 你期望的 API 是什么样子的？

快捷的

**Comment by wintsa123** [comment]
@JOU-amjs 
`
<t-card bordered class="basis-1/5 m-8" v-for="(item, index) in listData" ：key=“index”
>
const { send, data: listData, onSuccess } = useRequest(() => fetchQiniuDataList()}`
如果我在v-for引用了data这个响应式对象，但我输出渲染需要筛选这个data对象的某些条件才能输出。我的写法是通过watch来监听这个data的变化再

**Comment by JOU-amjs** [comment]
@wintsa123 关于第一个问题，你可以通过函数参数来控制transformData应该返回什么数据，如果需要在userequest层面转换数据的话，可以使用计算属性转换data或在onsuccess中转换赋值给自定义的ref值。

关于第二个问题，可以监听data变化，也可以通过计算属性转换data
