### ISSUE TITLE
[Feature Request] 重试功能时, 需要支持修改请求参数

### ISSUE THREAD

**Issue by vaynevayne** [alovajs/alova#126]
### 你在什么情况下，需要这个功能解决什么问题？

[useRetriableRequest](https://alova.js.org/zh-CN/tutorial/strategy/useRetriableRequest)

无脑重试(次数)的功能, 真的有人在用吗?
无论多么优秀的重试算法, 都只是鸡肋

在大多数业务中, 一般请求失败了, 是需要修改为其他请求参数继续发起请求的

以上只是个人的开发经验总结

### 你期望的 API 是什么样子的？

就这么简单啊
```jsx
onRetry:(prevRequest,prevResponse,retry)=> {
if(prevResponse.code !== 0){

retry({
headers:prevRequest.headers, // 可选,两者都不填,那就是单纯的加次数重试
body: prevRequest.body + 1, // 可选,两者都不填,那就是单纯的加次数重试

})
}

}
```

**Comment by JOU-amjs** [comment]
@vaynevayne 请求重试hook是可以允许你控制何时需要重试，除了指定最大重试次数外，你也可以在[retry函数](https://alova.js.org/zh-CN/strategy/useRetriableRequest/#%E5%8A%A8%E6%80%81%E8%AE%BE%E7%BD%AE%E6%9C%80%E5%A4%A7%E9%87%8D%E8%AF%95%E6%AC%A1%E6%95%B0)中动态判断何时需要重试，也可以手动停止它。

目前请求重试的设计场景是基于重要请求对网络波动下的稳定性保证，以及某些需要轮询请求的场景。你期望的API形式是一种不错的设计，可否一同探讨下，一般在什么场景下需要调整参数进行重试？

**Comment by vaynevayne** [comment]
总之, retry 次数很鸡肋

**Comment by kenixFog** [comment]
我也比较好奇，哪些场景下需要调整参数，或者需要调整哪些参数？不过个人感觉，重试的定义，就是重复尝试，重复就是保持不变。如果是问题当中描述的，感觉应该重新起一个名字。如果重试可以支持修改一些参数，比如url，header，params，data，那本次请求成功，到底是第一次直接成功，还是修改参数后"重试"成功？并且参数都修改了，那么就意味着，请求结果的不确定性，这感觉放到重试的逻辑里，怕是不合理。

**Comment by JOU-amjs** [comment]
@vaynevayne 我们在做功能设计时，首先会考虑需要满足什么场景的需求，并将这些场景进行更高层级的抽象和提炼，以达到更简单的设计。

**Comment by JOU-amjs** [comment]
@kenixFog 🤞🤞🤞
