### ISSUE TITLE
[Bug Report] 'import.meta' is currently unsupported, js engine: hermes in REACT NATIVE

### ISSUE THREAD

**Issue by Sofrosine** [alovajs/alova#128]
### Reproduction Link

https://github.com/facebook/react-native

### alova Version

2.6.1

### Describe the Bug

Hi, i got the this error message
`'import.meta' is currently unsupported, js engine: hermes`

And i need to comment the code from `alova.esm.js` file like exactly below

![Screenshot 2023-06-25 at 13 34 03](https://github.com/alovajs/alova/assets/54109543/8921ee00-4b01-42d1-980c-9ef88bd33488)

And then, it works fine
Any alternative ways to solve this problem?

Thanks

### Reproduce Steps

I use this react-native package

`
 "react-native": "0.72.0",
    "alova": "^2.6.1",
   "react": "18.2.0",
`

### Device / Browser / Browser Version

Android

**Comment by JOU-amjs** [comment]
Thanks for your issue.
I removed `import.env`, and now it can work well.

please upgrade to v2.7.1

**Comment by Sofrosine** [comment]
Thanks!
