### ISSUE TITLE
[Feature Request] 文档中增加版本更新日志

### ISSUE THREAD

**Issue by ZombieBrand** [alovajs/alova#130]
文档中增加版本更新日志

**Comment by JOU-amjs** [comment]
@ZombieBrand 目前文档内还缺少这部分内容，不过你可以在[github的releases中](https://github.com/alovajs/alova/releases)查看这些

**Comment by JOU-amjs** [comment]
@ZombieBrand 现在，你可以在[官网](https://alova.js.org/)中看到发布日志链接了。这真的是个好建议。💕💕💕
