### ISSUE TITLE
如何动态判断是否需要强制请求

### ISSUE THREAD

**Issue by wintsa123** [alovajs/alova#131]
### 重现链接

。

### alova 版本

1.3.7

### 描述一下你遇到的问题。

组件A
```javascript
const { send, data: listData, onSuccess } = useRequest(() => fetchQiniuDataList(), {
  initialData: {
    
    
  },
  middleware: actionDelegationMiddleware('getHomephohto')
})
```

组件B
```javascript
const handleRequestSuccess=async(e)=>{
await SyncDate(prefix,Number(1))
await accessAction('getHomephohto', async({send}) => {
  // 调用组件A中的send函数
  await send();
});
```
在网络看到SyncDate发起了，但看不到fetchQiniuDataList的发起。控制台也没报错。。。

### 重现步骤

想上传结束后触发list的变化

**Comment by JOU-amjs** [comment]
@wintsa123 1.3.7版本还不支持`middleware`功能，你可以按以下方式检查问题。
1. 更新到最新的alova版本
2. 检查`fetchQiniuDataList`这个请求是否有设置本地缓存（get请求默认有5分钟缓存时间）

**Comment by wintsa123** [comment]
> @wintsa123 1.3.7版本还不支持`middleware`功能，你可以按以下方式检查问题。
> 
> 1. 更新到最新的alova版本
> 2. 检查`fetchQiniuDataList`这个请求是否有设置本地缓存（get请求默认有5分钟缓存时间）

1. alova是2.6.2版本
2. fetchQiniuDataList是get请求确实有缓存，有缓存就不能触发第二次请求吗。如果我有的情况是后端的上传完立刻，后端的列表立刻发起请求刷新。但我前端同一个接口要求是有缓存不用刷新这么频繁，这种情况只能写两个实例吗

**Comment by JOU-amjs** [comment]
不需要的，原因是你重新发起请求时命中了缓存，因此不会发送出请求导致。如果你需要在强制请求，可以使用force动态返回true实现，具体如下：

```javascript
// 组件A
const { send, data: listData, onSuccess } = useRequest(() => fetchQiniuDataList(), {
initialData: {

},
// 设置force为函数，并接收send函数传入的参数
force: isForce => isForce
middleware: actionDelegationMiddleware('getHomephohto')
})

// 组件B
const handleRequestSuccess=async(e)=>{
await SyncDate(prefix,Number(1))
await accessAction('getHomephohto', async({send}) => {
// 在send函数中传入true给force函数接收
await send(true);
});

```
[文档在这边](https://alova.js.org/zh-CN/learning/use-request#%E5%8A%A8%E6%80%81%E8%AE%BE%E7%BD%AE-force-%E5%80%BC)

**Comment by wintsa123** [comment]
good!

**Comment by wintsa123** [comment]
@JOU-amjs
