### ISSUE TITLE
[Bug Report] 隐藏推荐提示

### ISSUE THREAD

**Issue by jiangkaifree** [alovajs/alova#135]
### 重现链接

https://stackblitz.com/edit/vitejs-vite-crstma?file=src%2FApp.tsx

### alova 版本

2.7

### 描述一下你遇到的问题。

dev下 结合[文档-隐藏提示](https://alova.js.org/zh-CN/others/hide-recommend-tips)，配置环境变量并不能去除控制台的提示输出

### 重现步骤

1. 打开控制台， alova的输出信息并没有消失

**Comment by jiangkaifree** [comment]
查看了一下代码 发现在这个 `src/index.tx` 下 只判断了 `process.env.NODE_ENV` 并未有获取 `env` 代码，我正在尝试解决

**Comment by JOU-amjs** [comment]
@jiangkaifree 感谢你的反馈哦！
由于在不同环境下经常会报`import.env`不存在的问题，在v2.7.1中已经取消了通过环境变量关闭控制台提示的功能了，这个在文档中已经体现。不过在生产环境会自动隐藏这部分代码。
![image](https://github.com/alovajs/alova/assets/29848971/bf8cc7de-8613-4b60-bfad-9ddff2fef7cf)

**Comment by kkfive** [comment]
所以现在在开发环境无法隐藏是嘛？
