### ISSUE TITLE
[Bug Report] File upload using xhrRequestAdapter() doesn't handle multipart form data

### ISSUE THREAD

**Issue by proddy** [alovajs/alova#138]
### Reproduction Link

https://codesandbox.io/p/sandbox/alova-test-upload-w46x26?file=%2Fsrc%2Fapi.ts%3A9%2C22-9%2C41

### alova Version

2.8.0

### Describe the Bug

Using the `xhrRequestAdapter()` to upload a file, via FormData, as shown in the example on https://alova.js.org/extension/alova-adapter-xhr#upload sets the Request Headers `Content-Type` to `application/json; charset=UTF-8` instead of multipart/form-data which means my server cannot process the uploaded file.

I tested with the `axiosRequestAdapter()` and it correctly adds the `multipart/form-data; boundary=----` Content Type including the boundary.

But I don't want to use Axios!

Is this by design?

(Note this is also related to a discussion I added earlier https://github.com/alovajs/alova/discussions/132)

### Reproduce Steps

Using the example code from the [documentation](https://alova.js.org/extension/alova-adapter-xhr#upload), upload a file and look at the request headers. Or use the codesandbox.io example.

**Comment by JOU-amjs** [comment]
Thanks for your issue.❤️
i will reproduce this bug by your demo, and try to resolve it as soon as possible.

**Comment by JOU-amjs** [comment]
@proddy Now it is fixed. please upgrade `@alova/adapter-xhr` to v1.0,1.

**Comment by proddy** [comment]
Confirmed it's fixed and works beautifully. Thanks for the quick fix!

**Comment by JOU-amjs** [comment]
You happy I happy.😁

**Comment by proddy** [comment]
another probably issue I found is that during a file upload, calling the method's abort() doesn't cancel the upload, as it does in axios. Shall I open a new issue for this @JOU-amjs ?

**Comment by JOU-amjs** [comment]
@proddy I will try to reproduce it later. If it cannot be reproduced, I will tell you to open a new issue

**Comment by JOU-amjs** [comment]
@proddy I didn't find this problem. [codesandbox link](https://codesandbox.io/p/sandbox/alova-test-upload-forked-4srgx3?file=%2Fpackage.json%3A13%2C34) is here.

you can check follow steps below.
1. is alova's version v2.6.2+
2. is the method that to be aborted same reference as the method that send request
3. is the request currently in progress when aborting the request
4. has `method.abort` been called

if still has problem, you can open a new issue and reproduce it base on my codesandbox link.

**Comment by proddy** [comment]
Thanks for responding, and very cool of you to create a codesandbox for this. What I'm trying to do give the user the ability to cancel an upload by clicking on a 'cancel' button. With axios I was using `AbortController()` and with my port to Alova now trying to find something similar. I first thought of using the `abort` function in the useRequest as per the example in https://alova.js.org/learning/use-request/#abort-request-manually but this didn't seem to work and I don't want to add it to the createAlova instance via `method.abort` is this is specific to one use case.

I'm not sure it's a bug - shall I create an issue, create a discussion or leave it here?

https://codesandbox.io/p/sandbox/alova-test-upload-w46x26

thanks again for this great library!

**Comment by JOU-amjs** [comment]
@proddy 😂I think you can leave here to open a new issue.
I will check it later.
