### ISSUE TITLE
[q] 缓存key在不同组件会是相同吗

### ISSUE THREAD

**Issue by wintsa123** [alovajs/alova#139]
### 重现链接

not

### alova 版本

1.7

### 描述一下你遇到的问题。

- 缓存 key 自动维护

响应数据缓存的 key 是由 method 实例的请求方法(method)、请求地址(url)、请求头参数(headers)、url 参数(params)、请求体参数(requestBody)组合作为唯一标识，任意一个信息或位置不同都将被当做不同的 key。

任意一个信息或位置不同都将被当做不同的 key。我想问，如果不同组件或者不同vue文件，key也是不同吗，这个位置不同是指某些params，headers位置不同，还是请求所在的组件位置不同。比如说我现在想请求拿到一个type的data，我在后台有几个不同的组件用到同样的一个get请求，其中参数都一样，正常来说我会使用pinia或者vuex状态管理来减少重复的发起请求。。。
但如果你的get请求内存模式能够实现这个效果的话，我就能剩下不少麻烦

### 重现步骤

多个temple使用同一个get请求

**Comment by JOU-amjs** [comment]
是的，这个确实可以省下你不少麻烦。
请求缓存是根据请求参数作为key的，和组件无关。

**Comment by zhaoyunyes** [comment]
可以自定义key的生成策略吗？
有这样一种情况，在相近时间内，每个请求都会有不同的签名和时间戳，其他参数都一样，但是最终会导致key不一样，从而不能共享请求了。
