### ISSUE TITLE
[Bug Report] 官方文档文案错误。

### ISSUE THREAD

**Issue by LinSky** [alovajs/alova#14]
### 重现链接

https://alova.js.org/zh-CN/overview/installation/

### alova 版本

1.4.0

### 描述一下你遇到的问题。

概览》安装/使用》引入 fetch adapter 中有一文案错误：
“你可以通过window.GlobalFetch使用，它将使用`winfow.fetch`进行请求。” 中的`winfow.fetch`中单词window拼写错误

### 重现步骤

1. 打开链接 https://alova.js.org/zh-CN/overview/installation/
2. 找到 “引入 fetch adapter ”章节

**Comment by LinSky** [comment]
找错地方了，抱歉已经提交到这儿：https://github.com/alovajs/alovajs.github.io/issues/2

**Comment by JOU-amjs** [comment]
仔细入微啊，我去那边处理一下
