### ISSUE TITLE
how to manually cancel an upload using abort

### ISSUE THREAD

**Issue by proddy** [alovajs/alova#141]
Continuation from https://github.com/alovajs/alova/issues/138#issuecomment-1615837125

What I'm trying to do give the user the ability to cancel an upload by clicking on a 'cancel' button. With axios I was using `AbortController()` and with my port to Alova now trying to find something similar. I first thought of using the `abort` function in the useRequest as per the example in https://alova.js.org/learning/use-request/#abort-request-manually but this didn't seem to work and I don't want to add it to the createAlova instance via `method.abort` is this is specific to one use case.

I'm not sure it's a bug - shall I create an issue, create a discussion or leave it here?

https://codesandbox.io/p/sandbox/alova-test-upload-w46x26

thanks again for this great library!

**Comment by proddy** [comment]
Thanks! I'll check....

**Comment by JOU-amjs** [comment]
OK. fixed it just now.
upgrade to v2.9.0 to check it.

**Comment by proddy** [comment]
just did, works great. A thousand thanks....!

**Comment by JOU-amjs** [comment]
and now. v2.9.0, In react, the send and abort functions are wrapped with `useCallback`, and they are not limited by the closure trap. You can use it directly in the event without worrying about performance problems.

**Comment by proddy** [comment]
I've been testing and found that the first Cancel works but any other abort calls are ignored.

You can reproduce at the codesandbox https://codesandbox.io/p/sandbox/alova-test-upload-w46x26

Upload a file, hit cancel, it aborts nicely. Now try and upload again and hit cancel and it doesn't work.

**Comment by JOU-amjs** [comment]
@proddy 😂I overlooked something, let me think of a way first.

**Comment by JOU-amjs** [comment]
@proddy Now it is fixed. I promise.😂

**Comment by proddy** [comment]
great, I'll check now.

**Comment by proddy** [comment]
> great, I'll check now.

works! 🎉
