### ISSUE TITLE
[Q] 想问一下，这种情况一般是用哪种方案？

### ISSUE THREAD

**Issue by wintsa123** [alovajs/alova#142]
### 重现链接

not

### alova 版本

1.7.1

### 描述一下你遇到的问题。

我看到alova提供的hooks，有点疑问。。。
在一个标签选择框，先是getlist请求，然后被增加的时候，触发一个creat的请求。
这时候我应该是使用accessAction，让getlist请求重新发起拿到数据，还是说直接用updateState的hook在缓存数组添加一个数据？
想知道哪种更合适。

### 重现步骤

1

**Comment by JOU-amjs** [comment]
看来你已经比较深度地使用alova啦，恭喜🎉
这个问题的话，两种其实都可以，主要取决于你自己的取舍
如果，你觉得服务端可靠，不想再请求一次，或想立即展示添加后的结果，你可以直接使用`updateState`，反之，则使用`accessAction`重新获取会更好，但要注意的是，重新获取时要保证不能命中缓存，比如强制请求或让缓存失效，或直接关闭缓存。

**Comment by wintsa123** [comment]
> 看来你已经比较深度地使用alova啦，恭喜🎉 这个问题的话，两种其实都可以，主要取决于你自己的取舍 如果，你觉得服务端可靠，不想再请求一次，或想立即展示添加后的结果，你可以直接使用`updateState`，反之，则使用`accessAction`重新获取会更好，但要注意的是，重新获取时要保证不能命中缓存，比如强制请求或让缓存失效，或直接关闭缓存。

updateState能跨组件吗？另外就是为什么我这个updateState打印不出来QAQ
`vue
const { send: gettag, data: allTag } = useRequest(() => taglist(), {
    initialData: [{data:{
    "rows":{
      "label": "",
      "value": "",
    }}}],
    force: isForce => { return !!isForce },
    middleware: actionDelegationMiddleware('getTagList')
})

const createOptions = async (val) => {
    // options.value.push({
    //     label: `选项${val}`,
    //     value: val,
    // });
    await creatrtag(val, 'green')
    await updateState(gettag(), oldListData => {
     console.log(oldListData)
      return oldListData;
    });
    // await accessAction('getTagList', async ({ send }) => {
    //     // 调用组件A中的send函数
    //     await send('getTag');
    // });
    console.log('create option:', formData.tag);
};
`

**Comment by wintsa123** [comment]
console.log(oldListData)
这一句，没有执行

**Comment by JOU-amjs** [comment]
`updateState`函数使用错误，第一个参数是需要传入一个method实例，比如你这边是`taglist()`，更详细的可以看下官网文档

**Comment by wintsa123** [comment]
> `updateState`函数使用错误，第一个参数是需要传入一个method实例，比如你这边是`taglist()`，更详细的可以看下官网文档

可以了，但有个问题，每次vscode报错后需要浏览器刷新一次才可以，不然这个updateState的回调console.log()不出数据
