### ISSUE TITLE
[Bug Report] 多文件串行上传不行

### ISSUE THREAD

**Issue by wintsa123** [alovajs/alova#148]
### 重现链接

not

### alova 版本

1.8.2

### 描述一下你遇到的问题。

![image](https://github.com/alovajs/alova/assets/47288630/cf259455-df9a-4a58-a98f-af71992584fc)
![image](https://github.com/alovajs/alova/assets/47288630/3ebf5bee-41ab-46d1-b654-da4c3d0a6623)
直接贴打印把，form表单确实是两个不同的，但我把这个post请求丢到promiseall里面，打印的数据变成了同一个，我不知道这是为什么。。。。

### 重现步骤

多文件上传

**Comment by JOU-amjs** [comment]
因为请求共享的缘故，两个相同的请求同时发出时，不会发起两个请求，你可以在上传部分关闭它。详见 https://alova.js.org/zh-CN/next-step/share-request

**Comment by wintsa123** [comment]
> 因为请求共享的缘故，两个相同的请求同时发出时，不会发起两个请求，你可以在上传部分关闭它。详见 https://alova.js.org/zh-CN/next-step/share-request

解决了，作者真厉害啊，一看就知道问题出现在哪。我昨晚检查这段代码，检查了半天

**Comment by JOU-amjs** [comment]
自己设计的东西不懂才怪😂

**Comment by wintsa123** [comment]
> 自己设计的东西不懂才怪😂

那想问一下axiosRequestAdapter和GlobalFetch这两个适配器有什么区别吗，还有就是能用在nuxt上吗

**Comment by JOU-amjs** [comment]
@wintsa123 前者是用axios封装的，后者是fetch封装的
