### ISSUE TITLE
[Feature Request] 提供一种公共状态管理的数据获取方式

### ISSUE THREAD

**Issue by luqiudi** [alovajs/alova#15]
### In what situation do you need this function to solve the problem?

想问下，那用这个alova，公共状态管理咋办呢，每个想公共状态管理的都对data加个watch么？有没有更优雅的方式呢呀

### What do you expect the API to look like?

提供一种公共状态管理的数据获取方式

**Comment by luqiudi** [comment]
> 没有很明白你的意思，按你的想法好像是在说vue2，但我不确定，你可以再详细说明下吗，也可以举个例子

我说的是vue3 呀
无论是vue2 还是vue3,都涉及到跨页面,跨组件的状态管理问题,比如说我在a页面 请求了一个数据,但是b页面不想再请求了,想要直接用a页面请求回来的数据,那就会用到公共状态管理呀.
会有pinia这一类的公共状态管理组件,那你这个alova 怎么和这一类的公共状态管理组件结合呢.
https://pinia.web3doc.top

**Comment by JOU-amjs** [comment]
我的观点是，其实没有必要结合，让它们各司其职就可以了
因为pinia和alova是用来解决不同问题的。
1. pinia解决组件中公共状态的管理问题，这些公共状态可以和请求相关的，也可以是不相关的；
2. alova解决请求，以及请求相关的数据和对应的状态问题；

对于你提的a、b页面共用数据的例子，pinia和alova两者都可以解决，只是看使用工具的人的解决思路了，我分别举个例子来看看这两者是怎么解决共用数据的问题的：
**pinia**：在store中写一个action，这个action实现判断公共数据A是否有值，没有值则发起请求并将响应数据放回A，然后在a页面和b页面中分别触发这个action，就达到你想要的效果了。
**alova**：将这个请求设置为可缓存的，在a页面发起请求，此时未命中缓存，将会发送请求获取数据并自动缓存起来，然后在b页面同样发起请求，此时会命中缓存，就不再发送请求了。

两者都能解决你的问题，但思路不同，看你取舍了。
