### ISSUE TITLE
[Bug Report] uniapp 微信小程序环境useRequest没有调用

### ISSUE THREAD

**Issue by yang1206** [alovajs/alova#150]
### 重现链接

https://github.com/yang1206/uniapp-template

### alova 版本

2.9.1

### 描述一下你遇到的问题。

uniapp 微信小程序环境使用useRequest hook，没有发起请求，h5正常，尝试降级到 2.7.0，发现 2.7 没问题

### 重现步骤

跳转 count页面

### 设备/浏览器/浏览器版本

微信开发者工具

**Comment by jinyaqiao1102** [comment]
卧槽，我这问题找了两天不知道为啥

**Comment by jinyaqiao1102** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by JOU-amjs** [comment]
@yang1206 @jinyaqiao1102 目前已修复，请升级到v2.9.2
