### ISSUE TITLE
[Bug Report] Error when reload in usePagination

### ISSUE THREAD

**Issue by codenesiareborn** [alovajs/alova#152]
### Reproduction Link

https://alova.js.org/strategy/usePagination

### alova Version

2.9.2

### Describe the Bug

Error when trigger reload event in usePagination
<img width="305" alt="Screenshot 2023-07-12 at 5 44 49 PM" src="https://github.com/alovajs/alova/assets/70792066/47eb332a-255e-4abd-8f39-7e388240bc75">

### Reproduce Steps

`const {data, send, loading, 
    isLastPage,
    reload,
    page: [page, setPage],
    pageCount,
    total
    } = useGetPickupRequests({
    filter: {
      status: tabSelected,
    },
  });`

**Comment by JOU-amjs** [comment]
@codenesiareborn are you developing a RN App? if so, you need to custom a storageAdapter, because there has no `localStorage` in RN which is default storageAdapter in alova.

[for more detail about custom storageAdapter](https://alova.js.org/advanced/custom-storage-adapter/)
