### ISSUE TITLE
[Bug Report] formDatas表单数据重置

### ISSUE THREAD

**Issue by wintsa123** [alovajs/alova#153]
### Reproduction Link

not

### alova Version

1.9.1

### Describe the Bug

```js
father:
<div v-if=" typeof data =='object'">
    <edit :data="data.data.rows[0]" />
  </div>
const { send: getid, onSuccess ,data} = useRequest(() => ArticleType({ typename: '关于我们' }))
```
```js
son:
const formData = reactive({
    title: props.data && props.data.title || '',
    desc: props.data && props.data.desc || '',
    content: props.data && props.data.content ? props.data.content : '# 在这任意编辑哦，创意由你定',
    tags: props.data && props.data.tags.map(e=>{return e.id}),
    imgurl: props.data && props.data.head_img || '',
    is_comment: props.data && props.data.is_comment || 1,
    status: props.data && props.data.status || 1,
    types: props.data && props.data.types.map(e=>{return e.id}),
    priority: props.data && props.data.priority || 0
});

  updateState(ArticleType({ typename: props.data.types[0].name }),(e)=>{
                    e.data.rows[0].content=formData.content
                     e.data.rows[0].desc=formData.desc
                   e.data.rows[0].tags=formData.tags
                    e.data.rows[0].priority=formData.priority
                    e.data.rows[0].head_img=formData.head_img
                     return e
                 })
                 invalidateCache(ArticleType({ typename: props.data.types[0].name }))
                fetch(ArticleType({ typename: props.data.types[0].name }));
                
```
我尝试在保存时用三种方法更新父组件的这个请求数据，都是成功了。但是问题在于表单重置时用的是第一次父组件传的的props.data,而不是保存后第二次发起拿到的props.data。
（父组件在发起第二次请求后，子组件的props.data并没有拿到）

### Reproduce Steps

进入一个文章的修改页面，我修改保存后，使用重置功能，我希望这时候重置的值是修改保存后的，而不是初始的

**Comment by wintsa123** [comment]
想传个demo的，但我这边没有服务器做后端，用的还是本地的

**Comment by wintsa123** [comment]
@JOU-amjs 按道理来说，data是个响应式对象，我触发了他的第二次请求，data改变了不应该重新渲染子组件吗，但是我通过打印子组件props.data看到还是第一次请求的数据

**Comment by JOU-amjs** [comment]
@wintsa123 按我的理解，你是希望在表单项修改提交后，再次进入编辑页时回显的是修改后的内容。
如果是这样的话，按我对你给出的示例代码，我感觉是有问题的，可能是以下情况：

如果你的编辑组件是持久化的（很多UI组件库都会做成默认持久化的），`formData`的值是在创建组件时构造的，那么第二次进入编辑组件是不会再次重新构造`formData`了，所以它的值就保留为了上次的内容，你可能需要watch一下`props.data`来更新`formData`数据，或者改为在关闭时销毁组件。

如果不是上面这种情况，我可能需要更完整点的重现代码

✨另外，表单处理可以推荐你使用[表单提交策略](https://alova.js.org/zh-CN/strategy/useForm)，可以更好地帮你管理表单提交功能

**Comment by wintsa123** [comment]
> @wintsa123 按我的理解，你是希望在表单项修改提交后，再次进入编辑页时回显的是修改后的内容。 如果是这样的话，按我对你给出的示例代码，我感觉是有问题的，可能是以下情况：
> 
> 如果你的编辑组件是持久化的（很多UI组件库都会做成默认持久化的），`formData`的值是在创建组件时构造的，那么第二次进入编辑组件是不会再次重新构造`formData`了，所以它的值就保留为了上次的内容，你可能需要watch一下`props.data`来更新`formData`数据，或者改为在关闭时销毁组件。
> 
> 如果不是上面这种情况，我可能需要更完整点的重现代码
> 
> ✨另外，表单处理可以推荐你使用[表单提交策略](https://alova.js.org/zh-CN/strategy/useForm)，可以更好地帮你管理表单提交功能

谢谢作者回复，这个问题已经解决了，就是因为异步数据传组件里面，我一开始是使用watch监听改变formdata，但是组件只认初始化的formdata。后来改用if判断渲染来初始化解决了，看了作者的方法我发现还有销毁组件的方法。另外我是想过使用[表单提交策略](https://alova.js.org/zh-CN/strategy/useForm)功能的，ui组件自带重置的hook，而我的需求也简单，就是单页面表单提交，所以使用[表单提交策略](https://alova.js.org/zh-CN/strategy/useForm)也不会更优
