### ISSUE TITLE
[Bug Report] updateState在router.push后不生效

### ISSUE THREAD

**Issue by wintsa123** [alovajs/alova#154]
### Reproduction Link

not

### alova Version

1.9.1

### Describe the Bug

在todo，使用router.push打开编辑器组件后，新建后
```js
      if (result.code == 200) {
        MessagePlugin.success(result.message);
        updateState(
          ArticleType({ typename: '产品中心' }),
          (e) => {
            console.log(e)
            return e;
          }
        );
        router.go(-1);
      } else {
        MessagePlugin.warning(result.message);
      }
```
updateState并没有生效，视乎并没有找到 ArticleType({ typename: '产品中心' }),我在todo是这样定义这个方法的，不知道有没有影响。
```js
const { send: getList, onSuccess: getListSuccess, data } = useRequest(() => ArticleType({ typename: '产品中心' }))
```
相反，如果我是直接组件嵌入后去直接使用updateState，相同写法，他可以工作

### Reproduce Steps

1

**Comment by wintsa123** [comment]
```js
invalidateCache(ArticleType({ typename: '产品中心' }))
```
是生效的，但我希望可以使用updateState这个hook，因为这个hook我可以省去第二次发起请求避免波动

**Comment by JOU-amjs** [comment]
@wintsa123 你的使用没有问题，问题出现在，
当你跳转到编辑页时，列表页已被销毁，它内部的状态也将会被销毁，此时调用`updateState`是找不到列表页状态的，因此自然也不会更新。

以下有两个解决方案：
1. 将列表页使用`<keep-alive>`持久化
2. 使用`setCache`替代`updateState`，这样在返回到列表页并重新发起请求时将会命中更新后的缓存，能达到同样的效果。

**Comment by wintsa123** [comment]
@

**Comment by wintsa123** [comment]
@JOU-amjs 尝试了<keep-alive>持久化，仍然不生效，updateState打印不出数据

**Comment by JOU-amjs** [comment]
@wintsa123 你可以参照[这个示例](https://alova.js.org/zh-CN/tutorial/example/update-state)，再检查下代码
