### ISSUE TITLE
[Feature Request] 新增refresh，使用上一次的 params，重新调用 send

### ISSUE THREAD

**Issue by vanness30214** [alovajs/alova#155]
### 你在什么情况下，需要这个功能解决什么问题？

https://ahooks.js.org/zh-CN/hooks/use-request/basic#result

参考ahooks 

很多时候传参会随场景改变而改变，为了简化send重复请求，不用特意记录上一次传参， 进行重新请求上一个参数的请求

### 你期望的 API 是什么样子的？

 const { loading, data, error，refresh } = useRequest(
    alovaInstance.Get('https://api.alovajs.org/profile', {
      params: {
        id: 1
      }
    })
  );

**Comment by JOU-amjs** [comment]
@vanness30214 按你的描述，我的理解是你希望每次调用`refresh`时使用最新的参数进行调用，而不再需要自行在调用`send`时传递，如果是这样的话，你可以按下面的方式做，也可以达到你希望的效果：

```javascript
let a = 1;
const [stateA, setStateA] = useState('a');

// 将useRequest的handler设置为一个函数，它将在每次请求时触发，此时内部将访问到外部最新的数据，例如这边的变量a和stateA
const { loading, data, send } = useRequest(
  () => alovaInstance.Get('https://api.alovajs.org/profile', {
  params: {
      a,
      b: stateA
    }
  })
);

const handleRequest = () => {
  send();
}
```

通过函数调用的延迟性，同样可以达到你希望的效果。
