### ISSUE TITLE
📢If your project uses alova, please tell us.

### ISSUE THREAD

**Issue by JOU-amjs** [alovajs/alova#165]
We believe that using alova in projects is also a contributor of alova, which is telling people that alova is a trustworthy open source project.🥳🥳🥳

if your project uses alova, please tell us in this issues, your project will have the opportunity to be showcased on alova's official website.

**post your project in the following format:**

- [your project name]
- [your project logo]
- [your project online link]

**Comment by wintsa123** [comment]
hh，我的个人项目太水了

**Comment by chansee97** [comment]
- nova -admin
- <img src="https://s2.loli.net/2023/10/27/WzQ4JLNV5epKh6X.png" width="100"/>
- [Nova-admin preview](https://nova-admin.pages.dev/)

>  [Nova-admin](https://github.com/chansee97/nova-admin) is a clean and concise back-end management template based on Vue3, Vite5, Typescript, and Naive UI. It implements complete functionality in a simple way, while also considering code standards, readability, and avoiding excessive encapsulation to facilitate secondary development.

> [Nova-admin](https://github.com/chansee97/nova-admin)是一个基于Vue3、Vite5、Typescript、Naive UI, 简洁干净后台管理模板，用简单的方式实现完整功能，并尽可能的考虑代码规范，易读易理解无过度封装，方便二次开发。

**Comment by 3m1n3nc3** [comment]
- 5Minutes
- ![image](https://github.com/user-attachments/assets/4237e1cf-6cc2-496f-896a-232ea96ddf3e)
- 5minutes is a mentor-mentee learning platform where mentors share content that is consumable in no more than 5minutes. 5minutes is a robust state-of-the-art Ed-Tech solution for learning and continuous learning for training organizations. Corporate institutions use 5minutes as their preferred platform to upskill their workforce on the go.

**Comment by JOU-amjs** [comment]
@chansee97 @3m1n3nc3 already added to [showcase](http://localhost:3000/showcase)

**Comment by southwind957** [comment]
- uni-vt
- [](https://raw.githubusercontent.com/southwind957/uni-vt/master/image/logo.png)
- uni-vt是一个基于uniapp+vite5+ts+vue3开发的uniapp快速启动模板。包含（alova、pinia、地图、scss、unocss等）。无需hbuilder x，不管你使用何种工具都可以快速启动。

**Comment by jackhb1999** [comment]
* vcvr

* 
<img width="64" height="64" alt="Image" src="https://github.com/user-attachments/assets/4d20bda1-69e7-4431-97f9-6d8cdb0cb2a6" />

* [vcvr](https://github.com/jackhb1999/vcvr) 是使用 tauri 开发的桌面应用，前端使用 vite + vue +ts + deno + alova + unocss 等技术，方便裁剪，方便改造为 web 项目 / 全栈项目。
