### ISSUE TITLE
无感获取token

### ISSUE THREAD

**Issue by wintsa123** [alovajs/alova#166]
### 需要新特性解决什么问题？

希望添加个hook,可以根据time定时发起请求，因为我现在是登录/获取token之类的都有时效，在一段时间后在某个步骤会提示失败再重新自动获取。我希望可以无感获取token(定时自动发起请求)

### 它对你有多重要？

有就更好了

**Comment by JOU-amjs** [comment]
这个需求个人觉得不具有普适性，不太适合放在通用库里，建议通过useRequest自行封装一个请求策略解决，封装教程可以[查看这边](https://alova.js.org/zh-CN/tutorial/advanced/overview)
