### ISSUE TITLE
自动获取的data能否做成同步的

### ISSUE THREAD

**Issue by wintsa123** [alovajs/alova#178]
### 需要新特性解决什么问题？

```js
const { data } = useRequest(() => getSystemInfo())
_.chunk(data,4)
```
因为这是个异步请求，直接这么写，_chunk会拿不到值，需要用send/onsuccess/watch(data)才可以，但这样写，要给函数外作用域的响应式对象赋值，我又感觉有点麻烦，好像不比axios省事。。。

### 它对你有多重要？

可以让我更便于开发

**Comment by JOU-amjs** [comment]
data数据是请求而来的，它一定是异步的，如果你希望向axios一样直接获取数据，可以使用`const data = await getSystemInfo().send()`。这也是可以的，你可以再熟悉一下文档。
