### ISSUE TITLE
GlobalFetch 实现FormData文件上传content-type设置不对，这个问题就是需要删除content-type，可以参考axios

### ISSUE THREAD

**Issue by wyysf123** [alovajs/alova#180]
### 请详细描述bug

不管设置不设置content-type 都不对，

### 复现链接

https://segmentfault.com/a/1190000016927601

### 复现步骤

只要是调用post上传formdata的数据即可

### 期望的表现

content-type的值是
multipart/form-data; boundary=----WebKitFormBoundaryzmD2dfgrcDeYmSBf

### alova 版本

所有版本

### 设备/浏览器/浏览器版本

无关

### 额外的说明

可以看看这个文章：[https://segmentfault.com/a/1190000016927601)](https://segmentfault.com/a/1190000016927601)

**Comment by JOU-amjs** [comment]
是的，在正常情况下，ajax上传文件时浏览器会自动添加一个content type，GlobalFetch是没有默认设置content type的，[源码在这](https://github.com/alovajs/alova/blob/main/src/predefine/GlobalFetch.ts)。

所以我觉得可能不是这个问题，看下可否给个复现demo，或贴出关键的代码，这样可以更好地定位问题并解决它

**Comment by wyysf123** [comment]
使用错误
