### ISSUE TITLE
[bug]invalidateCache方法失效

### ISSUE THREAD

**Issue by wintsa123** [alovajs/alova#188]
### 请详细描述bug

我的项目已经完成了几周了，在最近更新后重新run起来后，发现todolist创建后使用invalidateCache，并不生效。我不知道发生了什么，前后打印都正常，就invalidateCache和fetch不能工作，我并不想用updateState更新新的列进todolist，因为这种做法无法获取数据的数据库id。

### 复现链接

https://stackblitz.com/edit/vue-dnh4vw?file=src%2FApp.vue

### 复现步骤

1.在product.vue点击编辑/新建用路由进入mdEditer组件，提交后路由返回。但这时候失效

### alova 版本

2.9.1

**Comment by wintsa123** [comment]
可能是我加了keepalive？

**Comment by wintsa123** [comment]
我尝试用了中间件来重新发起请求，但是提示alova-scene.esm.js:151  Uncaught (in promise) Error: [alova/subscriber]no handler which id is `flashNew` is matched
我是开启了keepalive的。

**Comment by wintsa123** [comment]
`flashNew`是我写的一个中间件的名称。有点难受这个问题。如果实在解决不了，我只能把状态放在pinia里面了。

**Comment by wintsa123** [comment]
解决了，我尝试了打印onsuccess的数据，发现是有运行的，只不过没发送请求，很显然就是共享请求的问题，给数据加上force就可以了

**Comment by wintsa123** [comment]
@JOU-amjs 我用中间件和关闭共享请求可以正常工作，但是缓存失效以及fetch这两个方法都无法正常工作。我开启了keepalive，不知道是不是这个原因

**Comment by JOU-amjs** [comment]
我正想复现看一下你的问题，不过，复现地址打开后是报错的跑不起来。

按你的描述我盲猜，你希望在todolist页面点击进入新建页添加记录，提交后使用fetch重新刷新todolist页数据。我按你提供的demo代码，没有找到有地方使用useFetcher的地方，只发现在mdEditor里引入了，所以我觉得是不是描述或demo有不一致的地方，让我没办法彻底理解你的情况。

请求共享功能只会在发起了一个还未响应的相同请求时触发，命中缓存或没有还未响应的相同请求下都不会触发，但按我上面的理解，好像也不会出现两个相同请求同时发起的情况，是不是我的理解有错误？可否帮忙再描述清楚一下或修正下demo，也有可能是alova的bug，非常感谢哦

![image](https://github.com/alovajs/alova/assets/29848971/37e23638-9d20-4f02-af28-dbd935d2566d)

**Comment by wintsa123** [comment]
> 
我更新了一下demo，确实是mdEditor里的问题，这是个表单vue，在router进入这个mdEditor后新建完用router.go(-1)返回，这个时候并没有成功重新发起前面页面的请求
```js
if (result.code == 200) {
        MessagePlugin.success(result.message);
        //bug
        //两个方法都无法正常重新发起请求
        // fetch(ArticleType({ typename: '产品中心' }))
        // invalidateCache(ArticleType({ typename: '产品中心' }))
        accessAction('flashNew', delegatedActions => {
          delegatedActions.send({ typename: '产品中心' });
        });
        await router.go(-1);
      } else {
        MessagePlugin.warning(result.message);
      }
```
这一段，我本地能跑得动，上传完确实跑不起来。。。。。。我也想知道为什么QAQ

**Comment by wintsa123** [comment]
> > 
> 
> @JOU-amjs 我更新了一下demo，确实是mdEditor里的问题，这是个表单vue，在router进入这个mdEditor后新建完用router.go(-1)返回，这个时候并没有成功重新发起前面页面的请求。出现问题的代码在这一段
> 
> ```js
> if (result.code == 200) {
>         MessagePlugin.success(result.message);
>         //bug
>         //两个方法都无法正常重新发起请求
>         // fetch(ArticleType({ typename: '产品中心' }))
>         // invalidateCache(ArticleType({ typename: '产品中心' }))
>         accessAction('flashNew', delegatedActions => {
>           delegatedActions.send({ typename: '产品中心' });
>         });
>         await router.go(-1);
>       } else {
>         MessagePlugin.warning(result.message);
>       }
> ```
> 
> demo我本地能跑得动，上传完确实跑不起来。。。。。。我也想知道为什么QAQ

**Comment by JOU-amjs** [comment]
依然如此哦
![image](https://github.com/alovajs/alova/assets/29848971/ad149f3f-a3b9-4df9-80dd-a2feca5d7517)

**Comment by wintsa123** [comment]
> 依然如此哦 ![image](https://user-images.githubusercontent.com/29848971/262211826-ad149f3f-a3b9-4df9-80dd-a2feca5d7517.png)

我也不知道为啥跑不起来。。。。。但我本地clone下来是能够运行的。你可能需要用mock，我的服务端并没部署在服务器上。
