### ISSUE TITLE
nuxt3 useRuntimeConfig()无法使用在alova的二次封装上

### ISSUE THREAD

**Issue by wintsa123** [alovajs/alova#192]
### 需要新特性解决什么问题？

尝试了几次，用这个api都提示router报错。尝试过createAlova(()=>{.....})这样写，发现createAlova的ts判断不允许这样写。

### 它对你有多重要？

有就更好了

**Comment by JOU-amjs** [comment]
为了维护社区，有问题请通过discussion提问，确认是bug或特性请求再使用issue，这个问题已被立即关闭。
![image](https://github.com/alovajs/alova/assets/29848971/f87b2eb6-2e74-4198-8cd6-541c730d279b)
