### ISSUE TITLE
能否增加一个根据服务器端的 etag 是否变化来进行数据缓存更新功能

### ISSUE THREAD

**Issue by deluxebear** [alovajs/alova#199]
### 需要新特性解决什么问题？

能否增加一个根据服务器端的 etag 是否变化来进行数据缓存更新功能

### 它对你有多重要？

有就更好了

**Comment by JOU-amjs** [comment]
请问你在什么情况下需要这个功能
如果可以，可以按模板填写下，不然我可能不能理解这个功能
