### ISSUE TITLE
非内存缓存模式希望能够通过函数返回值来判断是否启用

### ISSUE THREAD

**Issue by yesixuan** [alovajs/alova#212]
### 需要新特性解决什么问题？

本地存储受到 cookie 隐私政策的限制。而用户是否统一 cookie 政策是不能从一开始就确定的，所以需要通过一个 getter 函数来判断是否启用

### 你期望的新特性应该如何呈现？

```js
alovaInstance.GET('/todo/list', {
  localCache: {
    // 判断用户是否同意了 cookie 来决定使用 本地存储还是内存
    mode: () => aggressCookie ? 'restore' : 'memory',
  }
});

### 它对你有多重要？

没有它我就要弃坑了

**Comment by JOU-amjs** [comment]
@yesixuan 你可以通过[受控的缓存](https://alova.js.org/tutorial/next-step/controlled-cache)来自定义你的缓存数据，可以实现这点，我尝试了下代码大概如下：

```js
import { getMethodKey } from 'alova';
const cacheObj = {};

function todoList() {
  const method = alovaInstance.GET('/todo/list', {
    localCache() {
      const methodKey = getMethodKey(method);
      // 判断用户是否同意了 cookie 来决定使用 本地存储还是内存
      return aggressCookie ? JSON.parse(localStorage.getItem(methodKey) || 'null') : cacheObj[methodKey];
    },

    // 在transformData中存储数据
    transformData(response) {
      const methodKey = getMethodKey(method);
      // 用户是否同意了 cookie 则使用localStorage持久化响应数据，否则使用内存
      if (aggressCookie) {
        localStorage.setItem(methodKey, JSON.stringify(response));
      } else {
        cacheObj[methodKey] = response;
      }
      return response;
    }
  });
  return method;
}
```

**Comment by yesixuan** [comment]
> @yesixuan 你可以通过[受控的缓存](https://alova.js.org/tutorial/next-step/controlled-cache)来自定义你的缓存数据，可以实现这点，我尝试了下代码大概如下：
> 
> ```js
> import { getMethodKey } from 'alova';
> const cacheObj = {};
> 
> function todoList() {
>   const method = alovaInstance.GET('/todo/list', {
>     localCache() {
>       const methodKey = getMethodKey(method);
>       // 判断用户是否同意了 cookie 来决定使用 本地存储还是内存
>       return aggressCookie ? JSON.parse(localStorage.getItem(methodKey) || 'null') : cacheObj[methodKey];
>     },
> 
>     // 在transformData中存储数据
>     transformData(response) {
>       const methodKey = getMethodKey(method);
>       // 用户是否同意了 cookie 则使用localStorage持久化响应数据，否则使用内存
>       if (aggressCookie) {
>         localStorage.setItem(methodKey, JSON.stringify(response));
>       } else {
>         cacheObj[methodKey] = response;
>       }
>       return response;
>     }
>   });
>   return method;
> }
> ```

虽然这样可以实现，但是出于以下原因，还是希望可以实现我最开始提到的那种写法
1. 代码的复杂度
2. 代码的入侵性，这里需要定义 `const cacheObj = {};` 
3. 与 alova 的其他功能割裂了，比如占位缓存、缓存过期日期等等
4. 如果是自己实现缓存模式的话，用 alova 的意义就不大了

**Comment by JOU-amjs** [comment]
经过仔细的思考，我们可能不会实现这个功能，原因有这几点
1. 它不太符合[alova的普适性理念](https://alova.js.org/zh-CN/contributing/overview#alova-%E4%BD%BF%E5%91%BD%E5%92%8C%E8%AE%BE%E8%AE%A1%E7%90%86%E5%BF%B5)，而可控的缓存更具有普适性和抽象性
2. 在method实例中定义的localCache只会针对这个实例有效，如果你只需要针对某一个特殊的接口需要做的话，是完全可以按上面做的，alova的缓存机制会保证你在localCache中返回有效值的情况下使用它作为缓存。如果是更多接口需要这样做的话，可以把上面一段封装成一个函数，并在每个地方引入调用即可，例如：
```js
function customCache() {
  const cacheObj = {};
  return {
    localCache() { /* ... */ },
    transformData(response) { /* ... */ }
  };
}

// 使用处
function todoList() {
  return alovaInstance.GET('/todo/list', {
    ...customCache()
  });
}
```
