### ISSUE TITLE
适配器支持 withCredentials 配置

### ISSUE THREAD

**Issue by zhangxuyang-sunny** [alovajs/alova#214]
### 需要新特性解决什么问题？

目前适配器好像无法设置 withCredentials，导致每个请求方法都需要进行配置

`const login = () => {
  return alovaIns.Get("api/xxx", {
    withCredentials: true
  })
}`

### 它对你有多重要？

可以让我更便于开发

**Comment by JOU-amjs** [comment]
https://alova.js.org/zh-CN/tutorial/learning/method-instance#%E8%AE%BE%E7%BD%AE%E8%AF%B7%E6%B1%82%E9%80%82%E9%85%8D%E5%99%A8%E6%94%AF%E6%8C%81%E7%9A%84%E5%8F%82%E6%95%B0

可以看下这边，如果你用的是GlobalFetch（fetch api），它应该叫`credentials`

**Comment by zhangxuyang-sunny** [comment]
我表述不够准确，我是希望在创建实例的时候统一设置 credentials。目前我每个接口都需要配置适配器相关属性例如 credentials

**Comment by JOU-amjs** [comment]
那你可以在beforeRequest中统一设置`method.config.credentials = true`就可以了

**Comment by zhangxuyang-sunny** [comment]
我每个接口都是一个 method，还是要每个都设置啊 0.0

**Comment by zhangxuyang-sunny** [comment]
ok~
