### ISSUE TITLE
适配器用GlobalFetch， 拦截器responded中无法获取，响应的header头？

### ISSUE THREAD

**Issue by youvergood7426** [alovajs/alova#224]
### 请详细描述bug

const instance = createAlova({
		statesHook: VueHook,
		baseURL: baseURL,
		requestAdapter: GlobalFetch(),
		// 请求拦截器
		beforeRequest(method) {
			method.config.headers['Authorization'] = 'TestAuth'
		},
		// 响应拦截器  
		 async responsed(response, method) { 
			console.log(response.headers);
		},
	});

### 复现步骤

拦截器中打印即可。

### alova 版本

2.13.1

**Comment by JOU-amjs** [comment]
fetch api可以通过response.headers.get('xxx')获取对应响应头
