### ISSUE TITLE
useRequest的update函数会触发再次网络请求？

### ISSUE THREAD

**Issue by Ryan-CW-Code** [alovajs/alova#225]
### 请详细描述bug

您好，我使用taro中间件来使用alova，我有一个场景想将useRequest的data值设置为null。
我使用useRequest的update函数，但是会触发再次网络请求，然后再设置data值。我想知道这是设置如此吗？看文档不是这个意思

### 复现步骤

使用useRequest获取data
退出页面时使用update更新data数据为null（小程序）
会再次发送useRequest的网络请求

### 期望的表现

期望调用update时不会再次发送useRequest的网络请求

### alova 版本

2.13.1

### 设备/浏览器/浏览器版本

taro插件版本1.2.1，taro版本3.6.18

### 额外的说明

"@alova/adapter-taro": "^1.2.1"
"alova": "^2.13.1",

**Comment by Ryan-CW-Code** [comment]
> 不会的，可能需要你贴一下相关代码，看下你是怎么使用的，在哪边调用的update

![image](https://github.com/alovajs/alova/assets/75795462/7e1afe61-8bcc-458e-8d87-68b2c132ac9f)
您好，我在jumpFun路由跳转前调用update清空data

**Comment by JOU-amjs** [comment]
问题出在你的组件内部。
```js
if (needUpdate.current === true) {
  needUpdate.current = false;
  send();
}
```
react的每次状态更新都会触发组件函数重新被调用，这段函数就会每次被执行到，因此就会触发重复请求了。
