### ISSUE TITLE
发送验证码，onError事件不生效

### ISSUE THREAD

**Issue by Lron-boy** [alovajs/alova#226]
### 请详细描述bug

发送验证码时，如果接口报错，不会触发onError事件，导致countdown虽然在倒计时，但是错误后不会重置，

### 复现步骤

1.点击按钮
2.开始请求

### 期望的表现

期望可以在接口调用成功后才开始倒计时

### alova 版本

^2.13.1

### 设备/浏览器/浏览器版本

微信开发者工具

**Comment by JOU-amjs** [comment]
感谢反馈。
我刚尝试了复现问题，但一切都是正常的，然后又翻看了下源码和测试用例，也是正常的。也就是接口报错的话，不会开始倒计时，也可以正常触发`onError`。

我猜可能是你所说的报错，应该是接口正常响应了，但返回了例如code: 500这样的数据，但这里的`onError`在以下两个情况才会触发：
1. 接口请求不通或超时导致的直接报错。
2. 前端在全局拦截器、或method实例的`transformData`里抛出一个错误

你可以按以上情况检查下，如果还是没有解决，可以贴一下全局拦截器、method实例的、useCaptcha部分的代码，再贴下网络请求的截图，再进一步分析。也可以加qq频道直接沟通，https://github.com/alovajs/alova/issues/210

**Comment by cleveng** [comment]
400 - 499 状态码 是否会触发 onError 事件， 我接口请求，返回404状态码都是进入了 onSuccess。 这不合理。
