### ISSUE TITLE
[讨论]是否有必要添加全局的onComplete钩子？

### ISSUE THREAD

**Issue by panghujiajia** [alovajs/alova#231]
### 需要新特性解决什么问题？

uniapp适配器场景下，在beforeRequest中会使用uni.showLoading，responded的回调中会uni.hideLoading，但当命中缓存时，该去哪里处理hideLoading？

目前我的处理是在缓存命中日志里面去处理的，是我没找到地方，还是说只有那里能处理？

如果是我没找到，还希望能麻烦贴一下文档位置，如果是没有的话，期望能提供这个命中缓存的回调处理。

另外期望能在responded中加一个onComplete的函数配置。

### 它对你有多重要？

可以让我更便于开发

**Comment by JOU-amjs** [comment]
是的，目前可以通过cacheLogger中处理命中缓存的情况。
从满足需求的角度说目前是够的，但从设计上好像确实缺少针对这种情况的处理，我不知道会有多少人需要全局的onComplete钩子，可以开着这个issue，让大家一同讨论一下。

**Comment by MarshallEriksen-shaomingyang** [comment]
可能有许多人遇到过相同的问题，对于缓存命中大家只知道不会请求后端了，但后面做什么还有些模糊，我觉得在onSuccess能否添加个变量 ishited(是否命中缓存) 用户可以自由选择 if(ishited) 执行一些代码。这只是我的建议

**Comment by MarshallEriksen-shaomingyang** [comment]
目前我希望作者考虑命中缓存的回调处理 就像onSuccess onError

**Comment by JOU-amjs** [comment]
经过思考了一下，确实可以加一个omComplete的全局钩子用于统一处理请求成功、缓存匹配成功、请求失败的逻辑。

我的设计如下：
```js
createAlova({
  responded: {
   // ...
    onComplete(methodInstance) {
      // methodInstance是当前请求的method实例
    }
  }
});
```
它将会在请求成功、缓存匹配成功、请求失败触发。
@MarshallEriksen-shaomingyang @panghujiajia 有人愿意尝试提交PR吗？

**Comment by panghujiajia** [comment]
> 经过思考了一下，确实可以加一个omComplete的全局钩子用于统一处理请求成功、缓存匹配成功、请求失败的逻辑。
> 
> 我的设计如下：
> 
> ```js
> createAlova({
>   responded: {
>    // ...
>     onComplete(methodInstance) {
>       // methodInstance是当前请求的method实例
>     }
>   }
> });
> ```
> 
> 它将会在请求成功、缓存匹配成功、请求失败触发。 @MarshallEriksen-shaomingyang @panghujiajia 有人愿意尝试提交PR吗？

![image](https://github.com/alovajs/alova/assets/76469156/f95ea901-bbcc-487f-bb91-e6e18ab41946)
![image](https://github.com/alovajs/alova/assets/76469156/cbd03349-5467-4414-9c0b-04a0c37d7647)
尝试着改了下，不知道对不对

**Comment by JOU-amjs** [comment]
@panghujiajia 我觉得写的很棒，不过你得提一下PR，这样我才能合并你的代码，然后可能还需要在对应的位置添加一下单元测试来保证代码正常运行，具体的在这边都有描述，可以看下 https://alova.js.org/zh-CN/contributing/overview
