### ISSUE TITLE
useForm和usePagination添加URL参数缓存功能

### ISSUE THREAD

**Issue by Ruler1020730** [alovajs/alova#234]
### 需要新特性解决什么问题？

持久化缓存参数希望添加URL参数缓存功能，有些情况下我可能不希望切换页面之后再回来缓存数据还存在，虽然可以通过重置方法去清除参数，但因为有时候不一定会调用这个方法。

### 它对你有多重要？

有就更好了

**Comment by JOU-amjs** [comment]
目前来说缓存数据就是按url和参数的集合来缓存的，如果你不希望切换后还有缓存，可以直接关闭对应请求的缓存就可以达到预期了
