### ISSUE TITLE
[Bug Report] vue3项目中使用alova时报错，找不到react

### ISSUE THREAD

**Issue by LeoFeng23** [alovajs/alova#24]
### 重现链接

https://github.com/LeoFeng23/bug-test

### alova 版本

2.0.11

### 描述一下你遇到的问题。

Can't resolve 'react' in 'XXX'
vue3项目中使用alova，启动项目，提示Can't resolve 'react' 

### 重现步骤

git pull https://github.com/LeoFeng23/bug-test
cd bug-test
pnpm i
pnpm run dev:h5

**Comment by JOU-amjs** [comment]
非常感谢你的反馈😃，我现在去重现下问题

**Comment by LeoFeng23** [comment]
我添加了这个参数，依然会报错

**Comment by LeoFeng23** [comment]
<img width="630" alt="image" src="https://user-images.githubusercontent.com/65535014/229268505-838bcc1c-3ca2-4ca2-96ce-6aa685637a52.png">
<img width="1556" alt="image" src="https://user-images.githubusercontent.com/65535014/229268525-e16e2810-5e95-49fc-90ec-f3ec9c8a2984.png">

**Comment by LeoFeng23** [comment]
@JOU-amjs

**Comment by JOU-amjs** [comment]
好的，你稍等下，我来看看

**Comment by LeoFeng23** [comment]
有没有群或者可以加个微信吗？

**Comment by JOU-amjs** [comment]
已发布`@alova/adapter-taro@1.2.0`，发布了一个新的vue3请求适配器来解决这个问题，在vue3中你可以这样做：
```js
import { createAlova } from 'alova';
import AdapterTaroVue from '@alova/adapter-taro/vue';

const alovaInst = createAlova(
  baseURL: 'https://api.alovajs.org',
  ...AdapterTaroVue()
);
```

**Comment by JOU-amjs** [comment]
社群还在加紧建设中，到时候我再通知你😁

**Comment by JOU-amjs** [comment]
迟来的交流群，我过来通知你啦，到这边加入https://alova.js.org/zh-CN/tutorial/get-started/overview#%E5%8A%A0%E5%85%A5%E4%BA%A4%E6%B5%81%E7%A4%BE%E5%8C%BA
