### ISSUE TITLE
@alova/scene-vue 中使用分页策略中isLastPage默认是true

### ISSUE THREAD

**Issue by limin2017** [alovajs/alova#242]
### 请详细描述bug

版本 "@alova/scene-vue": "^1.2.1"
isLastPage默认是true（第一次请求加载前），不知道是不是逻辑本来设计如此
我的理解上，正常来说，第一次加载前，是不知道是不是最后一页的，正常应该给false比较合理？我这边的场景是移动端上滑加载数据，需要判断是不是最后一页，默认值是true,数据直接是见底了
![image](https://github.com/alovajs/alova/assets/26949167/43e5864b-6588-496d-8c7b-66f14a858615)
我是主要学后台的，前端是半吊子，不知道看到的源码对不对，第一次应该会跑到这个逻辑里，我改了下代码,将数据的长度大于我的分页大小
![image](https://github.com/alovajs/alova/assets/26949167/f610b2df-5fb2-469a-844c-cc5f6f7df040)
这样尝试后返回的就是false,这是目前的解决方法，还有种就是重新定义一个，监听赋值或者onFetchSuccess里赋值，总归还是麻烦了些

麻烦看一下这个逻辑需不需要优化下？

### 复现步骤

定义usePagination获取isLastPage初始值

### 期望的表现

isLastPage初始值是false

### alova 版本

2.15.0

**Comment by JOU-amjs** [comment]
这是有意为之的，我认为首次加载完数据前列表是空的，此时是不应该让用户可以往下滑动加载下一页，而且列表为空表示为最后一页也是正确的，因为也有可能首次加载列表就是没有数据，此时isLastPage也应该是true才对。

> 我这边的场景是移动端上滑加载数据，需要判断是不是最后一页，默认值是true,数据直接是见底了

针对你的这种情况，如果加载后数据不止一页的话，isLastPage也会自动改为false，因此好像不存在你说的这种情况。如果你还是希望加载时也允许用户下拉加载下一页，那么你可以再把loading状态加入参与判断，例如loading为true时也允许加载下一页，不过从实际业务角度考虑这好像没什么意义。
