### ISSUE TITLE
不能将类型“Method<UnknownRef, object | WatchSource<any>, ListResponse<UserInfo>, unknown, FetchRequestInit, Response, Headers>”分配给类型“Method<UnknownRef, Ref<any>, ListResponse<UserInfo>, unknown, FetchRequestInit, Response, Headers>”。   不能将类型“object | WatchSource<any>”分配给类型“Ref<any>”

### ISSUE THREAD

**Issue by kwongfung** [alovajs/alova#244]
### 请详细描述bug

使用usePagination进行mock分页的时候，提示类型不匹配问题。
![截屏2023-12-04 11 16 11](https://github.com/alovajs/alova/assets/26649981/f8c5fd63-3dfd-405e-9c2a-00aaafe47fe1)
![截屏2023-12-04 11 16 31](https://github.com/alovajs/alova/assets/26649981/ba3e3362-d6c1-47fa-a12d-1b9a5d147ae2)

### 复现步骤

`const { data, loading, send, error } = usePagination(
  (page, pageSize) => getUserList(page, pageSize),
  {
    initialData: []
  }
)`

`export const alovaInstance = createAlova({
  baseURL: baseURL,
  statesHook: VueHook,
  timeout: 50000,
  requestAdapter: dev ? mockAdapter : GlobalFetch(),
  beforeRequest({ config }) {
    config.headers.Authorization = `${token()}`
    config.headers['Content-Type'] = 'application/json; charset=utf-8'
  },
  responded: {
    onSuccess: async (response) => {
      if (response.status >= 400) {
        throw new Error(response.statusText)
      }
      const json = await response.json()

      if (json.code !== 200) {
        throw new Error(json.msg)
      }

      return json.data
    },
    onError: (err) => {
      alert(err.message)
    }
  }
})`

`export const getUserList = (page: number, pageSize: number) =>
  alovaInstance.Get<ListResponse<UserInfo>, unknown>(urls.getUserList, {
    params: { page, pageSize }
  })`

### alova 版本

2.15.0

**Comment by kwongfung** [comment]
usePagination中的类型限定为：`E extends Ref`
![截屏2023-12-05 14 28 12](https://github.com/alovajs/alova/assets/26649981/b35cb0df-6a21-4f72-8bd9-8b463ac6f95f)
但是createAlova实例推断出的却是`WatchSource<any>`
![截屏2023-12-05 14 29 43](https://github.com/alovajs/alova/assets/26649981/7f3e3553-3592-4eb0-b528-c3b6f6bf65a3)
是方法配置的地方出错了还是版本兼容的问题？ @JOU-amjs

**Comment by JOU-amjs** [comment]
尝试了下发现在uniapp上出现了这个问提

**Comment by JOU-amjs** [comment]
alova更新到2.15.1尝试下

**Comment by kwongfung** [comment]
环境是：浏览器。alova更新到2.15.1问题还是存在。

**Comment by kwongfung** [comment]
问题修复，非常感谢。
