### ISSUE TITLE
useWatcher的send手动触发会报错，文档描述与实际使用不符

### ISSUE THREAD

**Issue by chenchenpp** [alovajs/alova#249]
### 请详细描述bug

使用官方文档提供的使用方式，调用发现报错，要求必须要有监听源，这意味着手动触发是不切合实际的。是不是文档有误请检查。
![image](https://github.com/alovajs/alova/assets/33083284/1d720287-6e69-4667-86e5-122744895af7)

### 复现步骤

```js
const { send: queryCategorySend } = useWatcher(storeNo =>
  queryCategory({
    storeNo
  })
)
function changeStore() {
  queryCategorySend(planForm.storeNo)
}
```
![image](https://github.com/alovajs/alova/assets/33083284/3371e921-e70b-4ebb-884c-53c5e8251f57)

### alova 版本

2.14.0

### 额外的说明

个人愚见：感觉既然是监听触发，那么手动触发的意义在哪，这与本身的功能有所矛盾。

**Comment by de1ck** [comment]
我理解 useWatcher API 跟 Vue watch属性差不多，immidate默认位false，主要是为了监听属性改动，触发查询

**Comment by JOU-amjs** [comment]
> 我理解 useWatcher API 跟 Vue watch属性差不多，immidate默认位false，主要是为了监听属性改动，触发查询

正解
