### ISSUE TITLE
usePagination API中配置force选项失效

### ISSUE THREAD

**Issue by frallisland** [alovajs/alova#258]
### 请详细描述bug

在usePagination 函数中配置force项时，ts提示 “对象字面量只能指定已知的属性，并且'force'不在类型‘PaginationHookConfig<any, any, ref<string>>’中”。

### 复现步骤

```typescript
const {data, page}=usePagination(()=>query(), {force:true})
```

### alova 版本

2.11.0

**Comment by JOU-amjs** [comment]
现在`usePagination`没有提供`force`参数，如果你只是希望不缓存，可以在method中关闭缓存即可。
还是有特定的其他需求呢？可以在这边说一下

**Comment by frallisland** [comment]
目前官方文档[分页请求策略](https://alova.js.org/zh-CN/tutorial/strategy/usePagination#hook-%E9%85%8D%E7%BD%AE)声明，usePagination继承useWatcher的所有配置，希望更改文档避免误导开发者。

**Comment by JOU-amjs** [comment]
我重新思考了这个问题，目前已经让usePagination继承了useWatcher的全部选项，升级到v1.4.2可以使用force参数了
