### ISSUE TITLE
[Bug Report] 文档错误

### ISSUE THREAD

**Issue by itmanyong** [alovajs/alova#26]
### Reproduction Link

https://alova.js.org/zh-CN/extension/alova-adapter-uniapp/

### alova Version

all

### Describe the Bug

文档中创建实例时的代码示例中参数错误。createAlova实例接受的是一个对象，而示例代码中的createAlova参数并非如此。如下图
![image](https://user-images.githubusercontent.com/53500371/229360242-6b5b999d-5161-405a-a3a3-651a775ed945.png)

### Reproduce Steps

打开上面文档链接即可

### Device / Browser / Browser Version

all

**Comment by itmanyong** [comment]
这样才对吧
`
const alovaInst = createAlova({
  baseURL: 'https://api.alovajs.org',
  ...AdapterUniapp()

});
`

**Comment by JOU-amjs** [comment]
已修复，感谢你的反馈😁
