### ISSUE TITLE
文档案例代码不一致

### ISSUE THREAD

**Issue by QC2168** [alovajs/alova#262]
### 请详细描述bug

![github readme](https://github.com/alovajs/alova/assets/82024018/1f93c5a4-1961-48fc-af06-7b2f68bc07da)
![npm readme](https://github.com/alovajs/alova/assets/82024018/d2526acd-db4b-4b8a-ad33-046b6f047fdc)

### 复现步骤

无

### 期望的表现

修正npm中的文档

### alova 版本

无

**Comment by QC2168** [comment]
![image](https://github.com/alovajs/alova/assets/82024018/3e528e81-3823-4426-87f9-be47aec58a10)

**Comment by JOU-amjs** [comment]
目前alova的npm README文档里没有这块内容啊，你看的是哪个链接的，可以提供一下吗

**Comment by QC2168** [comment]
找到原因了，是因为访问的是历史版本的readmme[alova/v/1.0.0-beta.11](https://www.npmjs.com/package/alova/v/1.0.0-beta.11)

**Comment by QC2168** [comment]
那会应该是直接从搜索引擎上面搜后进去的有点奇怪..跳到的是这个链接
