### ISSUE TITLE
send 传入的参数希望能添加类型支持。

### ISSUE THREAD

**Issue by Emily-0616** [alovajs/alova#263]
### 需要新特性解决什么问题？

参考react-query 的useMutate

https://tanstack.com/query/latest/docs/react/guides/mutations

### 它对你有多重要？

有就更好了

**Comment by JOU-amjs** [comment]
https://github.com/alovajs/alova/issues/158
可以到这个issue里讨论这个问题，也可以发表下自己的见解。
