### ISSUE TITLE
useRequest data 类型推导失败

### ISSUE THREAD

**Issue by Emily-0616** [alovajs/alova#265]
### 请详细描述bug

![image](https://github.com/alovajs/alova/assets/32790186/ee57c9db-3804-40f6-8cd3-caec6a4aab9a)
![image](https://github.com/alovajs/alova/assets/32790186/8a166cc7-be33-470d-b864-70352070f8c0)

### 复现步骤

1、使用uniapp 适配器。
2、使用useRequest hooks

### alova 版本

2.16.1

**Comment by JOU-amjs** [comment]
类型推导是从alova实例和method实例开始的，因此还需要看下这两个实例的类型才能知道，最好可以把这两个实例的定义发出来看下

**Comment by BaoXianSheng** [comment]
这个类型推导研究不明白
const  temp =(params: Params)=> api
        .Post<PageInfo>('/test', params)
        .then((res) => res);
temp 的type 是正确的  (params: Params) => Promise<PageInfo>
改一下
const  temp =(params: Params)=> api
        .Post<PageInfo>('/test', params)
这个temp 的类型推导就变成了 (params: Params) => Promise<unknown>
