### ISSUE TITLE
response header 哪去了？

### ISSUE THREAD

**Issue by tongjiaqi** [alovajs/alova#267]
### 请详细描述bug

下载文件流通过什么方法能获取response header content-disposition ？

### 复现步骤

1、createAlova => responded => onSuccess => response
2、response.header 里面是什么，浏览器 response.header 哪去了

### alova 版本

2.9.3

**Comment by wandoupeas** [comment]
解决了吗

**Comment by JOU-amjs** [comment]
@wandoupeas 在alova全局拦截器内可以获取到，如果你用的是GlobalFetch适配器，可以通过
```js
responded(response) {
  const responseHeaderItemXXX = response.headers.get('xxx');
}
```
