### ISSUE TITLE
accessAction的设计

### ISSUE THREAD

**Issue by panghujiajia** [alovajs/alova#270]
### 需要新特性解决什么问题？

在使用accessAction触发委托函数的时候，如果id不存在，会报错，阻断程序流程。
这里是否考虑只在控制台输入log，而不是throw error。
尽管id不存在属于编码阶段就应该规避的问题。

### 你期望的新特性应该如何呈现？

期望使用accessAction的时候，发现id不存在，仅在控制台输出error，而非直接throw error

### 它对你有多重要？

有就更好了

**Comment by JOU-amjs** [comment]
我觉得抛出错误是一种更为严谨和灵活的设计方式，首先它可以确保程序的严谨性，也可以让你发现可能存在的问题，就像`undefined.attr`的报错一样，让你注意到这个错误，如果只是给个提示更容易被忽略，其次是你可以灵活地处理，例如捕获它做一些自定义操作，例如你的问题一样，你就可以捕获它，然后自定义输出error
