### ISSUE TITLE
升级版本后影响自己封装的axios请求

### ISSUE THREAD

**Issue by kenixFog** [alovajs/alova#271]
### 请详细描述bug

升级前版本：2.15，同时有自定义封装的axios（参考的VueUse中的useAxios ，进行了一些改造），一切正常
升级后版本：2.16，其于未做任何改变，访问页面，发现通过自定义封装的axios的方法，无法接受到返回值，前端页面卡死。但是后端逻辑已经执行完毕（F12，也无法看到请求的响应结果）

### 复现步骤

1、由于整个框架比较庞大，无法抽取出来做成例子
2、页面逻辑是，点击按钮，按顺序发送请求，根据请求结果，进行后续请求~~
3、整个页面的请求，都是通过自定义封装的axios发送
4、不是所有请求都卡死，是其中某个特定的请求会卡死，导致页面无法进行流程
5、2.15一切正常，大于2.15就会存在该问题

自己没有排查思路，特来请教，是否可以提供排查思路

### alova 版本

2.16

### 设备/浏览器/浏览器版本

chrome、edge最新版

**Comment by yydsapi** [comment]
me too onlyshow loading

**Comment by yydsapi** [comment]
i Update to 2.16.2 and it will be solved
