### ISSUE TITLE
responded全局响应处理函数参数response中的Headers为空

### ISSUE THREAD

**Issue by jiaohxiong** [alovajs/alova#284]
### 请详细描述bug

responded全局响应处理函数参数response中的Headers为空

### 复现步骤

responded全局响应处理函数参数response中的Headers为空

### alova 版本

2.16.1

### 设备/浏览器/浏览器版本

chrome

**Comment by JOU-amjs** [comment]
信息不足以定位问题，最好可以提供足够的问题代码，以及错误截图，或提供一个最简可复现项目。
