### ISSUE TITLE
uniapp 移动端使用缓存功能时,报错

### ISSUE THREAD

**Issue by cfmj** [alovajs/alova#285]
### 请详细描述bug

错误如下
` TypeError: cole.groupCollapsed is not a function. (In 'cole.groupCollapsed("%cHitCache", "padding: 2px 6px; background: #c4fcd3; color: #53b56d;", methodInstance.url)', 'cole.groupCollapsed' is undefined)`

### 复现步骤

uniapp 移动端使用时
使用缓存功能,请求任意接口
报错
` TypeError: cole.groupCollapsed is not a function. (In 'cole.groupCollapsed("%cHitCache", "padding: 2px 6px; background: #c4fcd3; color: #53b56d;", methodInstance.url)', 'cole.groupCollapsed' is undefined)`

### alova 版本

2.16.2

### 设备/浏览器/浏览器版本

webview版本 safari12(移动端)

**Comment by JOU-amjs** [comment]
这个是因为uniapp下命中缓存的提示中不支持这个函数，错误提示不够友好，你可以参考[这边](https://alova.js.org/tutorial/advanced/cache-logger)自定义下或关闭它，后续我们再优化下这个问题，issue可以先留着。

**Comment by JOU-amjs** [comment]
升级到2.17.1修复此问题

**Comment by cfmj** [comment]
感谢
