### ISSUE TITLE
Remove console log in Next js in dev mode

### ISSUE THREAD

**Issue by chertik77** [alovajs/alova#286]
Please remove that ,I didnt find the solution to disable it, only for react-app, vue and webpack 

**star alova if you like it: https://github.com/alovajs/alova
this tips will be removed in production environment
powerful alova request strategies: https://alova.js.org/category/strategy
use mock data: https://alova.js.org/extension/alova-mock
please star alova if you like it: https://github.com/alovajs/alova
this tips will be removed in production environment**

**Comment by JOU-amjs** [comment]
due to certain reason. it cannot be removed on development env. But it would be removed on production env.
Thanks for your understand.

**Comment by chertik77** [comment]
what do u mean of certain reason? and who cares about production, if all my team has console logs in their terminals, because of the server components 😒
<img width="1440" alt="Screenshot 2024-02-26 at 14 04 24" src="https://github.com/alovajs/alova/assets/129002577/659c90a8-69dc-4db9-81cd-c35920c5c054">

It really annoying, but thanks for great product, we are obsessed with @alova/scene-react
