### ISSUE TITLE
vite 引入 alova 的问题：Uncaught SyntaxError

### ISSUE THREAD

**Issue by 596178924** [alovajs/alova#296]
### 请详细描述bug

今天发现了这个库，尝试在项目中用alova，但是引入就报这个错，不知道为什么，是我的方式有问题吗？

### 复现步骤

引入 alova 
import alova, { useRequest } from "alova";
报错：
Uncaught SyntaxError: The requested module '/node_modules/.vite/deps/alova.js?v=8de3c7c9' does not provide an export named 'alova'；

### alova 版本

2.17.1

### 设备/浏览器/浏览器版本

edge

**Comment by JOU-amjs** [comment]
请按文档说明使用

**Comment by Listen-to-poetry-in-the-wind** [comment]
我也出现这个问题了，哥们解决了吗
