### ISSUE TITLE
无法通过实例名称invalidateCache持久已过期缓存

### ISSUE THREAD

**Issue by EthanZhong** [alovajs/alova#300]
### 请详细描述bug

uniapp适配下，无法通过实例名称invalidateCache持久已过期Post缓存

### 复现步骤

请求实例-缓存策略本地持久且5秒过期
进入应用点击发送请求-本地持久缓存正常
5秒后刷新应用-调试器可见storage数据
再次点击按钮  `invalidateCache('info-post')` 执行无效 ，调试器storage并未清除
必须缓存记录上一次请求 `id`,然后执行 `invalidateCache(getInfo('上一次缓存id'))`才有效
```ts
const alova = createAlova({...});
function getInfo(id: string) {
  return alova.Post(
    '/api/info',
    { id },
    {
      name: 'info-post',
      localCache: {
        mode: 'restore',
        expire: 1000 * 5
      }
    }
  );
}
async function handleClick(){
  invalidateCache('info-post');
await sleep(2000);
  await getInfo('xxxx');
}
```

### 期望的表现

通过method名称也失效持久过期缓存

### alova 版本

2.17.1

**Comment by JOU-amjs** [comment]
@EthanZhong 这真是个好问题啊，缓存功能有点久了，你的问题又让我重新审视了它。
一开始以为是一个可以解决的bug，研究了两天后回忆起当初的设计是如此的，具体如下：
当`invalidateCache`传入字符串或正则表达式时，其实用的是[method匹配器](https://alova.js.org/tutorial/advanced/method-matcher)来检索method实例的，而它的检索来源是已经用于请求的method实例快照，因此出现了刷新应用再使用`name`无法失效持久化的缓存。

目前建议传入method实例来失效持久化缓存。

经过重新审视，我们也发现了这一设计产生的歧义，会在后续的大版本中重新设计以便消除歧义，非常感谢你的这个问题。

**Comment by EthanZhong** [comment]
> @EthanZhong 这真是个好问题啊，缓存功能有点久了，你的问题又让我重新审视了它。 一开始以为是一个可以解决的bug，研究了两天后回忆起当初的设计是如此的，具体如下： 当`invalidateCache`传入字符串或正则表达式时，其实用的是[method匹配器](https://alova.js.org/tutorial/advanced/method-matcher)来检索method实例的，而它的检索来源是已经用于请求的method实例快照，因此出现了刷新应用再使用`name`无法失效持久化的缓存。
> 
> 目前建议传入method实例来失效持久化缓存。
> 
> 经过重新审视，我们也发现了这一设计产生的歧义，会在后续的大版本中重新设计以便消除歧义，非常感谢你的这个问题。

另外希望在创建method实例时先默认`meta= {} as Record<string,any>`及为method也配置类alova实例一样的id属性。当我们重试method请求时，业务上希望用同一method重试请求，并获取这个实例多次重试请求后的一些持续状态。由于method发送请求会先 clone出新的method实例，而且最后采用了`Object.assign`来拷贝源实例的属性，如果源实例创建时没有meta，那么后续请求过程中就不会有持续统一引用的meta属性了。

**Comment by JOU-amjs** [comment]
meta默认值已经在这边通过了 https://github.com/alovajs/alova/issues/302。
此外，可以详细描述下具体是什么需求需要在method实例上记录一些持续状态呢？
