### ISSUE TITLE
Typescript error

### ISSUE THREAD

**Issue by chertik77** [alovajs/alova#317]
### Please describe the bug in detail

<img width="1440" alt="Screenshot 2024-03-29 at 11 44 22" src="https://github.com/alovajs/alova/assets/129002577/aafdc45c-b552-49bf-b3ea-04ddc6fc6395">

**Comment by JOU-amjs** [comment]
Could you please provide the version of `alova` and `@alova/scene-react`?

**Comment by JOU-amjs** [comment]
I should have found the problem.
Upgrade `@alova/scene-react` it can be resolved.

**Comment by chertik77** [comment]
still the same problem: 

 `"@alova/scene-react": "1.4.6"`
` "alova": "^2.17.1"`

**Comment by JOU-amjs** [comment]
please upgrade to `@alova/scene-react@1.4.7` to resolve it. Thanks for your feedback.❤
