### ISSUE TITLE
unibest(uni-app) 接入 alova 报错。

### ISSUE THREAD

**Issue by codercup** [alovajs/alova#321]
### 请详细描述bug

<img width="881" alt="image" src="https://github.com/alovajs/alova/assets/65991901/85706c4e-3601-4136-bbf9-c4637a693cbf">
不确定是否跟 pnpm 安装有关。

### 复现链接

https://github.com/codercup/unibest/tree/alova

### 复现步骤

代码层面就报错。
<img width="602" alt="image" src="https://github.com/alovajs/alova/assets/65991901/7c1452cd-9bbd-4d88-84b7-5b32c6cd1d6a">
<img width="533" alt="image" src="https://github.com/alovajs/alova/assets/65991901/dfe0e82c-3b8d-4d99-89a4-509251d27788">

### 期望的表现

能正常使用~

### alova 版本

2.18.2

**Comment by JOU-amjs** [comment]
非常感谢，已经修复了这个问题，升级到2.18.3可用

**Comment by JOU-amjs** [comment]
unibest准备接入alova了吗😁，后面我可以放一个链接推荐别人使用unibest

**Comment by codercup** [comment]
正在接入

**Comment by MeetinaXD** [comment]
> 我就用的unibest啊。使用alova. 大佬帮忙验证一下 支付宝小程序上传的体验版本后 出现报错的问题
> 
> <img alt="Image" width="531" src="https://private-user-images.githubusercontent.com/32589587/455168374-1d11aa2e-3fa2-44fe-857c-b8e386cea44c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTAxMzk5OTAsIm5iZiI6MTc1MDEzOTY5MCwicGF0aCI6Ii8zMjU4OTU4Ny80NTUxNjgzNzQtMWQxMWFhMmUtM2ZhMi00NGZlLTg1N2MtYjhlMzg2Y2VhNDRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA2MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNjE3VDA1NTQ1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU4NjdhNzVhMzk5ZmIyZmI1M2YzODczZmI5M2MyZTg3MzYzZTViMmMyYmMzNTllMGE4NzJhMTNkNGIzNTEyNGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.J1Pj4B2U42A16gZfa6aRutV25Zf0fxwREh3dpFlOp3w">

unibest 使用 alova 是没有问题的。支付宝环境比较特别，可以参考下类似的issue： #694
