### ISSUE TITLE
useWatcher + useFetcher 命中缓存的情况下，数据混乱的问题

### ISSUE THREAD

**Issue by panghujiajia** [alovajs/alova#324]
### 请详细描述bug

```
const { data, loading, send, onSuccess } = useWatcher(
    () => $getTabTopics(currentTagName.value),
    [currentTagName],
    {
        initialData: [],
        immediate: true
    }
);

const { fetch } = useFetcher();

onSuccess(({ data: res }) => {
    console.log(res);
    data.value = res.map(item => {
        let isVisited = false;
        if (visited.value.includes(item.id)) {
            isVisited = true;
        }
        return { ...item, visited: isVisited };
    });
    uni.pageScrollTo({
        scrollTop: 0
    });
    let next = tabs.value[currentTagIndex.value + 1];
    next && fetch($getTabTopics(next.value));
});

```

以上是我的关键代码，假设currentTagName取值为 a、b、c...，对应为顶部tab切换。

bug表现为：

首次加载 currentTagName 为 a，同时会fetch currentTagName 为 b的数据。

然后切换到 b，展示为 b 的数据，同时会去 fetch currentTagName 为 c的数据。

当我从 b 切到到 a 的时候，useWatcher会命中缓存，返回 a 的数据，然后在success回调中，由于会去fetch 下一个的数据，所以表现为 fetch b的数据，同时会命中缓存。

此时视图应该展示的是a的数据，但是实际上展示的是b的数据，不知道为什么。

当我尝试依次从 a 切换到 d，然后再从 d 依次返回到 a，就会发现，切换到 c 显示的 d的数据，切换到 b 显示的 c的数据，依次类推。

怀疑是fetch命中缓存的时候，将useWatcher的数据给替换了

### 复现步骤

见bug描述

### alova 版本

2.18.2

**Comment by JOU-amjs** [comment]
说来惭愧，这个问题在 https://github.com/alovajs/alova/issues/62 中已经被提及过，不过当时思考不够没有解决，这次被你也遇到了。

原因是因为`useFetcher`的一个特性，当fetch指定method的数据时，如果这个method有对应的data状态（即通过useHook请求过这个method），那么也会同步更新这个状态，当时的设计初衷是为了在重新拉取数据时也可以同步更新视图，现在想来，可以为`useFetcher`增加一个参数控制是否同步更新data状态，这样就可以解决，大概如下：

```js
const { fetch } = useFetcher({
  updateState: false // 默认为true
});
```

不过最近可能安排不出时间来增加这个，可能得再过些天解决它。

**Comment by panghujiajia** [comment]
盼修复..

**Comment by JOU-amjs** [comment]
放心😌，近几天会处理哦
