### ISSUE TITLE
unibest 接入 alova 类型提示怎么处理

### ISSUE THREAD

**Issue by codercup** [alovajs/alova#328]
### 请详细描述bug

教我编写代码吧，给我整不会了。https://github.com/codercup/unibest-base   alova 分支

### 复现链接

https://github.com/codercup/unibest-base   alova 分支

### 复现步骤

![image](https://github.com/alovajs/alova/assets/65991901/213c69b6-8a83-4e42-9a65-874781e8b5a7)

### 期望的表现

类型不报错。

### alova 版本

2.19.1

**Comment by JOU-amjs** [comment]
https://alova.js.org/zh-CN/tutorial/combine-framework/typescript#%E8%AE%BE%E7%BD%AE%E5%93%8D%E5%BA%94%E6%95%B0%E6%8D%AE%E7%9A%84%E7%B1%BB%E5%9E%8B

响应类型在这里哦老哥
