### ISSUE TITLE
尝试并发请求，使用alova实例或者通过useRequest进行请求，出现了实际请求丢失，但是有响应的情况，直接使用axios来请求没有问题

### ISSUE THREAD

**Issue by HardStylew** [alovajs/alova#330]
### 请详细描述bug

以下是代码
![image](https://github.com/alovajs/alova/assets/67721761/8a4f0d0f-bec8-445d-bd7a-70a65d97039c)

以下是出错的情况，使用了useRequest，
在控制台的响应信息没有问题，明确的说响应数目没问题
![image](https://github.com/alovajs/alova/assets/67721761/6a61585d-8d5b-4f48-8304-28429419695b)

实际的网络请求，明显低于预期数，这个数目是排查后端的请求日志和浏览器请求日志得来的
![image](https://github.com/alovajs/alova/assets/67721761/9aef70aa-988b-4a93-91e3-513b2257c2a2)

使用axios进行请求就没有遇到此问题，当时一直以为后端服务出了问题，排查了很久发现是请求的丢失。。
如果是我对文档的理解有问题，我接受批评改正

### 复现步骤

不断使用alova实例请求或者使用useRequest，观察请求响应数，和实际请求数

### 期望的表现

并发请求不会出现丢失请求的情况，截图中使用了直接使用axios达到了预期

### alova 版本

2.18.0

**Comment by JOU-amjs** [comment]
很有可能是请求共享导致，尝试关闭掉试试
https://alova.js.org/zh-CN/tutorial/getting-started/method#%E8%AF%B7%E6%B1%82%E5%85%B1%E4%BA%AB

仍然存在的话，再确认下是否命中了缓存导致
