### ISSUE TITLE
设置全局responded拦截器onSuccess后请求不会命中缓存

### ISSUE THREAD

**Issue by liuhongyu847433389** [alovajs/alova#338]
### 请详细描述bug

全局拦截器若不设置onSuccess则第二次开始命中缓存，若打开onSuccess则一直真实请求，不会命中缓存，并且命中缓存后的fromCache一直是undefined
![image](https://github.com/alovajs/alova/assets/24503844/10603a9c-9291-4253-966b-7300db99d744)

### 复现步骤

全局配置，没有绑定请求拦截器，immediate为false，手动请求
![image](https://github.com/alovajs/alova/assets/24503844/37c5a46b-f2dd-48f7-9688-288cf89fbc2b)

### alova 版本

2.20.1

**Comment by JOU-amjs** [comment]
你的`onSuccess`的代码贴一下看下？

**Comment by liuhongyu847433389** [comment]
![image](https://github.com/alovajs/alova/assets/24503844/3968a985-cc3b-45c6-8388-47043c0fde16)
responded不带onSuccess属性就可以走cache，带了就不走，更改请求适配器也同样

**Comment by MeetinaXD** [comment]
你好，这边编写了一个测试样例，没能复现你提到的问题。

<img width="790" alt="image" src="https://github.com/alovajs/alova/assets/40497962/a11086b6-a518-4644-9599-1907aafbb9c7">

或者你可以尝试在 codepen 等平台创建一个能复现问题的 demo，以便我们排查错误。谢谢！

**Comment by liuhongyu847433389** [comment]
好的，这边重试下，感谢
