### ISSUE TITLE
Upload progress not working in 2.20.0

### ISSUE THREAD

**Issue by proddy** [alovajs/alova#339]
### Please describe the bug in detail

With the upgrade from 2.19.2 to 2.20.x the Upload progress hook is no longer working. 

`uploading` is not refreshing the `uploading.total` and `uploading.loaded`.

```
 const { uploading } = useRequest(uploadPoster);
  return (
    <>
      <div>File size: {uploading.total}B</div>
      <div>Uploaded: {uploading.loaded}B</div>
      <div>Progress: {(uploading.loaded / uploading.total) * 100}%</div>
   </>
```

I made a remark on [Discord ](https://discord.com/channels/1151003341883715674/1151003342328307718/1231328615992660009) earlier.

My code follows the https://alova.js.org/tutorial/combine-framework/download-upload-progress. 

I could make a Sandbox for this, but it isn't easy as it requires backend code to upload the file stream.

### steps to reproduce

try the code at https://alova.js.org/tutorial/combine-framework/download-upload-progress/

### alova version

2.20.0 and 2.20.1

**Comment by MeetinaXD** [comment]
@JOU-amjs  fixed, waiting for PR merge #340

**Comment by JOU-amjs** [comment]
@proddy Sorry, It's my mistake. And it happens that the upload function cannot be unit tested.😂 Now it was fixed at v2.20.2

**Comment by proddy** [comment]
Thanks for the fix. Could you also fix the `loaded` and `total` - you have them inverted. `loaded` is showing the total file size of the upload data and `total` is showing the progress :-)

**Comment by proddy** [comment]
cheers!

**Comment by JOU-amjs** [comment]
> Thanks for the fix. Could you also fix the `loaded` and `total` - you have them inverted. `loaded` is showing the total file size of the upload data and `total` is showing the progress :-)

Now that was fixed. please update `@alova/adapter-axios` or `@alova/adapter-xhr` to latest version.

**Comment by proddy** [comment]
all fixed now, thanks!
