### ISSUE TITLE
使用Mock的时候直接报 TypeError: Cannot read properties of undefined (reading 'toString')

### ISSUE THREAD

**Issue by jekip** [alovajs/alova#345]
### 请详细描述bug

我原本想使用 @faker-js/faker 这个库来创建假数据，即便我不用 直接写死数据也依然存在这个问题，详细对比文档使用方案，好像并没有看错差异，还请作者指点迷津，感谢！

![image](https://github.com/alovajs/alova/assets/19426584/ed2d6e56-fda6-4f02-86a2-f3dae6072c82)

export default defineMock({
  // 登录
  '[POST]/login': () => {
    return {
      id: faker.number.int({ max: 99999999, min: 10000 }),
      token: faker.string.uuid(),
    }
  }
})

const mockAdapter = createAlovaMockAdapter([mockUser], {
  enable: true,
  httpAdapter: GlobalFetch(),
  delay: 1000,
  mockRequestLogger: true,
  onMockResponse: data => new Response(JSON.stringify(data)),
});

export const Alova = createAlova({
  baseURL: apiUrl,
  statesHook: VueHook,
  requestAdapter: mockAdapter,
})

### 复现链接

123

### 复现步骤

配置 `mock`，之后，直接在页面，发生请求

### 期望的表现

另外补充一点需求，这个 mock 包装器，当触发请求的适合，浏览器/终端，原本就无法看到网络请求吗？

### alova 版本

2.20.1

**Comment by jekip** [comment]
@JOU-amjs 有空的时候帮我看一下、`alovajs` 库不错，我打算把我们产品，统一切换到 `alovajs`

**Comment by JOU-amjs** [comment]
@jekip 非常感谢你的认可啊，你的问题是`onMockResponse`配置错了，它应该返回一个包含`response`和`headers`。不过我看你使用了`GlobalFetch`，可以不用设置`onMockResponse`，具体[查看这里](https://alova.js.org/zh-CN/tutorial/request-adapter/alova-mock#%E8%BD%AC%E6%8D%A2%E6%A8%A1%E6%8B%9F%E6%95%B0%E6%8D%AE)

**Comment by jekip** [comment]
Indeed, thank you very much

**Comment by JOU-amjs** [comment]
对了，这个适配器是本地模拟请求的，并没有实际发出请求，因此是看不到请求信息的

**Comment by jekip** [comment]
好的，如果能看到无非也是一大亮点，不过要兼容多个环境使用，可能确实有一些工作量，`vite` 下的话 `vite-plugin-fake-server` 体验还是不错的，最后，期待 `alovajs` 越来越好！

**Comment by JOU-amjs** [comment]
感谢😁，确实存在很多适配问题，现在的话，我们的在控制台会输出请求和响应信息哦
