### ISSUE TITLE
按照文档typescript项目引入，在没有导入alova，是类型推断会标红

### ISSUE THREAD

**Issue by Nowork-wen** [alovajs/alova#360]
### 请详细描述bug

封装了AlovaInstance是咧，然后再请求的接口封装闻文件中使用
如下图
![Snipaste_2024-05-11_17-25-47](https://github.com/alovajs/alova/assets/76811412/ed62b46b-c66f-4ae0-b2e1-85d4bb87eb4d)
但是只要引入alova，飘红就会没有（不管引入的是啥，只要引入alova，就不会报错）

### 复现步骤

如上图片，放开注释和解开注释，就能复现此问题

### 期望的表现

帮忙看看是啥原因

### alova 版本

2.20.3

### 设备/浏览器/浏览器版本

在webstorm编辑器，2024.1版本

### 额外的说明

![Snipaste_2024-05-11_17-25-47](https://github.com/alovajs/alova/assets/76811412/f20ccfaf-f0bf-4c21-a0b4-0579b2d90974)
![Snipaste_2024-05-11_17-30-01](https://github.com/alovajs/alova/assets/76811412/7a435373-650c-4991-9730-9cde6b114912)

**Comment by Nowork-wen** [comment]
报错内容：The inferred type of getMonitor cannot be named without a reference to .pnpm/alova@2.20.3/node_modules/alova. This is likely not portable. A type annotation is necessary.

**Comment by MeetinaXD** [comment]
你好，这个问题这边似乎没法复现，请提供更多的信息如：typescript版本等。

建议你这边提供一个可以复现问题的最小项目，托管到codepen这类平台上，方便我们更快定位，感谢！

**Comment by Nowork-wen** [comment]
不好意思，根据您的反馈，我检查了一下编辑器的typescript版本，是因为版本太低的原因造成的，更新以后不会在报错了，感觉您的回答，谢谢！！！
