### ISSUE TITLE
react项目中使用了alova导致jest执行单测报错

### ISSUE THREAD

**Issue by liuchanghao** [alovajs/alova#361]
### 请详细描述bug

react项目中集成了alova，在使用jest执行单测后，报错：
![image](https://github.com/alovajs/alova/assets/18344481/a0299738-0a73-40dc-8d30-1b76319b9266)

### 复现步骤

1. react项目
2. 安装alova
3. 安装jest
4.创建demo.test.tsx
5. 执行 jest --watch

### 期望的表现

安装了alova后，不能影响项目中使用jest做单测。

### alova 版本

"alova": "^2.9.3"

**Comment by MeetinaXD** [comment]
你好，这不是alova的bug，这是因为在默认情况下 jest 不支持 ESM 模块，且忽略 node_modules 内模块的转译。

可以参考一下这个文章：[Jest Cannot use import statement outside a module 单测报错完全解决方案](https://juejin.cn/post/7032623660896796709)

**Comment by MeetinaXD** [comment]
你可以参考方法一和方法三。alova 的 npm 包同时提供了 esm 和 cjs 格式的产物。

如果你需要修改jest配置，可以参考：

```js
// jest.config.js
{
  // ...
  transformIgnorePatterns: ['/node_modules/(?!(alova))']
}
```

这样可以打开对 alova 的转译。

**Comment by liuchanghao** [comment]
> 你可以参考方法一和方法三。alova 的 npm 包同时提供了 esm 和 cjs 格式的产物。
> 
> 如果你需要修改jest配置，可以参考：
> 
> ```js
> // jest.config.js
> {
>   // ...
>   transformIgnorePatterns: ['/node_modules/(?!(alova))']
> }
> ```
> 
> 这样可以打开对 alova 的转译。



> 你可以参考方法一和方法三。alova 的 npm 包同时提供了 esm 和 cjs 格式的产物。
> 
> 如果你需要修改jest配置，可以参考：
> 
> ```js
> // jest.config.js
> {
>   // ...
>   transformIgnorePatterns: ['/node_modules/(?!(alova))']
> }
> ```
> 
> 这样可以打开对 alova 的转译。

感谢回复！

我的项目采用的是Monorepo模式。  

alova依赖我是安装到最外层的node_modules中的。

按照： transformIgnorePatterns: ['/node_modules/(?!(alova))'] 写的话，是不是路径没对？

**Comment by MeetinaXD** [comment]
根据项目的实际情况修改一下配置中的路径，例如可以通过 `<rootDir>` 来确定 `node_modules`。

具体请自行查阅 jest 的配置文档：[transformIgnorePatterns customization](https://jestjs.io/docs/tutorial-react-native#transformignorepatterns-customization)

**Comment by ranwawa** [comment]
如果要在jest配置中单独针对alova进行配置，那就应该算alova的bug

既然alova/globalFetch提供了cjs模块，为什么不把alova/react也同样提供一个cjs模块呢。或者在导出的时候，使用umd做为默认导出，而不是esm作为默认导出也能解决这个问题。

**Comment by ranwawa** [comment]
你的邮件我已收到，查收后会尽快回复！：）

**Comment by JOU-amjs** [comment]
@liuchanghao @ranwawa 已在2.20.4中添加了vue、react、svelte三个statesHook的cjs打包文件

**Comment by liuchanghao** [comment]
> * npm package (@latest dist-tag)

你好！
我安装了最新的alova版本：2.20.4
在我的项目中，我使用alova封装了一个公共请求库叫alova.ts

这个文件中使用了
```js
import ReactHook from 'alova/react';
```

报错截图如下：
![image](https://github.com/alovajs/alova/assets/18344481/1fd27c18-98d6-4219-b642-ffec07c10a44)

**Comment by MeetinaXD** [comment]
确认是导出配置有问题，等待合入。 #367

**Comment by JOU-amjs** [comment]
@liuchanghao @MeetinaXD 已合并  并发布

**Comment by ranwawa** [comment]
你的邮件我已收到，查收后会尽快回复！：）
