### ISSUE TITLE
Taro开发环境，占位缓存模式，不会自动发送新请求。

### ISSUE THREAD

**Issue by Ryan-CW-Code** [alovajs/alova#362]
### 请详细描述bug

我使用Taro开发微信小程序，尝试使用占位缓存模式，期望的现象是 
发送请求 --》 先使用旧数据渲染  --》 再发送请求  --》 将新数据渲染

我使用的现象是
发送请求 --》命中缓存  
**不会再发送新请求了**

我用的useRequest发送请求

### 复现步骤

期望的现象是 
发送请求 --》 先使用旧数据渲染  --》 再发送请求  --》 将新数据渲染

我使用的现象是
发送请求 --》命中缓存  
**不会再发送新请求了**

我用的useRequest发送请求

### alova 版本

2.20.3

### 设备/浏览器/浏览器版本

微信小程序基础库3.1.5

**Comment by MeetinaXD** [comment]
你好，这个问题这边似乎没法复现。请提供更多的信息如：Taro 版本、微信开发工具版本、使用的 React/Vue 版本等。

建议你这边提供一个可以复现问题的最小项目，托管到codepen这类平台上，方便我们更快定位，感谢！

**Comment by Ryan-CW-Code** [comment]
我用web端平台写的最简易示例，也是命中缓存后就不会进行真实请求了
```
import { createAlova } from "alova";
import GlobalFetch from "alova/GlobalFetch";

const alovaInstance = createAlova({
  requestAdapter: GlobalFetch(),
  localCache: {
    POST: {
      mode: "placeholder", // 设置缓存模式为持久化占位模式
      expire: 240 * 1000, // 缓存时间
    },
  },
});

setInterval(() => {
  console.log("aaaaaaaaaaa");
  alovaInstance
    .Post("https://jsonplaceholder.typicode.com/posts", {
      title: "foo",
      body: "bar",
      userId: 1,
    })
    .then((data) => {
      app.innerHTML = data + "nihao";
    });
}, 1000);
```

**Comment by MeetinaXD** [comment]
根据你提供的示例代码，这边的测试是正常的。
表现的行为是：`打开应用` -> `发起请求` -> `返回新数据` -> `设置缓存`，并且在发起新请求之后，后续的请求都不再发出，而使用缓存。

只发出一次请求：

<img width="554" alt="image" src="https://github.com/alovajs/alova/assets/40497962/4e00c230-4c29-400e-aa50-ae0178d48d49">

第一次发出请求，后续都使用缓存：

<img width="769" alt="image" src="https://github.com/alovajs/alova/assets/40497962/5dbdc0df-6d94-4258-9896-9f61bc76a546">

还有就是你提供的 demo 并没有使用 useRequest，所以不会在首次请求发出前使用缓存。

**Comment by Ryan-CW-Code** [comment]
> 根据你提供的示例代码，这边的测试是正常的。 表现的行为是：`打开应用` -> `发起请求` -> `返回新数据` -> `设置缓存`，并且在发起新请求之后，后续的请求都不再发出，而使用缓存。
> 
> 只发出一次请求：
> 
> <img alt="image" width="554" src="https://private-user-images.githubusercontent.com/40497962/330319132-4e00c230-4c29-400e-aa50-ae0178d48d49.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2NzExNjMsIm5iZiI6MTcxNTY3MDg2MywicGF0aCI6Ii80MDQ5Nzk2Mi8zMzAzMTkxMzItNGUwMGMyMzAtNGMyOS00MDBlLWFhNTAtYWUwMTc4ZDQ4ZDQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE0VDA3MTQyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyYWU5ZGJkMTM5ZGMwMDliNGYwOWExNTM5N2FlM2VmYjY1NTI3MDc1OTAyYTQyM2JjMTE5MWVkYzAwZTJkYWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ow5U7wHN-1pz3zysPbii3tUA1mdq1o-Hr6Z0xhTOd3Q">
> 第一次发出请求，后续都使用缓存：
> 
> <img alt="image" width="769" src="https://private-user-images.githubusercontent.com/40497962/330320438-5dbdc0df-6d94-4258-9896-9f61bc76a546.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2NzExNjMsIm5iZiI6MTcxNTY3MDg2MywicGF0aCI6Ii80MDQ5Nzk2Mi8zMzAzMjA0MzgtNWRiZGMwZGYtNmQ5NC00MjU4LTk4OTYtOWY2MWJjNzZhNTQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE0VDA3MTQyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5YTNiNDVlMDRiYWNhMzM3Zjc0YTgwYjc4Y2Q5Zjk2M2NiZTUyMWJhZWMzNTk3MDAyZDQyZjBjMDU5NWY5MzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.W9YzRb54F1j_O44jNJADJu2T-PQWt6mvsB4l0CeTrl8">
> 还有就是你提供的 demo 并没有使用 useRequest，所以不会在首次请求发出前使用缓存。

我理解的 `placeholder` 模式流程  
第一次请求
`打开应用` -> `发起请求` -> `返回新数据` -> `设置缓存`
第二次请求
`发起请求` -> `命中缓存` -> `返回缓存数据` -> `实际开始发送请求` -> `返回新数据` -> `设置缓存`

不知道我理解的 `placeholder` 模式的意思对吗

**Comment by Ryan-CW-Code** [comment]
我想达到的就是这样的效果
![image](https://github.com/alovajs/alova/assets/75795462/5d739e7d-fa89-4841-aece-bc0c88802f89)

**Comment by MeetinaXD** [comment]
你提到的“第二次请求”有没有经过页面刷新。还是说如你在 demo 的用法一样，通过第二次调用方法去发起请求？

memory 和 placeholder 缓存模式的工作流程：

  1. 除非页面刷新了，否则数据都会在内存中有缓存。
  2. 在发起请求时，alova 会判断这个缓存是否过期了（根据你设置的过期时间）
  3. 如果过期了，则发起新的请求；否则就直接用缓存数据返回。

而使用了 placeholder 模式时，缓存还会存放在 localStorage 中。下次打开应用时，首次请求将直接返回旧数据，同时发起新请求。

这边看你的需求是希望每次请求都真实发出去，同时又使用缓存。这不是 alova 的缓存工作机制

如果你真的有这种需求，使用 useRequest 即可， 无需设置缓存。

``` typescript
const { data, send, onSuccess } = useRequest(() => alovaInstance.Get(...))

onSuccess(() => console.log(data))
setInterval(() => send(), 1000)
```

**Comment by Ryan-CW-Code** [comment]
> 你提到的“第二次请求”有没有经过页面刷新。还是说如你在 demo 的用法一样，通过第二次调用方法去发起请求？
> 
> memory 和 placeholder 缓存模式的工作流程：
> 
> 1. 除非页面刷新了，否则数据都会在内存中有缓存。
> 2. 在发起请求时，alova 会判断这个缓存是否过期了（根据你设置的过期时间）
> 3. 如果过期了，则发起新的请求；否则就直接用缓存数据返回。
> 
> 而使用了 placeholder 模式时，缓存还会存放在 localStorage 中。下次打开应用时，首次请求将直接返回旧数据，同时发起新请求。
> 
> 这边看你的需求是希望每次请求都真实发出去，同时又使用缓存。这不是 alova 的缓存工作机制
> 
> 如果你真的有这种需求，使用 useRequest 即可， 无需设置缓存。
> 
> ```ts
> const { data, send, onSuccess } = useRequest(() => alovaInstance.Get(...))
> 
> onSuccess(() => console.log(data))
> setInterval(() => send(), 1000)
> ```

好的，了解了。  谢谢

**Comment by Ryan-CW-Code** [comment]
昨天用请求中间件完成了我的需求，给有需要的提供一个参考吧。
现在 `useRequest` 发送请求的时候 `data` 会置为null，这样小程序返回页面都会显示加载动画。 其实直接显示上次数据然后后台更新就行。
用这个中间件可以实现如果有缓存 `data` 会被直接赋值为之前的缓存并把`loading`设置为false，然后发送实际请求，再更新数据到`data`。

```
import { useRequest as _useRequest } from 'alova';

// 重定义了useRequest
export const useRequest: typeof _useRequest = (methodHandler, config) => {
  return _useRequest(methodHandler, {
    ...config,
    middleware: (context, next) => {
      context.method.config.localCache = {
        mode: 'memory', 
        expire: 15 * 60 * 1000, 
      };
      context.controlLoading(); // 手动控制加载

      if (context.cachedResponse) {
        console.log('命中缓存', context.method.url);
        context.update({ loading: false, data: context.cachedResponse });
        context.method.meta = { ...context.method.meta, RyanCached: true };
      } else {
        context.update({ loading: true });
      }

      return next({ force: true })
        .then((value) => {
          context.update({ loading: false });
          return value;
        })
        .catch((error) => {
          context.update({ loading: false });
          return Promise.reject(error);
        });
    },
  });
};
```
