### ISSUE TITLE
useRequest发送请求如何不使用缓存模式

### ISSUE THREAD

**Issue by Lin-Van** [alovajs/alova#370]
### 请详细描述bug

不想影响全局的缓存设置，是否是应该在 force: true是不使用缓存？

### 复现步骤

 const {
    onSuccess,
    onError,
  } = useRequest(getData, {
    force: true
  })

### alova 版本

2.18.3

**Comment by MeetinaXD** [comment]
见文档：[强制请求](https://alova.js.org/zh-CN/tutorial/cache/force-request/#动态设置-force-值)

**Comment by Lin-Van** [comment]
> 见文档：[强制请求](https://alova.js.org/zh-CN/tutorial/cache/force-request/#%E5%8A%A8%E6%80%81%E8%AE%BE%E7%BD%AE-force-%E5%80%BC)

好的 谢谢诶
