### ISSUE TITLE
[Bug]: url自动增加'/'，导致后端服务无法路由

### ISSUE THREAD

**Issue by m839336369** [alovajs/alova#382]
### 这是否是一个 Bug？

- [X] 我已经确认我要报告的是一个 Bug

### 这个问题是否已经存在？

- [X] 我已经确认这个 Issue 没有被报告过

### Alova 版本

2.20.5

### 前端框架

Vue

### 问题描述

![image](https://github.com/alovajs/alova/assets/30934916/c7867f7a-0ca8-4be7-8dd8-93b78cbbe267)
url为' '，但在后端请求时，会自动加一个'/'，导致restful风格的api访问失效。
![image](https://github.com/alovajs/alova/assets/30934916/0d3dbc67-1880-4cc8-9845-748dc4fc2459)
![image](https://github.com/alovajs/alova/assets/30934916/4b4107c8-84ed-416f-82c4-ceca04b1fb60)

### 复现步骤

1.Post url使用‘ ’作为访问路径，即只通过Alova实例的BaseUrl访问

**Comment by MeetinaXD** [comment]
感谢反馈，这是没考虑到的边缘情况。已在 #384 中修复。

**Comment by MeetinaXD** [comment]
你好，修复已经包含在`alova@2.21.2` 中，更新 alova 版本即可修复 😃

**Comment by m839336369** [comment]
export const queryCheck = (patientId: string, page: number, size: number) =>
  checkService.Get(
    `?patient_id=${patientId}&page_number=${page - 1}&page_size=${size}`,
    {
      async transformData(data: Response) {
        const res = JSON.parse(await data.text());
        return {
          total: res.totalElements,
          page: res.number + 1,
          pageSize: res.size,
          pageCount: res.totalPages,
          data: res.content,
          isLastPage: res.last
        };
      },
      timeout: 10000
    });
    
    如果加上?条件筛选，也会出现这个问题，21版本不加的话可以正常使用了。

**Comment by m839336369** [comment]
![image](https://github.com/alovajs/alova/assets/30934916/a406621b-b081-4880-94b3-c5e709233fcb)

**Comment by MeetinaXD** [comment]
请使用 `params` 选项。
