### ISSUE TITLE
[Bug]: `alova/client`类型文件指向错误

### ISSUE THREAD

**Issue by JOU-amjs** [alovajs/alova#407]
### 这是否是一个 Bug？

- [X] 我已经确认我要报告的是一个 Bug

### 这个问题是否已经存在？

- [X] 我已经确认这个 Issue 没有被报告过

### Alova 版本

3.0.0-beta.3

### 前端框架

其他框架

### 问题描述

![image](https://github.com/alovajs/alova/assets/29848971/792bddf2-a245-4949-bdbb-d2840b8ee570)

需要指向`typings/clienthook/index.d.ts`

### 复现步骤

无

**Comment by MeetinaXD** [comment]
fix in `alova@3.0.0-beta.6`
