### ISSUE TITLE
[Bug]: useHooks的`update`类型错误

### ISSUE THREAD

**Issue by JOU-amjs** [alovajs/alova#420]
### 这是否是一个 Bug？

- [X] 我已经确认我要报告的是一个 Bug

### 这个问题是否已经存在？

- [X] 我已经确认这个 Issue 没有被报告过

### Alova 版本

3.0.0-beta.6

### 前端框架

React

### 问题描述

```js
const {
    // ...
    update
  } = usePagination((page, pageSize) => queryStudents(page, pageSize, studentName, clsName), {
    watchingStates: [studentName, clsName],
    initialData: { total: 0, list: [] },
    debounce: [800],
    abortLast: true,
    total: res => res.total,
    data: res => res.list
  });
```

其中`update`的类型是`undefined`和`any`组成，没有正确推断。

<img width="372" alt="image" src="https://github.com/alovajs/alova/assets/29848971/a480445d-a429-4b89-9ed5-a2a3ea43f169">

### 期望的表现

与导出类型的数据值相同

<img width="310" alt="image" src="https://github.com/alovajs/alova/assets/29848971/1d0aa6eb-4854-47aa-a964-5fe0674f8591">

### 复现链接

https://github.com/alovajs/alova/blob/chore/demo/examples/react/src/views/PaginatedList/index.jsx

### 复现步骤

无

**Comment by MeetinaXD** [comment]
似乎是因为StateUpdater中的推断出现了问题，推出了 never。

[alova/typings/clienthook/general.d.ts#L64](https://github.com/alovajs/alova/blob/d38031cdfd304c561bdd53a996762acbfeb582c7/packages/alova/typings/clienthook/general.d.ts#L64)

将此处改为：

```typescript
export type StateUpdater<ExportedStates extends Record<string, any>> = (newStates: {
  [K in keyof ExportedStates]?: ExportedStates[K] extends ExportedState<infer R, any> | ExportedComputed<infer R, any>
    ? R
    : ExportedStates[K];
}) => void;
```

可以解决该问题。

<img width="364" alt="image" src="https://github.com/alovajs/alova/assets/40497962/261e0940-9cb1-4410-a83b-fb3b913267a4">
