### ISSUE TITLE
[Bug]: 基于服务端Token认证，refreshTokenOnSuccess的handler中，调用最近请求接口无响应

### ISSUE THREAD

**Issue by Skiyee** [alovajs/alova#438]
### 这是否是一个 Bug？

- [X] 我已经确认我要报告的是一个 Bug

### 这个问题是否已经存在？

- [X] 我已经确认这个 Issue 没有被报告过

### Alova 版本

2.21.0

### 前端框架

Vue

### 问题描述

```
refreshTokenOnSuccess: {
  handler: async (response, method) => {
    console.log(method)
    // 打印出 method 是正常的
    
    const res = await method.send()
    // 无请求发出，打印 res 无任何值存在
  }

### 期望的表现

能做出正确请求

### 复现链接

_No response_

### 复现步骤

示例如上，请求未发出

### 系统信息

```shell
"alova": "^2.21.0",
"@alova/adapter-uniapp": "^1.2.2",
"@alova/scene-vue": "^1.6.1",
"@alova/mock": "^1.5.1",
"@dcloudio/uni-app": "3.0.0-alpha-4010920240606001",
```

**Comment by MeetinaXD** [comment]
请阅读文档并了解参数的含义：[在服务端无感刷新](https://alova.js.org/zh-CN/tutorial/strategy/tokenAuthentication#在服务端无感刷新-token)

**Comment by Skiyee** [comment]
不好意思，打扰了

我重启后，现在就好了

不知道是不是编译缓冲的问题，我这边上午一直不会自动再次发起请求，我才不得不使用send

**Comment by dodu2014** [comment]
@Skiyee 你是怎样配置的？我这边按照 [在服务端无感刷新](https://alova.js.org/zh-CN/tutorial/strategy/tokenAuthentication#%E5%9C%A8%E6%9C%8D%E5%8A%A1%E7%AB%AF%E6%97%A0%E6%84%9F%E5%88%B7%E6%96%B0-token) 文档配置下来，怎么一直报错，也没有找到示例，你能分享一下这里怎么配置的吗？谢谢

**Comment by Skiyee** [comment]
就你发的这个文档往下拉，有相关配置的说明
