### ISSUE TITLE
[Bug]: usePagination对加载异常的页数会认为加载成功了

### ISSUE THREAD

**Issue by thisXY** [alovajs/alova#441]
### Is this a Bug?

- [X] I have confirmed that I want to report a Bug

### Has this issue been reported before?

- [X] I have confirmed that this Issue has not been reported before

### Alova Version

2.21.3

### Framework

React

### Problem Description

关于使用usePagination的问题：比如请求第2页失败了，再次请求下一页(像这样：setPage(value => value + 1);) ，结果会请求第3页，然而第2页失败了不是应该继续请求第2页吗

### Expected Behavior

加载失败后，页数会回退到上一次加载成功的页数，如此在(setPage(value => value + 1);)后便会继续尝试加载这个失败的页数

### Reproduction Steps

1. 使用usePagination加载页数2，此时加载发生接口异常(页数2加载失败了)
2. 继续通过`setPage(value => value + 1);`这样尝试加载，会发现此时加载了页数3

**Comment by MeetinaXD** [comment]
humm，这确实是没考虑过的事情。

我们可以讨论这个策略：“加载失败后，页数会回退到上一次加载成功的页数”：

- 自己实现这个功能会不会更好？有些用户也许不希望这样
- 如果采取这样的策略，网络不稳定时请求乱序，导致奇怪的回退。

例如请求顺序：`A -> B -> C -> D`，实际返回顺序：`D -> C -> B -> A`，其中 `A` 请求失败，这时回退到上一个成功的页数 `B` 就会显得很奇怪。

还有一种情况：用户只想直接跳过中间几页看后面的页面。这时用户根本不关心中间发生了什么，成功或失败都无所谓了。如果固执地回退重试，恐怕会造成不好的体验。

**Comment by thisXY** [comment]
那我们是否可以考虑提供这样一个方法比如`loadNextPage`呢，该方法意图就是加载下一页，那这样我们不用关心具体是加载的哪一页了，只要总是基于当前成功的最后一页往下一页加载就行了。如此还可以考虑有`loadPrevPage`。。

**Comment by thisXY** [comment]
> humm，这确实是没考虑过的事情。
> 
> 我们可以讨论这个策略：“加载失败后，页数会回退到上一次加载成功的页数”：
> 
> * 自己实现这个功能会不会更好？有些用户也许不希望这样
> * 如果采取这样的策略，网络不稳定时请求乱序，导致奇怪的回退。
> 
> 例如请求顺序：`A -> B -> C -> D`，实际返回顺序：`D -> C -> B -> A`，其中 `A` 请求失败，这时回退到上一个成功的页数 `B` 就会显得很奇怪。
> 
> 还有一种情况：用户只想直接跳过中间几页看后面的页面。这时用户根本不关心中间发生了什么，成功或失败都无所谓了。如果固执地回退重试，恐怕会造成不好的体验。

那我们是否可以考虑提供这样一个方法比如loadNextPage呢，该方法意图就是加载下一页，那这样我们不用关心具体是加载的哪一页了，只要总是基于当前成功的最后一页往下一页加载就行了。如此还可以考虑有loadPrevPage。。

**Comment by de1ck** [comment]
> 即使提供了这样的方法，我们实现的效果应该也是 `setPage(value => value + 1)` 而不是根据上一个成功的页码加载下一个，理由和上面是一样的。
> 
> 这个需求没理解到应用场景是什么，即使真的有这样的需求，应该也是非常好实现的。但如果为了比较小众的需求而添加功能的话，我认为是不妥的。
> 
> 你可以描述一下这个功能的使用场景吗？

这个可能适合移动端（或者瀑布流）加载下一页数据时候，加载失败的场景吧。如果中间请求失败，部分数据就缺失了

**Comment by thisXY** [comment]
> 即使提供了这样的方法，我们实现的效果应该也是 `setPage(value => value + 1)` 而不是根据上一个成功的页码加载下一个，理由和上面是一样的。
> 
> 这个需求没理解到应用场景是什么，即使真的有这样的需求，应该也是非常好实现的。但如果为了比较小众的需求而添加功能的话，我认为是不妥的。
> 
> 你可以描述一下这个功能的使用场景吗？

在分页器上也有问题，分页器组件的当前页数属性如果直接用`pageCount`，此时也会发生异常，比如从页数2到页数3，如果页数3加载发生异常，会发现分页器上显示的是页数3但实际数据还是页数2的，这样其实看上去已经BUG起来了。更让人难受的是此时我想再尝试加载页数3，我不得不先点一下其他页数比如4再尝试请求页数3

对于你提到的：例如请求顺序：A -> B -> C -> D，实际返回顺序：D -> C -> B -> A，其中 A 请求失败，这时回退到上一个成功的页数 B 就会显得很奇怪。

我觉得并不奇怪，因为此时数据列表确实就是显示的B的数据，你从A回退到上一个到B页数这是完全正常了，我们总是应该保证显示的数据和页数能完全对应才是我们期望的

**Comment by JOU-amjs** [comment]
抱歉，那么久才过来回复，这个问题确实是一个值得深思的好问题，之前我们也忽略了这点，所以我们内部讨论后大概有了一个我们比较认可的结果了

其实这个问题我觉得最好的方案是，当考虑了错误处理的情况下，错误处理应该从产品层面解决，就是当请求错误了，翻页模式下应该不再显示列表数据而是显示个加载错误的提示并给个重新加载的按钮，append模式也是同理，上拉加载错误的时候，列表数据不动并在最下面显示一个重新加载的按钮。这个方案现在就支持，也就是用error来判断是否显示错误提示，点击重新加载就是调用send就好。

issue里提到的两个方案：
1. page回退的方案：这是一种在usePagination里解决错误处理的问题，如果能直接在usePagination里解决错误处理那也是不错的选择，还能完善一点usePagination，只是这种方案我们觉得不够好，因为仅限于append模式，翻页模式回退会让人觉得奇怪，点了又跳回原来的页数去了，从产品方案上我觉得可能很多产品不会看好这样的方案，如果有更好的方案可以通过usePagination来解决错误处理，我们还是很愿意实现进去的
2. 加一个loadNextPage方法这个方案我觉得是忽略了翻页模式的场景，应该不会考虑这样的方案

距离提issue也有段时间了，@thisXY 你现在是怎么处理的呢？

**Comment by thisXY** [comment]
> 抱歉，那么久才过来回复，这个问题确实是一个值得深思的好问题，之前我们也忽略了这点，所以我们内部讨论后大概有了一个我们比较认可的结果了
> 
> 其实这个问题我觉得最好的方案是，当考虑了错误处理的情况下，错误处理应该从产品层面解决，就是当请求错误了，翻页模式下应该不再显示列表数据而是显示个加载错误的提示并给个重新加载的按钮，append模式也是同理，上拉加载错误的时候，列表数据不动并在最下面显示一个重新加载的按钮。这个方案现在就支持，也就是用error来判断是否显示错误提示，点击重新加载就是调用send就好。
> 
> issue里提到的两个方案：
> 
> 1. page回退的方案：这是一种在usePagination里解决错误处理的问题，如果能直接在usePagination里解决错误处理那也是不错的选择，还能完善一点usePagination，只是这种方案我们觉得不够好，因为仅限于append模式，翻页模式回退会让人觉得奇怪，点了又跳回原来的页数去了，从产品方案上我觉得可能很多产品不会看好这样的方案，如果有更好的方案可以通过usePagination来解决错误处理，我们还是很愿意实现进去的
> 2. 加一个loadNextPage方法这个方案我觉得是忽略了翻页模式的场景，应该不会考虑这样的方案
> 
> 距离提issue也有段时间了，@thisXY 你现在是怎么处理的呢？

感谢认真回复！目前我确实自己在业务里针对异常页面进行了处理，在请求发生异常时会把异常的页数收集起来，再次请求这些异常页数会用refresh尝试再次请求，其实这样的处理已经给业务的使用造成了负担，这个hooks的能力表现出来没有完全收敛

至于提到的在页面上有意地表现一个错误提示并引导用户利用一个重新加载的按钮尝试重试。。个人觉得可能在B端应用是可以接受的，但在C端应用是让用户觉得体验不太好的，因为一般我们都会有一个全局的请求异常提示(类似Toast的)，用户通过此提示是知道发生了异常的，此时大家的下意识应该是再次重复刚刚的操作，并不是用另外一种交互操作来重试

**Comment by thisXY** [comment]
其实还有些问题，比如在initialData里设置了初始数据，然后在data(response)里处理请求后的数据，会发现这个data函数会触发多次，并且有些触发的这个response是initialData设置的那个初始值，有些是当前请求后的值(这个值才是期望的)。。这个表现令人有点沮丧，可能会考虑自己实现一个usePagination

**Comment by JOU-amjs** [comment]
好的，自己根据自己的情况处理是最好的。另外，data函数是用来返回列表数据的，它不只是在响应后触发，还会在初始化时、预加载响应、以及一些refresh、insert等操作都会触发。需要处理响应数据的话可以在onSuccess中处理
