### ISSUE TITLE
[Bug Report] 文档中的快速入门例子无法执行

### ISSUE THREAD

**Issue by yllfbaobao** [alovajs/alova#45]
### 重现链接

无

### alova 版本

2.1.0

### 描述一下你遇到的问题。

`<template>
  <div v-if="loading">Loading...</div>
  <div v-else-if="error">{{ error.message }}</div>
  <span v-else>responseData: {{ data.json()}}</span>
</template>

<script setup>
import { createAlova, useRequest } from "alova"
import GlobalFetch from "alova/GlobalFetch"
import VueHook from "alova/vue"

// 1. 创建alova实例
const alovaInstance = createAlova({
  // VueHook用于创建ref状态，包括请求状态loading、响应数据data、请求错误对象error等
  statesHook: VueHook,

  // 请求适配器，推荐使用fetch请求适配器
  requestAdapter: GlobalFetch(),
})

// 2. 使用alova实例创建method并传给useRequest即可发送请求
const { loading, data, error,onSuccess } = useRequest(
  alovaInstance.Get(
    "https://www.fastmock.site/mock/d1e86a30143876254ccbb72f6cd5d279/api/addons/ddrive/freight/carInfo",
    {}
  )
)
onSuccess((event) => {
  console.log("请求成功，响应数据为:", event.data)
  console.log("本次请求的method实例为:", event.method)
  console.log("响应数据是否来自缓存:", event.fromCache)
})
</script>
`
页面显示   responseData: "[object Promise]"

### 重现步骤

无

**Comment by yllfbaobao** [comment]
const { loading, data, error } = useRequest(
  alovaInstance.Get('https://api.alovajs.org/profile', {
    params: {
      id: 1
    }
  })
); ，这一段代码，返回来的data是个Response对象， 下一步该如何使用

**Comment by yllfbaobao** [comment]
如果 createAlova 中定义了responded, 即使在onSuccess中return 了数据， useRequest也无法接收数据 ， const { loading, data, error } = useRequest  ，data会变成空

**Comment by JOU-amjs** [comment]
非常感谢你的反馈🤞🤞🤞
我自己再尝试了下，虽然运行是没问题，但使用fetch适配器会默认返回一个Response对象，实际的数据可以通过Response.json()获取到json数据，因此在你的代码中可以增加一个全局拦截器来获取到实际数据，以下是更新后的示例代码。
![image](https://user-images.githubusercontent.com/29848971/231631170-c8ae9039-d647-44ce-867a-a12323925849.png)

稍后我再把它更新到官网上，再次感谢！

**Comment by yllfbaobao** [comment]
好的， 后面那个onSuccess应该是我写的问题， 抛出了异常
