### ISSUE TITLE
[Bug]: `useRequest` 返回的 data 得到的默认类型推断不正确

### ISSUE THREAD

**Issue by daiwanxing** [alovajs/alova#450]
### Is this a Bug?

- [X] I have confirmed that I want to report a Bug

### Has this issue been reported before?

- [X] I have confirmed that this Issue has not been reported before

### Alova Version

2.21.3

### Framework

Vue

### Problem Description

![image](https://github.com/alovajs/alova/assets/37327614/78ea4a0f-5ccc-42c6-b31d-2bc4dc4b8e4c)

### Expected Behavior

期望当没有为 `method` 指定泛型时，至少能推断出 `Ref<any>` 而不是 `any`

### Reproduction Steps

1. 使用 `useRequest` stateHook
2. 访问 `data`

**Comment by MeetinaXD** [comment]
没能复现你提到的问题，可否提供更多代码？

最好提供一个复现项目在 codepen 上以更快地解决问题，谢谢。
