### ISSUE TITLE
[Bug Report] 在responsed 的 onSuccess 钩子函数内抛错无法被 onError 捕获

### ISSUE THREAD

**Issue by hushed3** [alovajs/alova#46]
### 重现链接

https://codesandbox.io/p/sandbox/vigilant-grothendieck-lr4qxj?file=%2Fsrc%2Fapi.js&selection=%5B%7B%22endColumn%22%3A42%2C%22endLineNumber%22%3A18%2C%22startColumn%22%3A42%2C%22startLineNumber%22%3A18%7D%5D

### alova 版本

2.1.0

#### onSuccess内抛错无法被onError捕获
```javascript
  responsed: {
    onSuccess: (response: any) => {
      console.log("onSuccess", response)
      throw new Error("onSuccess")
      // return (response as any).json()
    },
    onError: (response) => {
      console.log("onError", response)
      throw new Error("onError")
    }
  }
```

### 重现步骤

+ 请求接口
+ onSuccess 钩子函数 throw new Error 抛出错误
+ 未进入 onError 钩子函数

### 设备/浏览器/浏览器版本

Microsoft Edge 版本 112.0.1722.39 (正式版本) (64 位)

**Comment by JOU-amjs** [comment]
感谢你的反馈！！！🤞
这边其实是有意为之的，我们在设计的时候参考了axios的处理逻辑，onError只有在请求错误的时候才会被触发。
![image](https://user-images.githubusercontent.com/29848971/231720891-92a6564b-49fe-429c-ad91-4acab3db6823.png)

是不是有什么需求不好实现的，可以在这边提出来，一起解决。

**Comment by hushed3** [comment]
<img width="671" alt="image" src="https://user-images.githubusercontent.com/95086492/231756824-f7d090b5-9809-450d-b26c-3c76bdd96df6.png">

好的  ,我看ts声明文件内有这个注释所以就试了试

**Comment by JOU-amjs** [comment]
应该是注释错了，我在后续更正这个注释

**Comment by day-xue** [comment]
那这个错误会被usereq的 error拿到吗

**Comment by JOU-amjs** [comment]
> 那这个错误会被usereq的 error拿到吗

会的，在以下几种情况都可以在`useRequest`的error中获得：
1. 在全局的`responded`抛出错
2. 请求或传参导致的错误，又或者在meethod实例中的`transformData`抛出错误，但在全局的`onError`中未捕获
3. 全局的`onError`中抛出了错误
