### ISSUE TITLE
[Bug]: `@alova/psc`无法在多个进程中共享内存

### ISSUE THREAD

**Issue by JOU-amjs** [alovajs/alova#460]
### 这是否是一个 Bug？

- [X] 我已经确认我要报告的是一个 Bug

### 这个问题是否已经存在？

- [X] 我已经确认这个 Issue 没有被报告过

### Alova 版本

3.0.0-beta.14

### 前端框架

React

### 问题描述

启动多个进程但无法共享内存

在入口处启动同步器

https://github.com/alovajs/alova/blob/a26c8e04bb02658a2a8c3512ea4f6b9550c08673/examples/server/index.ts#L5-L11

然后在alova中设置`l1Cache`

https://github.com/alovajs/alova/blob/a26c8e04bb02658a2a8c3512ea4f6b9550c08673/examples/server/api/index.ts#L13-L23

`@alova/psc`是使用的`chore/demo`分支的代码，与next分支同步过。

### 期望的表现

可以在多个进程间同步缓存

### 复现链接

https://github.com/alovajs/alova/blob/chore/demo/examples/server

### 复现步骤

1. 到`chore/demo`分支
2. 运行`pnpm --filter=server-demo start`，将会启动3个进程同时服务
3. 访问`http://127.0.0.1:3000/psc`，并点击`Start request`开始请求接口，它会请求到不同进程。
4. 查看控制台的输出，如下截图，多个进程未同步缓存

<img width="768" alt="image" src="https://github.com/user-attachments/assets/2a476cfc-5550-4e78-b802-11fe262d3ee6">

**Comment by MeetinaXD** [comment]
fix in commit [#10da6b61](https://github.com/alovajs/alova/commit/10da6b6109a722861a9bc3701622b676249186f5)
