### ISSUE TITLE
[Bug]: Response Headers 不存在

### ISSUE THREAD

**Issue by m839336369** [alovajs/alova#461]
### 这是否是一个 Bug？

- [X] 我已经确认我要报告的是一个 Bug

### 这个问题是否已经存在？

- [X] 我已经确认这个 Issue 没有被报告过

### Alova 版本

2.20.5

### 前端框架

Vue

### 问题描述

`  inspectionAlgorithmService.Post(
    '/舌象',
    images,
    {
      transformData(data: Response) {
        data.headers.forEach(item => {
          console.log(item)
        })
        return data.json();
      },
    }
  );`
headers里没有任何值，我看到之前issue里有提及全局的可以获取到，但是需要再特定请求里拿到header信息。

### 期望的表现

输出一系列headers值

### 复现步骤

`  inspectionAlgorithmService.Post(
    '/舌象',
    images,
    {
      transformData(data: Response) {
        data.headers.forEach(item => {
          console.log(item)
        })
        return data.json();
      },
    }
  );`
执行代码

**Comment by m839336369** [comment]
补充一下，我的返回值是201，当response没有body值的时候似乎获取不到任何headers。（不确定之前的问题是否能复现)
我刚刚返回了body值以后，response headers有值了,但值内容非常少，没有Location。
![image](https://github.com/user-attachments/assets/c4ece72e-be15-4e7a-a7b4-da7d8bb64930)
![image](https://github.com/user-attachments/assets/ef3a9189-f60a-46b0-8ef2-0a1e5f11090f)

**Comment by MeetinaXD** [comment]
请尝试用 fetch API 发出相同的请求并获取 header。如果只在 alova 中出现你提到的问题，我们再讨论。

**Comment by MeetinaXD** [comment]
现在关闭这个 issue。如果有进一步的补充，欢迎随时重新打开。
