### ISSUE TITLE
[Bug]: 请问关于 `useForm` 的解构出 `form` 的类型any是正确的？

### ISSUE THREAD

**Issue by MeetinaXD** [alovajs/alova#485]
### Discussed in https://github.com/orgs/alovajs/discussions/480

<div type='discussions-op-text'>

<sup>Originally posted by **Skiyee** July 29, 2024</sup>
请问能否让解构出的 form 能不能与 initialForm 同类型？</div>

### 这是否是一个 Bug？

- [X] 我已经确认我要报告的是一个 Bug

### 这个问题是否已经存在？

- [X] 我已经确认这个 Issue 没有被报告过

### Alova 版本

3.0.2

### 前端框架

Vue

### 问题描述

指定 `initialData` 类型时，handler 传入的 `form` 参数类型包含了 `undefined`

### 期望的表现

handler 传入的 `form` 参数类型与 `initialData` 一致。

**Comment by Skiyee** [comment]
usePagination 也遇到同样问题，解构出的 data 类型是any，正常情况下是否应该是handler返回的值所对应的类型？

**Comment by Skiyee** [comment]
更新至3.0.4后
`const { form } = useForm(...)`
`const { data } = usePagination(...)`

此时二者 `form` 的类型依旧为 any

**Comment by JOU-amjs** [comment]
没有复现你的问题，以下是我随便写的示例，alova@3.0.4

alova实例
```js
export const alovaInst = createAlova({
  statesHook: VueHook,
  requestAdapter: adapterFetch(),
  responded: {
    onSuccess(response) {
      return response.json();
    }
  }
})
```

method和调用代码
```js
const testMethod = (data: any) => alovaInst.Post<{code: number, data: string[]}>('/test', data)
const { data, form, loading } = useForm(form => testMethod(form), {
  initialForm: {
    username: 'admin',
    password: '123456'
  }
});
const { data, loading } = usePagination((page, size) => testMethod({}), {
  data: (data) => data.data,
  total: (data) => data.code
})
```

`useForm`类型提示如下：
![image](https://github.com/user-attachments/assets/858be3b6-ca5a-4ef5-a2f5-6aa499eea983)

![image](https://github.com/user-attachments/assets/0d326711-ec4a-400d-8263-2a3277b81b1c)

`usePagination`类型提示如下：
![image](https://github.com/user-attachments/assets/d9792eee-5fb6-487f-bf53-a1c8b8fa6896)


如果还有问题，请贴出详细的代码出来，或者提供可查看的示例

**Comment by Skiyee** [comment]
https://github.com/Skiyee/vue-test/blob/main/src/App.vue

**Comment by BenKids** [comment]
封装request时使用了token认真拦截器，需要给createClientTokenAuthentication传入typeof VueHook类型
https://alova.js.org/zh-CN/tutorial/client/strategy/token-authentication#typescript
