### ISSUE TITLE
[Bug]: hook not refreshing with PreactJS

### ISSUE THREAD

**Issue by proddy** [alovajs/alova#492]
### Is this a Bug?

- [X] I have confirmed that I want to report a Bug

### Has this issue been reported before?

- [ ] I have confirmed that this Issue has not been reported before

### Alova Version

3.0.5

### Framework

Other Framework

### Problem Description

useRequest() not re-rendering page using `preactJS` framework. 

I know PreactJS is not officially supported but it is 100% compatible with ReactJS and works well with version 2.x of AlovaJS.

I would be great if you could resolve this little issue.

This is the same issue I reported in https://github.com/alovajs/alova/issues/489

### Reproduction Link

https://stackblitz.com/~/github.com/proddy/alova3-preact?file=vite.config.ts

### Reproduction Steps

Go to https://stackblitz.com/~/github.com/proddy/alova3-preact?file=vite.config.ts and change the `react` for `preact` and you'll see the `useRequest()` successfully fetches the data, but does not refresh that page.

### Additional Information

Not technically a bug, as Preact is not officially supported by AlovaJS yet - but you're close! https://alova.js.org/resource/framework/preact

See also https://github.com/alovajs/alova/issues/489

**Comment by JOU-amjs** [comment]
Actually we didn't test alova in preact. so it can not be ensured to work. we will check it recently

**Comment by proddy** [comment]
It would be great if you could get it working as it did with version 2.0, and support AlovaJS's goal of "Run in any JS environment". It may be something really simple on how children in the DOM are refreshed. The example code I sent should be easy for your team to pinpoint the issue I'm hoping.

I'm building an open-source framework for Espressif's MCUs that uses AlovaJS as the core integration between the backend and the Web and API frontend. I replaced all the Axios and NextJS to use Alova when I first saw it.

**Comment by proddy** [comment]
Hi @JOU-amjs and @MeetinaXD - any luck finding a solution to this? It's the final step to upgrade my framework to Alova version 3!

**Comment by JOU-amjs** [comment]
I have found the problem. Look the following codes

https://github.com/alovajs/alova/blob/5e26e47d6e819783f6d49a3d72e431111c6f32b8/packages/client/src/statesHook/react.ts#L20-L25

react hook will assign new value to `state[0]`, it's a compatible way to update react state synchronously. but in preact it will compare the old value and new value before updating it. so that the state never be updated.

let me think how to fix it.

**Comment by JOU-amjs** [comment]
@proddy upgrade alova to 3.0.6, your demo is working.

**Comment by proddy** [comment]
that's amazing and very kind of you, many thanks @JOU-amjs
