### ISSUE TITLE
[Bug]: `vue` 下 `useRequest` 返回值中的 `loading` 类型错误

### ISSUE THREAD

**Issue by Nakus0426** [alovajs/alova#493]
### 这是否是一个 Bug？

- [X] 我已经确认我要报告的是一个 Bug

### 这个问题是否已经存在？

- [X] 我已经确认这个 Issue 没有被报告过

### Alova 版本

3.0.5

### 前端框架

Vue

### 问题描述

- 在 `createAlova` 时，`statesHook` 使用 `VueHook`，再加上 `createClientTokenAuthentication` ，`useRequest` 返回的 `loading` 的类型会变为 `any`

![image](https://github.com/user-attachments/assets/90c1a677-721b-42a9-887a-0c2cc6f65138)

- 不使用 `createClientTokenAuthentication` 时 `loading` 的类型为 `Ref`

![image](https://github.com/user-attachments/assets/029824a0-3bd8-494a-9457-a24e2e8fa048)

### 期望的表现

在使用 `createClientTokenAuthentication` 后 `loading` 的类型与不使用时保持一致

### 复现链接

[复现链接](https://codesandbox.io/p/sandbox/alova-bug-rx35ph)

### 复现步骤

在 `createAlova` 时，`statesHook` 使用 `VueHook`，再加上 `createClientTokenAuthentication`

### 系统信息

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (16) x64 AMD Ryzen 7 8845HS w/ Radeon 780M Graphics
    Memory: 8.86 GB / 31.31 GB
  Binaries:
    Node: 18.20.3 - D:\Program Files\nodejs\node.EXE
    npm: 10.7.0 - D:\Program Files\nodejs\npm.CMD
    pnpm: 9.5.0 - D:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Edge: Chromium (126.0.2592.113)
    Internet Explorer: 11.0.22621.3527
  npmPackages:
    alova: ^3.0.5 => 3.0.5
    vue: ^3.4.26 => 3.4.27
```

**Comment by MeetinaXD** [comment]
感谢反馈，已复现。我们尽快处理

**Comment by 3m1n3nc3** [comment]
I'm also experiencing this issue

**Comment by MeetinaXD** [comment]
For anyone experiencing this problem:

a temporary solution is mark the return type of `onResponseRefreshToken` as `any`

like this:
```typescript
const alovaInst = createAlova({
  // ...
  responded: onResponseRefreshToken() as any
})
```

**Comment by MeetinaXD** [comment]
fixed in #497. please upgrade alova to the latest version. @Nakus0426  @3m1n3nc3
