### ISSUE TITLE
[Bug Report] uni-app支付宝小程序环境

### ISSUE THREAD

**Issue by ssw1992** [alovajs/alova#50]
### Reproduction Link

empty

### alova Version

2.1.1

### Describe the Bug

![image](https://user-images.githubusercontent.com/24841397/232938261-952526dd-99d3-42f1-aca3-4e7b31f8a96f.png)
![image](https://user-images.githubusercontent.com/24841397/232938306-ce8dd6bd-a4be-4ea2-850d-cb94dafd46ca.png)
![image](https://user-images.githubusercontent.com/24841397/232938348-fbddb81b-6617-4e18-8f0f-dbf33217a09f.png)
![image](https://user-images.githubusercontent.com/24841397/232938524-aba49611-167e-4ae6-8538-0fdea2321882.png)
我尝试改源码，只需要把self函数更名就可以解决
支付宝小程序环境，因为把self设置成readonly，所以编译不通过，微信小程序没有这种设置，所有没这个问题

### Reproduce Steps

初始化项目
npx degit dcloudio/uni-preset-vue#vite-ts my-vue3-project

进入项目安装依赖
npm i

安装alova
npm install alova @alova/adapter-uniapp --save

在src/pages/index/index.vue下编写代码
<script setup lang="ts">
import { createAlova } from "alova";
import type { Method } from "alova";
import AdapterUniapp from "@alova/adapter-uniapp";
 createAlova({
  ...AdapterUniapp(),
});
</script>
<template>
  <view class="content">
    1111
  </view>
</template>
运行代码 npm run dev:mp-alipay
打开支付宝小程序工具，打开项目目录dist\dev\mp-alipay，运行小程序就会出现这个问题

### Device / Browser / Browser Version

支付宝小程序

**Comment by JOU-amjs** [comment]
兄弟，这个问题真的发现的真的很厉害，我稍后发布一个版本解决这个问题。
非常感谢你的反馈哦！🤞😁😁

**Comment by JOU-amjs** [comment]
已发布2.1.2，已将`self`修改为了`_self`来解决你的问题。
```javascript
export const _self = <T>(arg: T) => arg;
```
