### ISSUE TITLE
[Bug]: useRequest  updateState 更新缓存 useRequest data 状态未更新

### ISSUE THREAD

**Issue by littlezo** [alovajs/alova#510]
### Is this a Bug?

- [X] I have confirmed that I want to report a Bug

### Has this issue been reported before?

- [X] I have confirmed that this Issue has not been reported before

### Alova Version

3.0

### Framework

Vue

### Problem Description

useRequest  updateState 更新缓存 useRequest data 状态未更新

### Reproduction Steps

useRequest  updateState 更新缓存 useRequest data 状态未更新

**Comment by MeetinaXD** [comment]
请提供可复现的代码片段和复现步骤，否则我们将直接关闭这个 issue。

**Comment by JOU-amjs** [comment]
这个我这里复现了，我这里改下
