### ISSUE TITLE
[Bug]: 不同浏览器表现不同

### ISSUE THREAD

**Issue by blkcor** [alovajs/alova#526]
### 这是否是一个 Bug？

- [X] 我已经确认我要报告的是一个 Bug

### 这个问题是否已经存在？

- [X] 我已经确认这个 Issue 没有被报告过

### Alova 版本

3.0.9

### 前端框架

React

### 问题描述

# 问题描述
我一直使用chrome开发，今天上午请求是正常的，但是随着使用一段时间（浏览器窗口一直没关），发现菜单栏渲染不出来了，打开浏览器控制台查看请求如下：
![CleanShot 2024-08-30 at 21 35 49](https://github.com/user-attachments/assets/87e7cd8c-4af9-4757-b80a-4ef7666ab24d)
注意看这个请求：
![CleanShot 2024-08-30 at 21 36 18](https://github.com/user-attachments/assets/5dc33612-b197-4c30-b131-1177a6d15f4c)
似乎是alova对这个请求进行了缓存。
我尝试按照文档将所有的缓存给ban掉了，并重启了项目 + 清理了浏览器的缓存：
![CleanShot 2024-08-30 at 21 37 53](https://github.com/user-attachments/assets/15d447e0-ee58-4295-bf2b-46173e4aff3f)
问题仍然存在。
于是我尝试换成arc浏览器，请求突然正常了：
![CleanShot 2024-08-30 at 21 39 10](https://github.com/user-attachments/assets/211d661d-2800-436f-a850-96717a9bb05b)
没有对应的304那个请求。

# 环境
开发环境：macos m1 pro
alova版本：3.0.9
前端框架：react
node版本：v19.0.0
pnpm版本：9.7.0

### 复现步骤

暂无

**Comment by MeetinaXD** [comment]
请阅读 304 状态说明：[304 Not Modified](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/304)
