### ISSUE TITLE
[Bug]: 使用useSSE会丢失实例化alova时自定义的header

### ISSUE THREAD

**Issue by SuperGness** [alovajs/alova#534]
### 这是否是一个 Bug？

- [X] 我已经确认我要报告的是一个 Bug

### 这个问题是否已经存在？

- [X] 我已经确认这个 Issue 没有被报告过

### Alova 版本

3.0.12

### 前端框架

Vue

### 问题描述

实例化alova时在beforeRequest中增加headers.Authorization， 使用useSSE发送请求会丢失自定义的header

### 复现步骤

使用useSSE发送sse请求

**Comment by MeetinaXD** [comment]
你好，目前`useSSE` 使用 `EventSource` 实现，浏览器默认的 `EventSource` API 对传入的参数有限制，详见：

[EventSource Parameters](https://developer.mozilla.org/en-US/docs/Web/API/EventSource/EventSource#parameters)

目前有一些第三方实现可以做到自定义 header，不过它们是基于 fetch 实现的。如：[Azure/fetch-event-source](https://github.com/Azure/fetch-event-source)

也许我们应该在文档中提到这点。

**Comment by hzlzsm** [comment]
> 你好，目前`useSSE` 使用 `EventSource` 实现，浏览器默认的 `EventSource` API 对传入的参数有限制，详见：
> 
> [EventSource Parameters](https://developer.mozilla.org/en-US/docs/Web/API/EventSource/EventSource#parameters)
> 
> 目前有一些第三方实现可以做到自定义 header，不过它们是基于 fetch 实现的。如：[Azure/fetch-event-source](https://github.com/Azure/fetch-event-source)
> 
> 也许我们应该在文档中提到这点。

为什么3.5.1版本的alova已经用fetch实现了，在beforeRequest中的设置还是会丢失？
