### ISSUE TITLE
[Bug]: npm run build时报错error TS1192: Module '"D:/demo/node_modules/alova/typings/fetch"' has no default export.

### ISSUE THREAD

**Issue by yeqinghz** [alovajs/alova#539]
### 这是否是一个 Bug？

- [X] 我已经确认我要报告的是一个 Bug

### 这个问题是否已经存在？

- [X] 我已经确认这个 Issue 没有被报告过

### Alova 版本

3.0.16

### 前端框架

Vue

### 问题描述

最简单环境下，即npm init vite@latest后仅安装了 alova   在src/api/index.ts 添加以下代码
import { createAlova } from 'alova';
import adapterFetch from 'alova/fetch';

const alovaInstance = createAlova({
  requestAdapter: adapterFetch()
});

然后npm run build即报如上错误

### 期望的表现

能正常生成dist

### 复现步骤

已提交demo文件夹

### 补充说明

vite 版本：5.4.1

**Comment by JOU-amjs** [comment]
目测是typescript@5.6的bug，降级到5.5及以下解决

**Comment by mamboer** [comment]
这个应该不是 typescript 5.6 的问题，实测在`typings/fetch.d.ts`里面，
把
```ts
export = adapterFetch;
```

改成
```ts
export default adapterFetch;
```

就没有报错了。

@JOU-amjs

**Comment by JOU-amjs** [comment]
@mamboer 经测试typescript@5.6会报错，但之前的版本正常

**Comment by ssw1992** [comment]
@JOU-amjs 大哥，我5.5的版本打包也报这个，跟楼上说的一样，打包的时候还是得改成export default，不能写写成export =

**Comment by JOU-amjs** [comment]
@ssw1992 两步检查法
1. 是否使用的vscode编辑器的ts版本
2. 是否node_modules里依然为更高版本

**Comment by pawover** [comment]
@JOU-amjs
![image](https://github.com/user-attachments/assets/1a70a51c-09ea-4ffc-ab7e-c341734dd7e6)

![image](https://github.com/user-attachments/assets/22898384-e46c-4cb2-b690-191a6999e251)

希望可以尽早适配下，目前使用 pnpm patch 临时手动修补

**Comment by JOU-amjs** [comment]
已修复，升级到3.0.19
