### ISSUE TITLE
[Feature Request] alova need to support Angular and qwik

### ISSUE THREAD

**Issue by st-clair-clarke** [alovajs/alova#54]
### In what situation do you need this function to solve the problem?

Add alova scene for the following:
1. Angular ([https://angular.io/](https://angular.io/))
2. qwik ([https://qwik.builder.io/](https://qwik.builder.io/))

### What do you expect the API to look like?

Uncertain

**Comment by JOU-amjs** [comment]
Hey, there!
Thinks for your issue first.
but unfortunately, as I known, Angular is not compatible with alova. and as for qwik, we currently have no plan to support it. which I so sorry abot it.😂😂😂
