### ISSUE TITLE
[Bug]: The initial value of loading is false

### ISSUE THREAD

**Issue by voyageh** [alovajs/alova#543]
### Is this a Bug?

- [X] I have confirmed that I want to report a Bug

### Has this issue been reported before?

- [X] I have confirmed that this Issue has not been reported before

### Alova Version

3.0.16

### Framework

React

### Problem Description

Most of the pages load and request the interface, which is not very friendly.

### Reproduction Steps

loading init false

**Comment by voyageh** [comment]
I think the initial value of loading should follow immediate

**Comment by voyageh** [comment]
usePagination hook

**Comment by JOU-amjs** [comment]
@voyageh resolve to upgrage to 3.1.0
