### ISSUE TITLE
[Bug]: 照着官网的例子，没有执行成功，版本:3.0.16

### ISSUE THREAD

**Issue by ephemeral98** [alovajs/alova#544]
### 这是否是一个 Bug？

- [X] 我已经确认我要报告的是一个 Bug

### 这个问题是否已经存在？

- [X] 我已经确认这个 Issue 没有被报告过

### Alova 版本

3.0.16

### 前端框架

Vue

### 问题描述

import { createAlova } from 'alova';
import adapterFetch from 'alova/fetch';

const alovaInstance = createAlova({
  requestAdapter: adapterFetch()
});

const response = alovaInstance
  .Post('https://alovajs.dev/posts', {
    title: 'foo',
    body: 'bar',
    userId: 1
  })
  .then(response => response.json());

请求没有发送出去，用的ts，response类型也报unknown

### 复现步骤

直接请求，没有走useRequest的，没有成功执行

**Comment by MeetinaXD** [comment]
请看文档使用

https://alova.js.org/zh-CN/tutorial/getting-started/basic/combine-framework#自动管理请求状态
