### ISSUE TITLE
[Feature Request] 建议 useRequest 参数和 ahooks 对齐

### ISSUE THREAD

**Issue by PineSongCN** [alovajs/alova#55]
### 你在什么情况下，需要这个功能解决什么问题？

如果 useRequest 是参考的 ahooks 里的useRequest做的话，似乎没必要把相关的参数名给调整了，统一的话，更好一些。

### 你期望的 API 是什么样子的？

const { loading, run, runAsync } = useRequest(service, {
  manual: true
});

**Comment by JOU-amjs** [comment]
这其实是一个很好的建议，可以让大家使用的时候更熟悉，在这个理念下，`alova`的`method`实例创建的设计就是参考了`axios`的请求发送的方式。

不过alova没有参考`ahooks`的设计，可能是不谋而合吧，我会好好考虑这点，可以的话在下一个大版本中尝试改为更加熟悉的使用方式。

感谢你的反馈哦！😁😎

**Comment by PineSongCN** [comment]
> 这其实是一个很好的建议，可以让大家使用的时候更熟悉，在这个理念下，`alova`的`method`实例创建的设计就是参考了`axios`的请求发送的方式。
> 
> 不过alova没有参考`ahooks`的设计，可能是不谋而合吧，我会好好考虑这点，可以的话在下一个大版本中尝试改为更加熟悉的使用方式。
> 
> 感谢你的反馈哦！😁😎

了解👍🏻

**Comment by PineSongCN** [comment]
> > 这其实是一个很好的建议，可以让大家使用的时候更熟悉，在这个理念下，`alova`的`method`实例创建的设计就是参考了`axios`的请求发送的方式。
> > 不过alova没有参考`ahooks`的设计，可能是不谋而合吧，我会好好考虑这点，可以的话在下一个大版本中尝试改为更加熟悉的使用方式。
> > 感谢你的反馈哦！😁😎
> 
> 了解👍🏻

如果这个库主要是面向vue的话，问题不大，ahooks是react的库，虽然也有人做了vue版，不过用的似乎不多。

**Comment by PineSongCN** [comment]
> 这其实是一个很好的建议，可以让大家使用的时候更熟悉，在这个理念下，`alova`的`method`实例创建的设计就是参考了`axios`的请求发送的方式。
> 
> 不过alova没有参考`ahooks`的设计，可能是不谋而合吧，我会好好考虑这点，可以的话在下一个大版本中尝试改为更加熟悉的使用方式。
> 
> 感谢你的反馈哦！😁😎

如果这个库更多是面向vue的话，问题不大，ahooks是react的库，虽然也有人做了vue版，不过用的似乎不多。
