### ISSUE TITLE
[Feature Request] 请问如何在onSuccess/onError内重新发起当前的请求？

### ISSUE THREAD

**Issue by PineSongCN** [alovajs/alova#56]
### 你在什么情况下，需要这个功能解决什么问题？

比如登录的acess_token过期的情况下，通过refresh_token刷新access_token并重新发起请求返回数据

### 你期望的 API 是什么样子的？

import { refreshToken } from 'token'
const alovaInstance = createAlova({
    baseURL: BASE_URL,
    ...AdapterUniapp({}),
    timeout: 5000,
    beforeRequest: (method) => {
        const authStore = useAuthStore();
        method.config.headers = assign(method.config.headers, HEADER, authStore.getAuthorization);
    },
    responsed: {
        /**
         * 请求成功的拦截器
         * 第二个参数为当前请求的method实例，你可以用它同步请求前后的配置信息
         * @param response
         * @param method
         */
        onSuccess: async (response, method, reload) => {
            const { statusCode, data: rawData } = response;
            const { code, message, data } = rawData as API;
            if (statusCode === 200) {
                if (code === ResultEnum.SUCCESS) {
                    return data;
                } else  if (code === ResultEnum.TOKEN_EXPIRED) {
                    await refreshToken();
                    const resData= await reload();
                    return reData;
                } 
                message && Toast(message);
                return Promise.reject(rawData);
            }
            checkStatus(statusCode, message || '');
            return Promise.reject(rawData);
        },
    },
});

**Comment by JOU-amjs** [comment]
你应该是需要在token过期的时候再次自动授权，然后重新获取数据是吗？
如果是这样的话，你可以尝试在onSuccess中刷新token后，使用`method`对象再次发送请求，按下面这样再次发起请求：

```javascript
...
async onSuccess(response, method) {
  // ...
  else if (code === ResultEnum.TOKEN_EXPIRED) {
    await refreshToken();
    const resData= await method.send();
    return resData;
  }
}
...
```

**Comment by PineSongCN** [comment]
> 你应该是需要在token过期的时候再次自动授权，然后重新获取数据是吗？ 如果是这样的话，你可以尝试在onSuccess中刷新token后，使用`method`对象再次发送请求，按下面这样再次发起请求：
> 
> ```js
> ...
> async onSuccess(response, method) {
>   // ...
>   else if (code === ResultEnum.TOKEN_EXPIRED) {
>     await refreshToken();
>     const resData= await method.send();
>     return resData;
>   }
> }
> ...
> ```
> 
> 这样的话就可以再次执行当前请求了

谢谢，如果method就是请求的实例的话，是我文档没看仔细。

**Comment by JOU-amjs** [comment]
是的，method就是通过比如`alovaInst.Get('/...')`创建的method实例
