### ISSUE TITLE
[Bug]: 官方文档例子 ts 报错

### ISSUE THREAD

**Issue by Mi-liu** [alovajs/alova#565]
### 这是否是一个 Bug？

- [X] 我已经确认我要报告的是一个 Bug

### 这个问题是否已经存在？

- [X] 我已经确认这个 Issue 没有被报告过

### Alova 版本

3.1.0

### 前端框架

Vue

### 问题描述

照着文档例子实现效果， 出现ts类型错误。文档是否应该主动声明其 ts类型？
![image](https://github.com/user-attachments/assets/a9bc0922-9f47-4097-8486-bf0d59e7efcd)
`js
const response = alovaInstance
  .Post('https://alovajs.dev/posts', {
    title: 'foo',
    body: 'bar',
    userId: 1
  })
  .then(response => response.json());
`

### 复现步骤

`const response = alovaInstance
  .Post('https://alovajs.dev/posts', {
    title: 'foo',
    body: 'bar',
    userId: 1
  })
  .then(response => response.json());`

**Comment by MeetinaXD** [comment]
感谢反馈。这个例子写的不太好，虽然可以这么用但是类型声明不支持。

我们已经修改了文档，可以参考下修改后的文档
