### ISSUE TITLE
[Bug]: usePagination解构出来的remove函数

### ISSUE THREAD

**Issue by flowerwOw0316** [alovajs/alova#566]
### Is this a Bug?

- [X] I have confirmed that I want to report a Bug

### Has this issue been reported before?

- [X] I have confirmed that this Issue has not been reported before

### Alova Version

3.1.0

### Framework

Vue

### Problem Description

在append模式下，场景是手机列表滚动追加数据，假设现在的页数是2，那么remove就只能去删第2页的数据，我想删第1页的无论传index还是传item都删不掉。

### Expected Behavior

用了remove函数，按照文档的传索引或者传列表项都应该要能删掉和更新列表状态。

### Reproduction Steps

1：创建一个假数据的列表，2页就行
2：使用usePagination的remove函数尝试删第一页的数据

**Comment by MeetinaXD** [comment]
猜测是没有关闭自动预加载功能。

https://alova.js.org/zh-CN/tutorial/client/strategy/use-pagination#预加载相邻页数据

**Comment by flowerwOw0316** [comment]
刚根据大佬你说的关闭预加载参数，全局缓存也关了还是不行哦，remove不能跨页删，只能删当前加载到哪一页的就是哪一页的能删，应该是bug了。

**Comment by JOU-amjs** [comment]
@flowerwOw0316 刚测试没问题的，打开[示例](https://alova.js.org/examples)，进去后左侧选择`Load More List`，没有出现你说的情况，右上角github图标点击可以看源码

**Comment by flowerwOw0316** [comment]
排查一下午，最后是自己的问题，感觉大佬耐心解答。
