### ISSUE TITLE
文档示例 “延迟更新 loading” 无效

### ISSUE THREAD

**Issue by LiMao00** [alovajs/alova#571]
### 这是否是一个 Bug？

- [X] 我已经确认我要报告的是一个 Bug

### 这个问题是否已经存在？

- [X] 我已经确认这个 Issue 没有被报告过

### Alova 版本

3.1.1

### 前端框架

React

### 问题描述

![image](https://github.com/user-attachments/assets/ef2ff8bf-7bb9-4aeb-90ca-b533c4bc5411)
并不能延时执行，可以更新文档

### 复现步骤

如图

**Comment by MeetinaXD** [comment]
我在 `alova@3.1.1` 使用文档示例进行了测试，没能复现你提到的问题。

<img width="585" alt="image" src="https://github.com/user-attachments/assets/eb188e7c-32fc-4f3a-a07b-707013b835e9">

控制台输出：

<img width="346" alt="image" src="https://github.com/user-attachments/assets/f8ffcbd0-9327-43d1-9ff2-c10c1428cf87">

显然 Loading 产生了预期的 1s 延迟。

如果确信一个 bug，请按照 issue 模板的指引，提供一个最小可复现示例。

**Comment by MeetinaXD** [comment]
由于较长时间没有活动，因此关闭这个 issue。如果有问题，请随时 re-open。
