### ISSUE TITLE
[Bug]: get请求参数没编码导致异常

### ISSUE THREAD

**Issue by luojin315** [alovajs/alova#583]
### 这是否是一个 Bug？

- [X] 我已经确认我要报告的是一个 Bug

### 这个问题是否已经存在？

- [X] 我已经确认这个 Issue 没有被报告过

### Alova 版本

3.1.1

### 前端框架

Vue

### 问题描述

https://github.com/alovajs/alova/blob/a314f50c99a802e343412dbf73e244aa26b2385d/packages/shared/src/function.ts#L386
请教一下为什么不encodeURIComponent 参数，是有其他方式添加这一步的处理吗？
我现在遇到的问题是get请求，参数中存在特殊符号会有问题

### 复现步骤

import {createAlova, Method} from 'alova';
import fetchAdapter from 'alova/fetch';
import VueHook from 'alova/vue';

const defaultConfig = {
    // 请求适配器，这里我们使用fetch请求适配器
    requestAdapter: fetchAdapter(),
    // 在vue项目下引入VueHook，它可以帮我们用vue的ref函数创建请求相关的，可以被alova管理的状态
    statesHook: VueHook,
    baseURL: '',
    timeout: 30 * 1000,
};

export default class AlovaRequest {
    constructor(options = {}) {
        this.alovaInstance = this.create(options);
    }

    /**
     * 创建一个新的Alova实例
     *
     * @param config 配置对象，用于自定义Alova实例的行为
     * @returns 返回创建的Alova实例
     */
    create(config) {
        const alovaConfig = {
            ...defaultConfig,
            ...config,
        };
        return createAlova(alovaConfig);
    }

    request(method, url, params = null, config = {}) {
        // 根据请求方法（GET或POST等）设置请求配置
        const requestConfig = method === 'GET' ? {params, ...config} : config;

        // 创建请求方法实例
        const requestMethod = new Method(
            method.toUpperCase(),
            this.alovaInstance,
            url,
            requestConfig,
            method !== 'GET' ? params : undefined
        );

        // 额外的配置项
        Object.getOwnPropertyNames(config).forEach(key => requestMethod[key] = config[key]);
        return requestMethod;
    }

    /**
     * 通过GET请求获取数据
     *
     * @param url 请求的URL地址
     * @param params 请求的参数，默认为null
     * @param config 请求的配置项，默认为空对象{}
     * @returns 返回Method实例，用于发送GET请求
     */
    get(url, params, config) {
        return this.request('GET', url, params, config);
    }

    /**
     * 发送POST请求
     *
     * @param url 请求的URL地址
     * @param params 请求的参数，默认为null
     * @param config 请求的配置信息，默认为空对象
     * @returns 返回Method实例，用于处理请求结果
     */
    post(url, params, config) {
        return this.request('POST', url, params, config);
    }

    /**
     * 向指定URL发送PUT请求
     *
     * @param url 目标URL
     * @param params 请求参数，默认为null
     * @param config 请求配置，默认为空对象{}
     * @returns 返回一个Method实例，表示该PUT请求
     */
    put(url, params, config) {
        return this.request('PUT', url, params, config);
    }

    /**
     * 删除指定资源
     *
     * @param url 要删除资源的URL
     * @param params 可选的请求参数，默认为null
     * @param config 可选的配置对象，默认为空对象
     * @returns 返回Method对象，用于执行HTTP DELETE请求
     */
    delete(url, params, config) {
        return this.request('DELETE', url, params, config);
    }
}

**Comment by luojin315** [comment]
目前我的解决方案是自己encodeURIComponent 参数
`const requestConfig = method === 'GET' ? {params: cloneAndEncodeParams(params), ...config} : config;`

**Comment by MeetinaXD** [comment]
这个需求建议在请求拦截器中进行处理，最好不要手动在每个请求中处理 config。

## 为什么不对参数进行编码处理

可以视作为一个实现疏忽，但我们不打算处理这个问题。alova 的目标不是成为 axios 那样的请求库并且取代 axios，在这个前提下，一些实现细节我们不想追求与 axios 一致。不然就会出现很多类似 ”xxx 功能 axios 有，为什么 alova 不做？“ 的问题。

也是出于以上的原因，对于追求 axios 使用体验的用户，建议使用 axios 适配器。而不需要在两个请求库之间选择一个。

**Comment by luojin315** [comment]
我按照你的建议，将功能放入了拦截器中。我理解在拦截器或 config 中处理 params 都能达到相同的效果，但是否将逻辑放在拦截器中更符合 alova 的设计理念？这样处理是否有其他优势？还是说在 config 中处理 params 可能存在潜在的问题？

> 这个需求建议在请求拦截器中进行处理，最好不要手动在每个请求中处理 config。
> 
> ## 为什么不对参数进行编码处理
> 可以视作为一个实现疏忽，但我们不打算处理这个问题。alova 的目标不是成为 axios 那样的请求库并且取代 axios，在这个前提下，一些实现细节我们不想追求与 axios 一致。不然就会出现很多类似 ”xxx 功能 axios 有，为什么 alova 不做？“ 的问题。
> 
> 也是出于以上的原因，对于追求 axios 使用体验的用户，建议使用 axios 适配器。而不需要在两个请求库之间选择一个。

**Comment by MeetinaXD** [comment]
这是惯用方式。在拦截器而非请求时对 config 进行处理可以减少重复的代码。在拦截器中处理可以得到更大的灵活度，你可以随时对所有请求的行为作出修改。

从设计角度来说，这样语义也更明确。
