### ISSUE TITLE
[Bug]: uniapp适配器@alova/shared问题

### ISSUE THREAD

**Issue by Lazy-Hand** [alovajs/alova#584]
### 这是否是一个 Bug？

- [X] 我已经确认我要报告的是一个 Bug

### 这个问题是否已经存在？

- [X] 我已经确认这个 Issue 没有被报告过

### Alova 版本

3.0

### 前端框架

Vue

### 问题描述

X [ERROR] Could not resolve "@alova/shared/function"

    node_modules/alova/dist/stateshook/vue.esm.js:8:37:
      8 │ import { createSyncOnceRunner } from '@alova/shared/function';
        ╵                                      ~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "@alova/shared/function" as external to exclude it from the bundle, which
  will remove this error and leave the unresolved path in the bundle.

X [ERROR] Could not resolve "@alova/shared/function"

    node_modules/@alova/adapter-uniapp/dist/alova-adapter-uniapp.esm.js:8:36:
      8 │ import { isPlainObject, noop } from '@alova/shared/function';
        ╵                                     ~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "@alova/shared/function" as external to exclude it from the bundle, which
  will remove this error and leave the unresolved path in the bundle.

X [ERROR] Could not resolve "@alova/shared/function"

    node_modules/alova/dist/alova.esm.js:8:274:
      8 │ ...etLocalCacheConfigParam, isFn, getConfig, getOptions, isPlainObject, sloughFunction, noop, $self, isSpecialRequestBody, getContextOptions, key, isString } from '@alova/shared/function'; 
        ╵                                                                                                                                                                    ~~~~~~~~~~~~~~~~~~~~~~~~  

  You can mark the path "@alova/shared/function" as external to exclude it from the bundle, which
  will remove this error and leave the unresolved path in the bundle.

X [ERROR] Could not resolve "@alova/shared/function"

    node_modules/alova/dist/clienthook/index.esm.js:8:402:
      8 │ ...t, walkObject, uuid as uuid$1, globalToString, delayWithBackoff, isString, getConfig, createAsyncQueue, getLocalCacheConfigParam, usePromise, getOptions } from '@alova/shared/function'; 
        ╵                                                                                                                                                                    ~~~~~~~~~~~~~~~~~~~~~~~~  

  You can mark the path "@alova/shared/function" as external to exclude it from the bundle, which
  will remove this error and leave the unresolved path in the bundle.

X [ERROR] Could not resolve "@alova/shared/vars"

    node_modules/alova/dist/stateshook/vue.esm.js:9:49:
      9 │ import { setTimeoutFn, forEach, trueValue } from '@alova/shared/vars';
        ╵                                                  ~~~~~~~~~~~~~~~~~~~~

  You can mark the path "@alova/shared/vars" as external to exclude it from the bundle, which will
  remove this error and leave the unresolved path in the bundle.

X [ERROR] Could not resolve "@alova/shared/vars"

    node_modules/@alova/adapter-uniapp/dist/alova-adapter-uniapp.esm.js:9:20:
      9 │ import { len } from '@alova/shared/vars';
        ╵                     ~~~~~~~~~~~~~~~~~~~~

  You can mark the path "@alova/shared/vars" as external to exclude it from the bundle, which will
  remove this error and leave the unresolved path in the bundle.

X [ERROR] Could not resolve "@alova/shared/vars"

    node_modules/alova/dist/alova.esm.js:9:321:
      9 │ ...jectKeys, PromiseCls, deleteAttr, isArray, MEMORY, promiseThen, trueValue, falseValue, promiseFinally, promiseReject, promiseCatch, JSONStringify, JSONParse } from '@alova/shared/vars'; 
        ╵                                                                                                                                                                        ~~~~~~~~~~~~~~~~~~~~  

  You can mark the path "@alova/shared/vars" as external to exclude it from the bundle, which will
  remove this error and leave the unresolved path in the bundle.

X [ERROR] Could not resolve "@alova/shared/vars"

    node_modules/alova/dist/clienthook/index.esm.js:9:415:
      9 │ ...s, ObjectCls, valueObject, defineProperty, includes, RegExpCls, regexpTest, shift, mapItem as mapItem$1, MEMORY, objectValues, promiseReject, promiseFinally } from '@alova/shared/vars'; 
        ╵                                                                                                                                                                        ~~~~~~~~~~~~~~~~~~~~  

  You can mark the path "@alova/shared/vars" as external to exclude it from the bundle, which will
  remove this error and leave the unresolved path in the bundle.

X [ERROR] Could not resolve "@alova/shared/assert"

    node_modules/alova/dist/alova.esm.js:10:29:
      10 │ import { createAssert } from '@alova/shared/assert';
         ╵                              ~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "@alova/shared/assert" as external to exclude it from the bundle, which will
  remove this error and leave the unresolved path in the bundle.

X [ERROR] Could not resolve "@alova/shared/assert"

    node_modules/alova/dist/clienthook/index.esm.js:10:41:
      10 │ import { createAssert, AlovaError } from '@alova/shared/assert';
         ╵                                          ~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "@alova/shared/assert" as external to exclude it from the bundle, which will
  remove this error and leave the unresolved path in the bundle.

10:42:04 [vite] Build failed with 10 errors:
node_modules/@alova/adapter-uniapp/dist/alova-adapter-uniapp.esm.js:8:36: ERROR: Could not resolve "@alova/shared/function"
node_modules/@alova/adapter-uniapp/dist/alova-adapter-uniapp.esm.js:9:20: ERROR: Could not resolve "@alova/shared/vars"
node_modules/alova/dist/alova.esm.js:8:274: ERROR: Could not resolve "@alova/shared/function"
node_modules/alova/dist/alova.esm.js:9:321: ERROR: Could not resolve "@alova/shared/vars"
node_modules/alova/dist/alova.esm.js:10:29: ERROR: Could not resolve "@alova/shared/assert"

### 复现步骤

`createAlova({
  ...AdapterUniapp()
})`

**Comment by JOU-amjs** [comment]
pnpm下使用uniapp，需要额外安装@alova/shared

**Comment by Lazy-Hand** [comment]
已经安装了的

**Comment by JOU-amjs** [comment]
如果你安装的@alova/shared是1.1.0，那还需要将alova升级到3.2.0一下

**Comment by Lazy-Hand** [comment]
我知道原因了，是因为我后面才单独安装的@alova/shared，pnpm-lock.yaml的问题，删除重新安装就可以了
