### ISSUE TITLE
[Bug]: 修改`data`引用值时缓存数据也会被修改

### ISSUE THREAD

**Issue by H2z2H** [alovajs/alova#588]
### 这是否是一个 Bug？

- [X] 我已经确认我要报告的是一个 Bug

### 这个问题是否已经存在？

- [X] 我已经确认这个 Issue 没有被报告过

### Alova 版本

3.2.6

### 前端框架

Vue

### 问题描述

使用`const { data } = useRequest(getTodoList);`获取到data后，不用setCache修改缓存，直接 `data.value = '随意'` 替换后，缓存结果也会被修改。
其他缓存模式我没有去尝试

### 复现步骤

```js
{
  id: 'base',
  baseURL: '',
  statesHook: VueHook,
  cacheLogger: import.meta.env.DEV,
  requestAdapter: xhrRequestAdapter(),
  shareRequest: true,
  // 设置为null即可全局关闭全部请求缓存
  cacheFor: null,
}
```
这是我的alova的config，我在method中使用了
```js
const getTodoList = currentPage =>
  alova.Get('/todo/list', {
    name: 'todoList',
    cacheFor: {
      mode: 'memory',
      expire: 60 * 10 * 1000,
    }
  })
```

**Comment by H2z2H** [comment]
版本是`"alova": "^3.2.3",`

**Comment by MeetinaXD** [comment]
未能复现你提到的问题，请提供一个可复现的线上 demo。

**Comment by MeetinaXD** [comment]
未能复现你提到的问题，请提供一个可复现的在线 demo。

**Comment by H2z2H** [comment]
https://github.com/H2z2H/alova-cache-test.git，这是复现的demo。
具体的表现为data为对象时，修改data里面的某个属性值会连带修改缓存值，详细操作在复现demo的app.vue中。

**Comment by H2z2H** [comment]
> 未能复现你提到的问题，请提供一个可复现的在线 demo。

已提供

**Comment by MeetinaXD** [comment]
感谢反馈，问题已复现。看来我先前对 issue 的描述有些理解错误。

我们将尽快处理该问题。
