### ISSUE TITLE
[Bug Report] 使用usePagination分页时，watchingStates没有设置、或者为空数组的情况下，改变请求中的某一个参数，会触发多次请求，page参数也会改变

### ISSUE THREAD

**Issue by Slodezzm** [alovajs/alova#59]
### Reproduction Link

暂无

### alova Version

"alova": "^2.0.16"， "@alova/scene-vue": "^1.0.4"

### Describe the Bug

```typescript
import { ref } from 'vue'
import { usePagination } from "@alova/scene-vue"
import { get_news_page_hot_info } from "@/api"
import type { HomeTabType, NewsType } from "@/models"
const { tabInfo } = defineProps<{tabInfo: HomeTabType}>()
const newId = ref<number>(0)
const {
  loading, data, isLastPage, page
} = usePagination((page) =>
  get_news_page_hot_info({
    firstFlag: page === 1 ? 1 : 0,
    newId: newId.value,
    hotListId: 0,
    videoId: 0,
    pageNo: page,
    businessType: 1,
    subclass: tabInfo.subclass == '全部' ? '' : tabInfo.subclass
  }),
  {
    append: true,
    initialData: [],
    debounce: [500],
    preloadNextPage: false,
  }
)
const loadMore = () => {
  if (!loading.value && !isLastPage.value) {
    newId.value = data.value[data.value.length - 1].newsCollectInfo.newInfo.newId
    page.value++
  }
}
```

### Reproduce Steps

暂无

**Comment by JOU-amjs** [comment]
我仔细看了你的代码片段，是不是指newId.value改变后，触发了多次请求？

**Comment by Slodezzm** [comment]
嗯是的，不知道是不是bug，其他没有多个参数改变的情况下，使用usePagination时，请求是正常的，我试了下如果不改变newId的值时，请求也是正常的。

**Comment by JOU-amjs** [comment]
我刚才使用了你的代码片段复现了你的问题，但这个并不是bug，原因如下：

在未关闭缓存（alova默认会开启get缓存），并且未关闭usePagination的preloadPreviousPage（预加载前一页数据）的情况下，在翻页后会预加载前一页数据，当在翻页时如果未改变newId值，此时会命中首次加载时的缓存，所以不会重新发起请求，但在翻页的同时改变了newId值会导致无法命中缓存，此时就会触发预加载的请求了，也就是你现在看到的重复请求问题。
缓存匹配规则可以看以下链接的最底部
https://alova.js.org/zh-CN/learning/response-cache

建议做法：
1. 设置`preloadPreviousPage: false`
2. 关闭缓存
选择任意一项都可以解决这个问题。

**Comment by Slodezzm** [comment]
谢谢谢谢，问题已经解决了。

**Comment by Slodezzm** [comment]
谢谢谢谢，问题已经解决了。

**Comment by JOU-amjs** [comment]
😁😁🤞欢迎常来提问

**Comment by Slodezzm** [comment]
好的好的，厌倦了axios的配置繁杂，首次尝试用alova，感觉数据请求和交互更加简洁，但是新手上路好多参数上面还是摸不着头脑，希望能够继续完善下文档。谢谢！

**Comment by JOU-amjs** [comment]
哈哈，这是个好建议哦
只是，其实光文字确实更难理解，后期会出一些视频讲解，这样对新手来说就更加友好了
