### ISSUE TITLE
[Bug]: 分页请求策略 usePagination

### ISSUE THREAD

**Issue by PdxLook** [alovajs/alova#593]
### 这是否是一个 Bug？

- [x] 我已经确认我要报告的是一个 Bug

### 这个问题是否已经存在？

- [X] 我已经确认这个 Issue 没有被报告过

### Alova 版本

3.2.4

### 前端框架

Vue

### 问题描述

```
// 分页逻辑
const {
  loading,       // 加载状态
  data,          // 列表数据
  isLastPage,    // 是否为最后一页
  page,          // 当前页码
  pageSize,      // 每页数据条数
  pageCount,     // 总页数
  total,         // 数据总量
  onComplete,    // 完成回调
} = usePagination(
  (page, pageSize) => pullIndex(page, pageSize),
  {
    total: response => response.count,
    data: response => response.product_list,
    page: response => response.param.page,
    pageSize: response => response.page_size,
    pageCount: response => Math.ceil(response.count / response.page_size),
    debounce: 300,    // 设置请求间隔（可以根据需求调整）
    preloadPreviousPage: false,  // 是否预加载上一页
    preloadNextPage: false,      // 是否预加载下一页
    append: true,   // 启用追加模式
    initialData: {
      total: 0,
      data: [] // 确保初始化时有空数据数组
    },
    initialPage: 1,       // 初始页码
    initialPageSize: 8    // 每页数据条数
  }
);
```

![image](https://github.com/user-attachments/assets/70cfc55d-f308-4cf4-aca8-571fe179612a)

如果列表做的触底加载分页，会导致每次分页数据加载滚动到顶部

### 期望的表现

考虑触底加载场景不需要滚动到最顶部

### 复现链接

1

### 复现步骤

触底加载分页

**Comment by PdxLook** [comment]
查看源码，append为true的情况下， data整个列表被替换重新绑定，

**Comment by MeetinaXD** [comment]
没理解你提的问题具体是什么，能否重新描述一下？

**Comment by MeetinaXD** [comment]
你只是复制了一次原文，这不是重新描述。

其次，如果我理解的意思和你想要表达的一致。你所提到的「问题」就是文档里实现的特性，这就是预期行为，我不理解为什么会是问题。

再者，如果实在不希望触底回到顶部，不调用 `scrollTo(0)` 即可，这也不是 alova 的行为。

**Comment by MeetinaXD** [comment]
上文所提到的效果和文档描述的相一致，因此这不是一个 bug，现在关闭这个 issue。

如果有需求建议，请移步至 discussion 发起一个 Feature Request。

**Comment by PdxLook** [comment]
@MeetinaXD   append是把数据追加，应用场景在页面下滑触底加载的情况下；那么在下滑触底加载分页的情况下，页面会回到顶部；而回到顶部的原因不是scrollTo(0)导致的，就算阻止了scrollTo(0)，页面也会重新渲染；前面有提到append的情况下不是追加源码中不是data=[...data,...newdata]；不知道这样描述你能理解吗

**Comment by MeetinaXD** [comment]
原来是这个意思。但我的回应依然如旧：这不是一个 bug。

### 关于 append 后列表从头渲染

诚如你所说，alova 在 append 后替换了原 data 所指向的列表，可能会导致一些情况下整个列表重新渲染的行为，也就是上面提到的「回到了顶部」。这也是 vue 在文档里提到 `v-for` 要和 `key` 一起使用的原因，vue 会确保已有的元素位置不变。


### 为什么要替换整个列表

- 不采用 vue2 风格的 Array.push 是因为 alova 是一个适配多框架的请求库，在 react 中就是通过替换为新的data（在这里是数组）触发重新渲染
- 在 vue 中这样也完全没问题，why not

### Prove it

请看 demo：[Load More List - Vue](https://codesandbox.io/p/sandbox/github/alovajs/alova/tree/main/examples/vue)

你有这个疑虑的原因也许是一开始就带着答案来寻找问题，但也许这不是一个真正的问题。

**Comment by PdxLook** [comment]
@MeetinaXD   

感谢你的回答， 是我本地代码导致的 此问题。
