### ISSUE TITLE
[Bug]: useWatcher actionDelegate 触发时使用的不是最新的依赖

### ISSUE THREAD

**Issue by Limsanity** [alovajs/alova#596]
### 这是否是一个 Bug？

- [X] 我已经确认我要报告的是一个 Bug

### 这个问题是否已经存在？

- [X] 我已经确认这个 Issue 没有被报告过

### Alova 版本

3.2.1

### 前端框架

React

### 问题描述

```js
const [name, setName] = useState('1');

useWatcher(
    () => {
      return getData({ name });
    },
    [name],
    {
      middleware: actionDelegationMiddleware('test'),
    }
  )

// 变更 name
setName('2') // 触发接口首次调用
setName('3') // 触发接口二次调用


// 变更 name 之后触发以下代码，接口调用参数 name 还是首次调用的 2
accessAction(getList.name, (action) => {
  action.send();
})
```

### 期望的表现

accessAction 调用的接口应该使用最新的依赖值

### 复现步骤

暂无

**Comment by MeetinaXD** [comment]
方便在 codesandbox 上放个复现 demo 吗

**Comment by Limsanity** [comment]
> 方便在 codesandbox 上放个复现 demo 吗

可以看看这个链接：https://codesandbox.io/p/sandbox/pw2z3s。
复现步骤：点两下 update name 按钮，再点一下 access action 按钮，这个过程中看看 chrome devtool 的请求参数。

**Comment by MeetinaXD** [comment]
感谢反馈，已确认是 bug。我们尽快解决！

**Comment by JOU-amjs** [comment]
@Limsanity 已发版修复
