### ISSUE TITLE
[Bug Report]设置全局请求拦截器后 invalidateCache('List') 不能清除缓存

### ISSUE THREAD

**Issue by gxdvip** [alovajs/alova#6]
### 重现链接

暂无

### alova 版本

2.0.0

### 描述一下你遇到的问题。

```javascript
const list = params => alovaInstance.Get('/ad', { name: 'List', params })

//……

const del = id => alovaInstance.Delete('/ad/del/' + id)
const { send, onComplete } = useRequest(id => del(id),{
      immediate: false
})
onComplete(() => {
  //invalidateCache()        //没问题。
  invalidateCache('List')  // 不生效，缓存未清除
})
```

invalidateCache() 传其他参数也无效（例如正则、对象）。

### 重现步骤

1. 设置获取列表接口 alovaInstance.Get 名称为 'List'
2. 添加、编辑、删除 完成时调用 invalidateCache('List') 清除缓存
3. send 调用获取列表接口

### 设备/浏览器/浏览器版本

Mac Ventura v13.2.1/Google Chrome v110.0.5481.177

**Comment by JOU-amjs** [comment]
你好，还是很感谢你的issue哦，我刚检查了unit test，是有覆盖`invalidateCache`的测试，然后尝试写了个demo测试了`invalidateCache`的功能，也没有发现类似问题，[demo链接在这](https://codesandbox.io/p/sandbox/quizzical-wind-tuiigl?file=%2Fsrc%2FApp.vue&selection=%5B%7B%22endColumn%22%3A21%2C%22endLineNumber%22%3A6%2C%22startColumn%22%3A21%2C%22startLineNumber%22%3A6%7D%5D)。

不知你的项目是如何的，可否在[stackBlitz](https://stackblitz.com/)、[codesandbox](https://codesandbox.io/)中复现下bug，我会在第一时间查看问题的。

感谢！！！

**Comment by gxdvip** [comment]
```javascript
const alovaInst = createAlova({
  //……
  beforeRequest: (method) => {
      method.config.headers.token = 'token'
  },
 //……
})
```

还用你的demo,  设置全局请求拦截器 就出现我描述的情况了。

**Comment by JOU-amjs** [comment]
😁发现了个大bug，我稍后修复下再回复你

**Comment by JOU-amjs** [comment]
已发布v2.0.2解决这个问题。

**Comment by gxdvip** [comment]
已验证解决了。多谢！

**Comment by JOU-amjs** [comment]
🤞我才要感谢你喜欢我写的东西😁
