### ISSUE TITLE
[Bug]: 使用 useRequest 时， data 无法正确推导出数据类型

### ISSUE THREAD

**Issue by mote-ice** [alovajs/alova#607]
### 这是否是一个 Bug？

- [X] 我已经确认我要报告的是一个 Bug

### 这个问题是否已经存在？

- [X] 我已经确认这个 Issue 没有被报告过

### Alova 版本

3.2.6

### 前端框架

Vue

### 问题描述

<img width="1026" alt="iShot_2024-12-12_10 46 17" src="https://github.com/user-attachments/assets/69e6497e-41d3-4788-b3ef-876a0e9596c1" />
<img width="1008" alt="iShot_2024-12-12_10 46 30" src="https://github.com/user-attachments/assets/659ec72d-b091-4b91-bd97-5933d13bb67e" />

### 期望的表现

希望可以像 res 一样推到出正确的数据类型，方便使用

### 复现步骤

![code_1](https://github.com/user-attachments/assets/d1f3435f-c7bb-4542-9cca-eb6556ddf0d7)
![code_2](https://github.com/user-attachments/assets/bfa44a3f-36ad-468b-81c1-4f2e451eb693)
![code_3](https://github.com/user-attachments/assets/c3b2b352-257f-4a5d-8168-e12710d1f2e3)

**Comment by MeetinaXD** [comment]
请提供可复现的线上demo。

**Comment by MeetinaXD** [comment]
你提供的 demo 行为是正常的哦

<img width="485" alt="image" src="https://github.com/user-attachments/assets/f3bf98c7-4a9c-4fca-bb67-ae3b5097757b" />

**Comment by mote-ice** [comment]
![iShot_2024-12-12_15 56 43](https://github.com/user-attachments/assets/bf1e417d-79ab-45b8-9fd3-75cf6909902f)

那这个就很奇怪了，我这里总是 any, 我检查了我的环境也没有其他异常

**Comment by mote-ice** [comment]
我将代码做如下修改之后可以正常：
![iShot_2024-12-12_15 58 31](https://github.com/user-attachments/assets/8689c5d6-255a-4a60-8cd8-8c84652e2f20)
![iShot_2024-12-12_15 58 40](https://github.com/user-attachments/assets/0f427f97-333b-49a0-bfa1-c9702ed41c7f)


所以 我目前觉得应该是由于我在自定义响应拦截时 对 responded ：
`
const interceptResponse: AlovaOptions<AlovaGenerics>["responded"] = {
   async onSuccess() {},
   async onError() {},
   async onComplete() {},
};
`
类型定义存在问题，不知有什么其他的办法

**Comment by MeetinaXD** [comment]
我大概了解问题所在了。问题在于你在外部定义了 `interceptResponse`，其中AG使用了 AlovaGenerics 类型，这会导致框架类型丢失。

建议不要将响应拦截器写在外部。
