### ISSUE TITLE
[Feature Request] Does alova work in nodejs runtime

### ISSUE THREAD

**Issue by bhavya3024** [alovajs/alova#61]
### In what situation do you need this function to solve the problem?

Can use in backend servers for communication with third party apis!

### What do you expect the API to look like?

N/A

**Comment by JOU-amjs** [comment]
I think no.
alova targets client request library, and not consider to be use in server side, so it is designed to bind with UI framework.

**Comment by JOU-amjs** [comment]
SSR is just a client code that is generated in backend server. but these code are run in client.
The topic of this issue is "can alova send request in nodejs", so my answer is no.
