### ISSUE TITLE
[Feature Request] 异常处理机制

### ISSUE THREAD

**Issue by kenixFog** [alovajs/alova#63]
### 你在什么情况下，需要这个功能解决什么问题？
1、感觉目前的异常机制有些不完备
  ① responded中 onSuccess 抛出的异常，无法被responded中 onError捕获
  ② responded中 onSuccess 抛出的异常，可以被useRequest提供的 onError回调捕获，却无法通过useRequest提供的 error获取
  ③ beforeRequest 中抛出的异常，既无法被responded中 onError捕获，也无法通过useRequest提供的 onError回调捕获，也无 
       法通过error获取
2、这样，就可能需要再单独的请求体外增加try...catch，增加使用成本

### 你期望的 API 是什么样子的？
1、拿异常来说，封装程度越高，越友好，使用者不需要关心是哪个环节的出了异常
2、只要useRequest或useWatcher过程中发生了异常，不论是在beforeRequest，还是responded中的onSuccess 、onError甚至其它环节的业务中抛了异常，对于使用者而言，最好能通过useRequest提供的error和onError获取到
3、至少提供钩子函数可以对异常可以统一处理（这样有便于针对具体业务，对alova进行简单的二次封装），在统一异常的处理钩子函数中（可以存在默认处理方式，比如抛出异常），也可覆写，可以自行进行业务处理（日志、提示信息等后），选择继续抛出异常，或return 或不做任何处理：
   ① 如果抛出异常（可做为alova默认处理机制），则可以被useRequest等提供的error和onError获取
   ② return  ***，则表示整个请求过程存在返回结果，结果可根据业务自定定义，用于data结果值
   ③ 不做任何处理的，可在method中增加defaultData(或者可沿用iniatData)作为data结果值，

**Comment by kenixFog** [comment]
补充：
GlobalFetch() 和 axiosRequestAdapter() 对返回的结果是否成功，标准不统一，同样500错误，fetch触发responded的onSuccess，axios触发responded的onError，关于这个问题，不晓得作者是否考虑统一处理？

**Comment by JOU-amjs** [comment]
感谢你的反馈啊，
不得不说，你对alova的异常反馈机制已经有比较深入的了解，我将一一解答下你的问题

> ① responded中 onSuccess 抛出的异常，无法被responded中 onError捕获

其实这个是有意为之的，，在设计alova的时候我们希望将请求错误的异常和响应数据处理错误的异常分离开，而不希望混淆在一起处理，如果是相同的处理方式，可以统一一个函数并在不同地方调用，这可以给开发者更大的自由度，好吧，这其实也参考了axios的异常处理机制

> ② responded中 onSuccess 抛出的异常，可以被useRequest提供的 onError回调捕获，却无法通过useRequest提供的 error获取

经过测试目前是可以做到这点的，[看这边的例子](https://codesandbox.io/s/cold-haze-s8jour?file=/src/App.vue)

> ③ beforeRequest 中抛出的异常，既无法被responded中 onError捕获，也无法通过useRequest提供的 onError回调捕获，也无
法通过error获取

当beforeRequest指定为异步函数时，抛出的异常会被useRequest正常捕获，error中也有对应的错误对象，但beforeRequest为同步函数时却打印出了错误信息，这应该是一个bug，稍后我会修复一下。

> 2、只要useRequest或useWatcher过程中发生了异常，不论是在beforeRequest，还是responded中的onSuccess 、onError甚至其它环节的业务中抛了异常，对于使用者而言，最好能通过useRequest提供的error和onError获取到
3、至少提供钩子函数可以对异常可以统一处理（这样有便于针对具体业务，对alova进行简单的二次封装），在统一异常的处理钩子函数中（可以存在默认处理方式，比如抛出异常），也可覆写，可以自行进行业务处理（日志、提示信息等后），选择继续抛出异常，或return 或不做任何处理：

这点其实目前是可以做到的，在全局的responded中统一处理异常，当在全局的responsed的onSuccess、onError中抛出的异常都会被useRequest、useWatcher的onError和error中体现，如果未设置全局错误处理，抛出的错误也都将体现在useRequest、useWatcher的onError和error中，以下是官网的介绍
![image](https://user-images.githubusercontent.com/29848971/236597812-76e5c66b-c417-496c-b3bd-ccb15c088391.png)

https://alova.js.org/zh-CN/learning/alova-instance#%E8%AE%BE%E7%BD%AE%E5%85%A8%E5%B1%80%E5%93%8D%E5%BA%94%E6%8B%A6%E6%88%AA%E5%99%A8

**Comment by JOU-amjs** [comment]
> 补充： GlobalFetch() 和 axiosRequestAdapter() 对返回的结果是否成功，标准不统一，同样500错误，fetch触发responded的onSuccess，axios触发responded的onError，关于这个问题，不晓得作者是否考虑统一处理？

这点我觉得你的观察也是很仔细的，在做这两个适配器设计的时候我们也纠结了一段时间，也尝试过几次方案，现在的样子就是我们最终的方案，理由是尽量让对应的适配器保留它原有的样子，让开发者在使用它们的时候也会感到熟悉，而不是迷惑，同时，我们在编写这些适配器代码的时候，也不需要再特殊处理这些，只需要交由原请求工具即可。

**GlobalFetch**适配器内部是使用fetch api的，它的错误处理特点是，只要服务端有回应就不会抛出错误，无论status是什么，而在请求超时、网络断开时才会抛出错误。
**axiosRequestAdapter**适配器用的是axios发起的请求，axios会在遇到status诸如404或500的情况下认为是请求错误，也会抛出一个axios封装的错误对象，其内部包含了请求错误信息，而非简单的Error对象。

**Comment by JOU-amjs** [comment]
已发布了2.3.0解决beforeRequest为同步函数时loading和error不改变的问题，如果还有问题你可以再这边继续追问，或重新打开issue

**Comment by kenixFog** [comment]
总的来说，异常都能获取到，但是感觉还是少了一个全局的钩子函数，尤其是beforeRequest中的异常，只能通过onError捕获~这就造成每个方法都需要单独去处理这个异常~~但实际使用中，beforeRequest中基本都是全局通用的功能~~
比如判断token、是否具有请求权限等，如果不存在、没权限，可能跳转到登录界面（这个应该不影响），也有可能返回空数据（或其非正常数据），覆盖现有页面的数据，但是目前数据无法统一返回，不像在responded-onError中，return的结果可以当做返回值~

至于异常后统一返回数据，我自己的做法是，自定义配置项defaultData，其属性和正常的结果中属性保持一致，但值为null或[]等，然后异常处理时，根据需要选择是否return defaultData，但目前beforeRequest的异常机制。。导致这个无法统一做到。。

**Comment by JOU-amjs** [comment]
这个提议很好哦，我思考下各场景的使用情况，如果可以的话，后续可以添加进去😃

**Comment by Emily-0616** [comment]
@JOU-amjs 现在统一的异常处理方案是什么，拦截器success 抛出的异常无法被拦截器的error 捕获的情况下，是否意味着每次请求在调用时都要主动捕获？

**Comment by graphsay** [comment]
刚开始用alova，发现了拦截器onSuccess 抛出的异常无法被拦截器的onError 捕获，而文档里说在useRequest里这个是可以捕获的，我觉得二者需要统一才好。。建议尽快实现拦截器onSuccess 抛出的异常可以被拦截器的onError 捕获。否则加一个参数选项也行，由参数控制 异常要不要被捕获。
