### ISSUE TITLE
[Bug Report] 请求共享在请求超时的情况下的混乱问题

### ISSUE THREAD

**Issue by kenixFog** [alovajs/alova#66]
### In what situation do you need this function to solve the problem?

PS: 不清楚是不是使用方式有误~~

使用场景
1、2个按钮A、 B，对应请求A1、B1，其中A1直接响应，B1延迟10秒~~全局超时时间5秒（B1肯定超时）
2、单独点击按钮并等待各请求完成响应，A1正常，B1超时，没问题
3、点击B按钮，再点击A按钮，A的加载状态跟B按钮保持同步，并且结果也显示超时，无法正常获取结果

猜测是不是useRequest内部处理有问题？或者使用上需要注意什么？

### What do you expect the API to look like?

1、各请求的状态、结果等应该不受影响

**Comment by kenixFog** [comment]
![image](https://user-images.githubusercontent.com/29566225/236620814-71fd0413-8e1f-4d4c-9324-e9590dc22025.png)

**Comment by kenixFog** [comment]
再次经过测试，缩短save方法的延迟时间至10秒后，触发save，等待响应完成后，想要正常触发list的等待时间相应减少，大概也就是save触发开始，到请求处理完毕，耗时10秒，在这期间，只要触发list方法，那么list的加载状态、返回结果均为save的结果~~考虑要么内部处理机制有问题，要么使用方法的问题导致了实例状态间的共享~

**Comment by JOU-amjs** [comment]
好的，已明白，我明天调试一下，不出意外明天可以解决，感谢你的反馈哦😃

**Comment by JOU-amjs** [comment]
我写了一个demo尝试复现你说的问题，但好像一切都正常
你可以帮我看下是我没写对吗？链接在这：https://codesandbox.io/p/sandbox/practical-dubinsky-5le37g?file=%2Fpackage.json&selection=%5B%7B%22endColumn%22%3A29%2C%22endLineNumber%22%3A17%2C%22startColumn%22%3A29%2C%22startLineNumber%22%3A17%7D%5D

或者，如果方便的话，你可以提供一个最小可复现的demo吗，通过github、sandcodebox、stackBlitz都可以，如果可以，也提供一下你正在使用的alova版本

**Comment by kenixFog** [comment]
先说说我自己的使用场景
1、进行了简单的二次封装，通过自定义了一些配置，便于业务开展，举个例子，比如以下三个属性： 
      // 是否自行处理异常（false，发生异常时，responded.onError不再抛出异常，并将defaultData作为返回值；true，responded.onError将抛出异常，由使用者手动通过useRequest的OnError回调处理特殊业务）
     handleError：boolean
     // 默认返回值（handleError = false时，用于responded.onError的返回结果）
     defaultData：any
    //  适配器类型default：GlobalFetch，axios：axiosRequestAdapter
    adapter：'dealut' | 'axios'

2、这样就导致每个方法无法公用一个实例，最方便的是每个请求，根据相应的参数，实时创建alova实例（目前还不清楚这样会不会导致性能问题），或者根据实际需求和相应的规则，预先定义若干个实例，根据参数选择其中一个；

3、以上场景，就导致，最多一个方法对应一个alova实例

由于本地环境剥离最小不太容易，就基于你的例子，尝试了下，本地直接使用，确实无法复现问题，但稍微稍加改造，虽然实际问题没有复现，但发现了一些新情况

PS：先全局关闭缓存

改动一：
```
   '[POST]/save': () => {
    // 延迟10秒返回数据
    await new Promise((resolve) => {
      setTimeout(resolve, 10000)
    })
    return {
      msg: 'success',
    }
  },
```
   更改为如下（不要纠结这种比较low的延迟的方式），
```
   '[POST]/save': async () => {
    // 延迟10秒返回数据
    const start = Date.now()
    const expire = start + 10 * 1000

    while (Date.now() < expire);
    return {
      msg: 'success',
    }
  },
```
  
  改动前：一切正常，该超时超时，该返回返回，
  改动后：首先，原本超时的save不会在超时，一定会经过10秒返回结果；其次，先点击save（请求等待中），马上再点击list，l会同时与save返回正确结果；当然如果先点击list，不用等待，正常返回，再点击save，等待返回正确结果

 改动二：在改动一的基础上，取掉async
 先点击list，正常返回；先点击save，请求等待结束，一定会正常返回结果，但结果返回之前，list无法点击；

 改动三：在改动二的基础上，复制新的alova实例 alovaInst1，save使用新实例
 先点击list，正常返回；先点击save，请求等待结束，一定会正常返回结果，再此前进，list可以点击，但返回结果需要等待sava结束一起返回（同改动一的效果）


自己的测试环境，没有用@alova/mock，但是从以上测试，是否感觉@alova/mock中的处理机制存在问题？
实时使用时也是一个方法，一个alova实例

**Comment by kenixFog** [comment]
本地重新进行了测试，将原本的返回方式：
```

() => {
    // 延迟10秒返回数据
    const start = Date.now()
    const expire = start + 10 * 1000
    while (Date.now() < expire);
    return {
      msg: 'success',
    }
}

```
修改为

async () => {
    // 延迟10秒返回数据
    await new Promise((resolve) => {
      setTimeout(resolve, 10000)
    })
    return {
      msg: 'success',
    }
}

最开始描述的问题消失。感觉是不是由于前端是模拟的服务器返回数据，但实际还是能够区分返回结果是否是promise对象？但实际开发，结果都有后台返回，应该没有promise这一说~而超时的处理，却根据返回结果类型进行了处理啊（瞎猜的）

**Comment by JOU-amjs** [comment]
```javascript
'[POST]/save': async () => {
    // 延迟10秒返回数据
    const start = Date.now()
    const expire = start + 10 * 1000

    while (Date.now() < expire);
    return {
      msg: 'success',
    }
  }
```
以上改动点导致的问题其实是不对的，因为mock本身其实是在前端模拟的异步返回数据，此时把它从异步改为了同步，这就导致js线程堵塞了，其他的执行都需要等待save的10秒之后才能执行，因此也就没有异步之说了，这也解释了你的三次改动的情况。

但是在实际场景下，请求都是异步的，我在demo中的save写法就是异步方式，这是和实际请求相符的。

**Comment by JOU-amjs** [comment]
按你的封装描述，我可能没办法想象出你的封装是如何的，因此也无法精确重现你的问题，如果需要重现，希望还是可以提供一份可复现的代码，这样才可以帮你解决问题😌

**Comment by kenixFog** [comment]
大概懂你说的意思了，咱们换个场景，假设只有一个请求，方式A就是你的save方式，async，方式B是我的没有async， while~~那方式A超时~~方式B有没有办法，也最终按超时处理？按目前的状态，mock下，2个请求，如果都不加async，理论上也是会互相影响的，只不过。。一般mock都是直接返回数据，响应大概也就几ms~~感受不到罢了~~~但是你说的同步、异步导致的问题还是存在的~~本着严谨的求学精神，有没有办法彻底避免这种情况

**Comment by kenixFog** [comment]
那现在感觉好像又有个新问题，你的save方式会导致超时，我得save方式，并没有超时，感觉这个不太合理？mock中就是处理了一些逻辑（虽然。这样看上去很傻，直接返回数据多好），耗时100ms~~但是超时时长50ms~~这样的话，应该也无法超时~~
我的意思，虽然我说的这种情况很无聊，但本着求学的态度，有没有当时可以规避？

**Comment by JOU-amjs** [comment]
即使不设置为异步函数，mock内部也会当做异步处理，mock有个delay参数，可以用来控制延迟多久返回数据，不会存在你说的这个问题哦

**Comment by kenixFog** [comment]
烦请看看这个，是不是使用有问题，实际save并没有超时

[测试](https://codesandbox.io/p/sandbox/exciting-leakey-6rbzzx?file=%2Fsrc%2FApp.vue&selection=%5B%7B%22endColumn%22%3A1%2C%22endLineNumber%22%3A48%2C%22startColumn%22%3A1%2C%22startLineNumber%22%3A48%7D%5D)

**Comment by JOU-amjs** [comment]
> ```js
> '[POST]/save': async () => {
>     // 延迟10秒返回数据
>     const start = Date.now()
>     const expire = start + 10 * 1000
> 
>     while (Date.now() < expire);
>     return {
>       msg: 'success',
>     }
>   }
> ```
> 
> 以上改动点导致的问题其实是不对的，因为mock本身其实是在前端模拟的异步返回数据，此时把它从异步改为了同步，这就导致js线程堵塞了，其他的执行都需要等待save的10秒之后才能执行，因此也就没有异步之说了，这也解释了你的三次改动的情况。
> 
> 但是在实际场景下，请求都是异步的，我在demo中的save写法就是异步方式，这是和实际请求相符的。

还是非常感谢你对mock模块的测试。
这种是同步的写法，也称为堵塞写法，堵塞期间界面是无法进行任何操作的，因此这样是正常的。

我的意见是，可以先不纠结mock这边的问题了，把更多精力放在你当初提出的问题上，如果可以，希望还是可以提供一份可复现的代码，这样才可以帮你解决问题😌

**Comment by kenixFog** [comment]
[看看这个呢](https://codesandbox.io/p/sandbox/exciting-leakey-6rbzzx?file=%2Fsrc%2FApp.vue&selection=%5B%7B%22endColumn%22%3A13%2C%22endLineNumber%22%3A31%2C%22startColumn%22%3A13%2C%22startLineNumber%22%3A31%7D%5D)

1、测试环境，用的mock是另外的插件
2、其中save依旧是按照错误形式
3、先点击save在点击list，全部返回超时


同样的代码（保持save的错误方式），但是如果换成@alova/mock  无法复现

**Comment by kenixFog** [comment]
[看看这个呢](https://codesandbox.io/p/sandbox/exciting-leakey-6rbzzx?file=%2Fsrc%2FApp.vue&selection=%5B%7B%22endColumn%22%3A13%2C%22endLineNumber%22%3A31%2C%22startColumn%22%3A13%2C%22startLineNumber%22%3A31%7D%5D)

1、测试环境，用的mock是另外的插件
2、其中save依旧是按照错误形式
3、先点击save在点击list，全部返回超时


同样的代码（保持save的错误方式），但是如果换成@alova/mock  无法复现

**Comment by JOU-amjs** [comment]
不管是nodejs、还是浏览器上，js都是单线程的，按这种堵塞的方式编写，无论是怎么样都会出现这样的问题。
下面是我直接使用window.fetch请求vite模拟接口的，同样存在你说的问题，这是单线程的问题，而不是请求的问题。

[详见这里的demo](https://codesandbox.io/p/sandbox/exciting-leakey-6rbzzx?file=%2Fsrc%2FApp.vue&selection=%5B%7B%22endColumn%22%3A13%2C%22endLineNumber%22%3A31%2C%22startColumn%22%3A13%2C%22startLineNumber%22%3A31%7D%5D)

**Comment by JOU-amjs** [comment]
关于这点，你可以再深入了解下js单线程的机制

**Comment by kenixFog** [comment]
如果可以确认插件本身没问题，那就太好了。感谢耐心的解答，谢谢

**Comment by JOU-amjs** [comment]
目前是没发现有问题的，只是不能通过while同步堵塞的写法延迟，而是需要通过Promise异步的方式哦
感谢反馈🤞
