### ISSUE TITLE
[bug report] These dependencies were not found:  To install them, you can run: npm install --save alova/GlobalFetch alova/vue

### ISSUE THREAD

**Issue by JOU-amjs** [alovajs/alova#69]
[bug report] These dependencies were not found:  To install them, you can run: npm install --save alova/GlobalFetch alova/vue

_Originally posted by @maicFir in https://github.com/alovajs/alova/issues/60#issuecomment-1537863168_

**Comment by LZDWTL** [comment]
请问下这个问题解决了么？我这边也遇到这个问题了。

**Comment by JOU-amjs** [comment]
@LZDWTL 可以提供一下以下资料吗？
**1. 编译工具（webpack? vite?，还是其他）以及版本**
**2. nodejs版本**
**3. alova版本**
**4. 错误的代码片段**

**Comment by LZDWTL** [comment]
1、工具版本
"webpack": "5.73.0",
"node":"14.20.0"，
"alova": "^2.4.1",
2、截图
![image](https://github.com/alovajs/alova/assets/72549540/da032d14-f1ea-451c-a70c-9aeaf889fa3d)
![image](https://github.com/alovajs/alova/assets/72549540/742e3d1c-bc13-4a95-a906-c43693e594e3)

**Comment by JOU-amjs** [comment]
好的，使用的代码片段可以再贴出来看看吗？我稍后来看下这个问题

**Comment by LZDWTL** [comment]
代码是官网中vue的示例代码，没有做任何修改。
![image](https://github.com/alovajs/alova/assets/72549540/2972b170-1a6d-4cda-aa3b-c2b4523073c3)

**Comment by JOU-amjs** [comment]
好的，我稍后复现下问题

**Comment by JOU-amjs** [comment]
@LZDWTL 根据你的这份配置，我安装的依赖是webpack4.46.0，也出现了你这种问题，但在webpack5.x中是可以正常使用的。

因此这边给出两种方案供参考：
1. 更新vue-cli预设的打包环境到@vue/cli-service 5.x以上
2. 改用以下方式引入
```javascript
import GlobalFetch from "alova/dist/adapter/globalfetch.esm.js";
import VueHook from "alova/dist/hooks/vuehook.esm.js";
```

**Comment by LZDWTL** [comment]
感谢！问题解决了。

**Comment by JOU-amjs** [comment]
🤞🤞🤞你的反馈是我们完善优化的动力，同样感谢
