### ISSUE TITLE
[Bug Report] 分页时，清除缓存只能清除当前分页，其他页未清除。

### ISSUE THREAD

**Issue by gxdvip** [alovajs/alova#7]
### 重现链接

暂无

### alova 版本

2.0.3

### 描述一下你遇到的问题。

加载分页列表。清除缓存只能清除当前分页，其他页未清除。
失效缓存方式都测试过了，结果相同。
以下是测试失效缓存方式
1. 方式1：invalidateCache('list')
2. 方式2：invalidateCache(/list/)
3. 方式3：invalidateCache({name: 'list', filter:()=>true})
4. 方式4: 配置 hitSource: /list/

### 重现步骤

比如有3页，总数据28条。

1. 连续点1、2、3页让缓存生效。
2. 在第3页删除一条数据并失效缓存
3. 调用列表接口（第3页缓存失效成功，显示27条）
4. 在点第1页或第2页，总数据还是显示28条。

**Comment by gxdvip** [comment]
效果有点像 https://alova.js.org/zh-CN/example/paginated-list 这个例子。
只是这个例子没有调用失效缓存。
当前页删除数据后，点其他页就可以看到分页不正常。

**Comment by JOU-amjs** [comment]
我现在来看下这个问题

**Comment by JOU-amjs** [comment]
经过了一天的努力，终于把这两个问题解决了，顺便优化了下usePagination的代码。需要更新alova的版本到2.0.4，更新@alova/scene-*的版本到1.0.1 @gxdvip 

感谢你的反馈！😁🤞

**Comment by gxdvip** [comment]
升级到2.0.4了，发现其他页还是清除不成功。我用本地开发环境真实接口测的。

**Comment by JOU-amjs** [comment]
我这边是可以正常清除缓存，你还需要更新下 **@alova/scene-xxx到1.0.1**，以下是我的测试代码片段
```javascript
// 分页接口
const queryStudents = (page, pageSize, studentName, clsName) =>
  alovaInst.Get("/query-students", {
    name: 'list',
    params: { page, pageSize, studentName, clsName }
  });
```

```javascript
// 点击事件
const handleInvalidateCache = () => {
  invalidateCache('list');
}
```

分页数据的缓存已被全部删除。

**Comment by JOU-amjs** [comment]
如果是其他的情况，请详细描述下哦，或者提供一个可复现的代码，使用codesandbox或stackBiltz都可以

**Comment by gxdvip** [comment]
没有使用@alova/scene。

1. 列表用 useWatcher。
2. 删除用 useRequest。
```javascript
//1.列表
const list = params => agent.Get('/ad', { params, name: 'list' })
const { send, data, loading, onSuccess, onError } = useWatcher(
  () => list(params),
  [ params ],
  {
      initialData: {
        total: 0,
        data: []
      },
      immediate: true
  }
)

//2.删除
const del = id => agent.Delete('/ad/del/' + id, {}, { name: 'ad-del' })
const { send, onSuccess } = useRequest(
  id => del(id),
  {
    immediate: false
  }
)

onSuccess(() => {
  //删除成功清除缓存
  invalidateCache('list')
})
```

**Comment by JOU-amjs** [comment]
从你提供的代码上看是没问题的，设置`/ad`的method实例名称为list，然后调用`invalidateCache('list')`清除缓存。但这个是你的真实代码片段吗？应该是会报错吧，因为我看到重复定义了`onSuccess`。或者凭借这点代码我也不太能判断问题所在，你可能需要检查下`invalidateCache`是否有被调用。

**Comment by gxdvip** [comment]
截取的片段，代码没问题，invalidateCache调用了，当前页的缓存也成功清除了，就是其他页不行。

**Comment by JOU-amjs** [comment]
我按你的方式写了个demo，确实没有发现问题，你可以参考下。
https://codesandbox.io/s/zealous-gwen-tj1j87

**Comment by JOU-amjs** [comment]
你好，你的问题已经解决了吗？

**Comment by gxdvip** [comment]
找到原因了。问题出在 接口接收参数 params。
❌错误的
```javascript
//list.vue
//……
const params = ref({ page: 1, pageSize: 10 })

//api.js ……
params = unref(params)
const list = params => alovaInst.Get('/ad', { params, name: 'list' })
//……
```

✅正确的
```javascript
//list.vue
//……
const params = ref({ page: 1, pageSize: 10 })

//api.js……
params = unref(params)
//简便写法
//const list = params => alovaInst.Get('/ad', {params: {...params}, name: 'list' })
const list = params => alovaInst.Get('/ad', {
  params: {
    page: params.page, 
    pageSize: params.pageSize
  }, 
  name: 'list' 
})
//……
```

**Comment by JOU-amjs** [comment]
😉😉😉你的反馈真的起到了很大的帮助！
这个问题已修复，已发布v2.0.5。
问题源头出在使用了引用类型作为请求参数，而alova内部是使用这些请求参数实时生成key来管理对应的缓存数据的，因此当`page`改变时，相应的method实例内的param实例也改变了，导致永远只能匹配当前页的缓存。这也解释了为什么使用解构的方式有效。

解决方案是在失效缓存时，不实时生成method的key，而是使用请求时生成的key，这样即使引用值内部改变了也不会影响key。

**Comment by gxdvip** [comment]
这次使用起来就非常丝滑了 😄
