### ISSUE TITLE
[Feature Request]OpenApi的支持

### ISSUE THREAD

**Issue by Agoines** [alovajs/alova#75]
### 你在什么情况下，需要这个功能解决什么问题？

解决在编写对应的 openapi 后，可以根据yaml生成对应的请求api，无感切换到 alova

### 你期望的 API 是什么样子的？

类似于 [openapi-typescript-axios](https://github.com/OpenAPITools/openapi-generator/blob/master/docs/generators/typescript-axios.md) 这样可以根据 api 自动生成对应请求代码的功能

**Comment by JOU-amjs** [comment]
感谢你的反馈。
我们在稍后了解本块功能后，如果符合我们对后续版本的预期将会尽快支持这些特性的。☺️

**Comment by JOU-amjs** [comment]
通过openapi生成alova请求代码的方案已实现。
https://alova.js.org/next/tutorial/getting-started/extension-integration
