### ISSUE TITLE
[Bug Report] taro适配器 vue3

### ISSUE THREAD

**Issue by HuangYaobin** [alovajs/alova#76]
### 重现链接

https://github.com/HuangYaobin/taro-alova-demo

### alova 版本

2.4.1

### 描述一下你遇到的问题。

按照文档配置, 没有响应式。
```js
import { createAlova } from 'alova';
import AdapterTaroVue from '@alova/adapter-taro/vue';

const alovaInst = createAlova({
  baseURL: 'https://api.alovajs.org',
  ...AdapterTaroVue()
});
```

需要加一行配置，才有响应式。
```js
import { createAlova } from 'alova';
import AdapterTaroVue from '@alova/adapter-taro/vue';
import VueHook from 'alova/vue';

const alovaInst = createAlova({
  baseURL: 'https://api.alovajs.org',
  ...AdapterTaroVue(),
  statesHook: VueHook
});
```

![image](https://github.com/alovajs/alova/assets/51368773/5606ed49-c4de-4de5-92f7-30e966e4e1fc)

loading和data变化，watchEffect监听不到。

### 重现步骤

点击button

**Comment by JOU-amjs** [comment]
非常感谢你的反馈！
经过测试发现`@alova/adapter-taro/vue`的打包方式参数设置有误，目前已发布`@alova/adapter-taro@1.2.1`修复了此问题。
