### ISSUE TITLE
原生小程序支持吗

### ISSUE THREAD

**Issue by breezefeng** [alovajs/alova#80]
### In what situation do you need this function to solve the problem?

原生小程序支持吗

### What do you expect the API to look like?

原生小程序支持吗

**Comment by JOU-amjs** [comment]
不支持哦，alova的设计是usehook形式的，小程序并不支持usehook

**Comment by breezefeng** [comment]
axios默认也是不支持小程序的，但是有人做了兼容

**Comment by JOU-amjs** [comment]
请求的话，alova可以通过适配器实现。只是目前没有对小程序兼容

**Comment by JOU-amjs** [comment]
因为alova的核心是请求策略，我们也正在通过hook来探索更多的请求场景，因此目前暂时也不考虑非hook情况的使用
