### ISSUE TITLE
useRequest 返回的 data 类型支持使用 transformData 的 ReturnType

### ISSUE THREAD

**Issue by kunkuntang** [alovajs/alova#82]
### 你在什么情况下，需要这个功能解决什么问题？

```javascript
interface Todo {
  title: string;
  time: string;
  done: boolean;
}
const Get = alovaInstance.Get('/todo/list', {
  // 将类型写到data参数中，而headers会自动推断，可以不用指定类型
  transformData(data: Todo[], headers) {
    return data.map(item => ({
      ...item,
      status: item.done ? '已完成' : '未完成'
    }));
  }
});

const { data } = useRequest(Get);
// vue: data的类型为Ref<(Todo & { status: string })[]>
// react: data的类型为(Todo & { status: string })[]
// svelte: data的类型为Writable<(Todo & { status: string })[]>
```

感觉直接使用 transformData 的 ReturnType 比取 transformData 的参数会更自由点，因为一般只会定义 transformData 后的类型，不会定义 transformData 数据前的类型，而且也不太关心转换之前的数据类型是什么样子，个人感觉。

### 你期望的 API 是什么样子的？

transformData 使用 ReturnType 作为类型返回

**Comment by JOU-amjs** [comment]
目前的设计就是这样的，即如果method内定义了`transformData`，将会把它的返回值类型作为usehook函数返回的data类型，如下：
<img width="796" alt="image" src="https://github.com/alovajs/alova/assets/29848971/cc873d03-cc48-41c5-be41-055de877b56a">

不知我有没有理解你的问题？

**Comment by kunkuntang** [comment]
> transformData
 const { data } = useRequest()
我的意思是 useRequest 的 data 的类型是根据  transformData 返回类型决定，而不是由 transformData(data: Todo[] ,headers) {} 的参数 data 决定，因为我用的时候如果这样写

```
// 接口返回的数据类型，如果有工具库对接口数据做字段兜底，那么转会后的数据类型是确保安全的，所以是不会关心接口返回的数据类型是什么，还有一种情况是接口可能会根据入参返回不同的数据结构，但是转换后给到视图使用是同一个结构，目前我是要分别对接口数据的返回情况写两种类型的，但是这种类型在转换后就不会再使用到了，这无疑大大增加了写代码的负担
interface ResponseTodo {
  title: string;
  time: string;
  done: boolean;
  status: '已完成' | '未完成'
}

// 转换后的数据类型
interface TransformTodo {
  title: string;
  time: string;
  done: boolean;
}
const Get = alovaInstance.Get('/todo/list', {
  // 将类型写到data参数中，而headers会自动推断，可以不用指定类型
  transformData(data, headers) {
    return data.map(item => ({
      ...item,
      status: item.done ? '已完成' : '未完成'
    })) as TransformTodo[];
  }
});

const { data } = useRequest(Get);
// 这时候的 data 类型为 unkonw， 我希望这里 data 的类型应该是 transformData 函数的返回类型 **TransformTodo[]**
```

**Comment by JOU-amjs** [comment]
你的描述在我理解还是我上面说的场景，这是可以做到的，即使你不在transformData中指定data的类型，但只要保证transformData返回值的类型就可以自动推断。

我昨天尝试也可以正常推断（见截图），不知你的项目中是否有其他地方没用对，建议以下尝试
1、createAlova时传入的statesHook是否正确
2、确认下Get中的transformData是否返回了正确的类型

如果都不行，你可以给我发一个可运行的最小复现项目，上传到GitHub上，我会尽快排查一下问题帮你解决它

**Comment by JOU-amjs** [comment]
你的描述在我理解还是我上面说的场景，这是可以做到的，即使你不在transformData中指定data的类型，但只要保证transformData返回值的类型就可以自动推断。

我昨天尝试也可以正常推断（见截图），不知你的项目中是否有其他地方没用对，建议以下尝试
1、createAlova时传入的statesHook是否正确
2、确认下Get中的transformData是否返回了正确的类型

如果都不行，你可以给我发一个可运行的最小复现项目，上传到GitHub上，我会尽快排查一下问题帮你解决它

**Comment by JOU-amjs** [comment]
对了，关于响应数据的类型，建议看下[alova的typescript](https://alova.js.org/zh-CN/advanced/typescript)，应该会对你有所帮助

**Comment by JOU-amjs** [comment]
@kunkuntang 还存在这个问题吗？如果不是我所理解的那样，可以再详细描述一下吗？
