### ISSUE TITLE
[Feature Request] 有支持取消alova请求的功能吗

### ISSUE THREAD

**Issue by shylock-wu** [alovajs/alova#85]
### 你在什么情况下，需要这个功能解决什么问题？

我发送请求后，能够主动取消

### 你期望的 API 是什么样子的？

配置能够取消的功能

**Comment by JOU-amjs** [comment]
@shylock-wu 可以参考这边 https://alova.js.org/zh-CN/learning/use-request#%E6%89%8B%E5%8A%A8%E4%B8%AD%E6%96%AD%E8%AF%B7%E6%B1%82
