### ISSUE TITLE
建议能够使用快速全局搜索(快捷键方式)

### ISSUE THREAD

**Issue by shylock-wu** [alovajs/alova#86]
### 你在什么情况下，需要这个功能解决什么问题？

文档太多需要搜索
例如[Vite](https://cn.vitejs.dev/)或者其他官网文档中的功能一样
<img width="543" alt="image" src="https://github.com/alovajs/alova/assets/73875874/01abb776-53ca-4928-86c1-d33ae3198a9b">

### 你期望的 API 是什么样子的？

文档太多需要搜索

**Comment by JOU-amjs** [comment]
这是个好建议哦，这些天我尝试加一个上去

**Comment by JOU-amjs** [comment]
已加上algolia支持文档搜索，非常感谢你的反馈哦！🤞
