### ISSUE TITLE
[Bug Report] invalidateCache清空全部缓存数据时无法清除持久化数据

### ISSUE THREAD

**Issue by kenixFog** [alovajs/alova#91]
### 重现链接

~~

### alova 版本

2.5.1

### 描述一下你遇到的问题。

invalidateCache，好像对持久化缓存策略不生效，执行完，缓存依旧生效；对内存模式好像没问题

### 重现步骤

1、测试环境，缓存3分钟，然后有个全局定时器，每1分钟执行一次invalidateCache()
2、memory下，定时器执行完，再次请求，会发起请求；restore模式下，定时器执行完，再次请求，缓存依旧有效

3、观察了下大概是因为invalidateCache并没有针对localStorage中数据进行清除操作

或者说如果invalidateCache的设计只是针对memory模式，是否可以提供针对restore的全局缓存清理接口~~

**Comment by JOU-amjs** [comment]
`invalidateCache`是会去清除持久化的缓存数据的，刚尝试了功能是完好的，[demo链接在这](https://codesandbox.io/s/github/alovajs/alova-examples/tree/main/packages/storage-restore?from-embed)

![image](https://github.com/alovajs/alova/assets/29848971/be9c2cd2-f45d-4bcd-9ed4-4445a6dd90c2)

请检查下你的项目中，传入`invalidateCache`的参数是否正确哦，或者你可以尝试在这个例子上复现下bug吗？

**Comment by kenixFog** [comment]
1、没传参数，直接全局invalidateCache()
2、restore模式下，执行完缓存清理，必须手动刷新页面才能生效么，如果不刷新呢？我是清理完缓存，不刷新页面~
3、我自己手动写了一个清理localStorage中alova缓存的方法，如果执行了，不刷新页面，那缓存也就失效了~

**Comment by JOU-amjs** [comment]
不需要刷新也可以生效
bug已经复现了，稍后修复，非常感谢你的反馈哦！🤞

**Comment by kenixFog** [comment]
另外，2.5.1升级到2.5.2之后，ts类型感觉很多地方飘红~~以下只是其中一处
如下2.5.1
![image](https://github.com/alovajs/alova/assets/29566225/ed6a4528-c824-4b13-a240-6aa7e1a901a5)


如下2.5.2.
![image](https://github.com/alovajs/alova/assets/29566225/2bc18c1a-518a-49ea-af60-b623d278a785)


2.5.2使用时，有什么需要额外配置的么么？

**Comment by kenixFog** [comment]
还有这个（2.5.2）：
![image](https://github.com/alovajs/alova/assets/29566225/eeaf2813-9d56-4c29-8176-389c9dc41154)
![image](https://github.com/alovajs/alova/assets/29566225/b3ec5a15-f4a1-42a8-9574-c2abf507949b)


而且useRequest如果要泛型加持，好像需要传入7个泛型。。而最关注的无非就是一个返回值类型，是否能够，达到只传一个返回值类型，比如useRequest<string>, 或useRequset<Record<string,any>>，或useRequset<boolean>，唯一的一个泛型，就是data返回值的类型~
